from pathlib import Path
import json
R=Path(__file__).parent
# Each row freezes a candidate, derives its commitment, supplies a countercase,
# derives a replacement from that countercase, and follows the replacement.
# The candidate list is a search space, not a claim that the prior baseline was bad.
DATA={
'route':[
('Adding body-turn words to the complete compass route improves the prospective reviewer’s endpoint accuracy.', 'With the same map and endpoint question, the reviewer must answer more accurately with the added turn words.', 'A reviewer who already follows compass bearings gets the same answer from both; conflicting frame habits instead make the added words a distraction. No reviewer comparison exists.', 'Retain both texts as candidates with measured endpoint accuracy as the discriminator.', 'Equal correct answers would provide no accuracy advantage to the longer candidate.', 'UNCERTAIN','human endpoint comparison'),
('The relative command string FRFF reaches the same endpoint from every cardinal initial heading at the same start.', 'North-facing and east-facing starts at (0,0) must end at the same coordinate.', 'Executed north start ends at (2,1); east start ends at (1,-2).', 'Attach the initial heading to a relative command string.', 'The anchored east instance now selects (1,-2), excluding (2,1).', 'REJECTED','route.same_words_different_heading'),
('Map-right and body-right always denote the same compass direction.', 'Facing east, a body-right turn must still point map-right, which is east on the declared north-up map.', 'Facing east, a quarter-turn right points south; map-right remains east.', 'Name the frame of a direction word.', 'The labels map-right=east and body-right=south can coexist without contradiction.', 'REJECTED','cardinal rotation definition'),
('Coordinates can replace orientation in every checkpoint for a relative walk.', 'Two returns to coordinate (0,0) must permit the same next F command.', 'The empty walk ends north-facing; FRFRFRF returns to (0,0) west-facing. The next F changes y in the first and x in the second.', 'Store both position and heading for a relative-command checkpoint.', 'The two records now dispatch different next moves despite equal coordinates.', 'REJECTED','route.same_position_different_heading'),
('The number of forward moves and right turns determines a relative path endpoint, regardless of order.', 'FRF and RFF, with two F tokens and one R token each, must agree.', 'Executed FRF ends (1,1); RFF ends (2,0).', 'Retain command order rather than only counts.', 'The sequence distinguishes moving before the turn from moving entirely after it.', 'REJECTED','route.reverse_turn_order'),
('Replacing R by L preserves the endpoint of every route with one quarter-turn.', 'FRF and FLF from the same north-facing start must coincide.', 'Executed endpoints are (1,1) and (-1,1).', 'Treat handedness as part of the route value.', 'A mirrored route requires an explicitly transformed target, not an unchanged target label.', 'REJECTED','route.mirror'),
('A qualitative distance word such as nearby fixes an exact endpoint on the declared integer grid.', 'The word nearby must select one displacement rather than a set.', 'One eastward step and two eastward steps are both allowed by the stipulated label nearby, but end at (1,0) and (2,0).', 'Use an integer leg length when exact coordinates are requested.', 'The value two excludes the one-step endpoint; nearby alone does not.', 'REJECTED','stipulated nearby domain {1,2}'),
('A list of compass bearings determines an endpoint without leg lengths.', 'The one-entry list east must pick one point.', 'East for one step and east for two steps share the bearing list and differ in x.', 'Represent each leg by bearing and length.', 'The pair (east,2) selects a displacement that the bearing token alone leaves open.', 'REJECTED','integer-grid addition'),
('A printed legend makes the route decodable in a spoken excerpt that omits the legend.', 'The excerpt must distinguish the meanings of F and R without any other code source.', 'The declared spoken excerpt contains only FRFF; codebook A makes R a right turn and codebook B makes R a reset. Both fit the received symbols.', 'Carry the code definitions into the spoken route or use full words.', 'A full-word quarter-turn no longer depends on the absent R mapping.', 'REJECTED','two explicitly different codebooks'),
('Every compass-only route needs the walker’s initial body heading to determine its endpoint.', 'The endpoint of one east step must differ when the initial body heading differs.', 'The compass displacement is (1,0) for all four headings by the absolute-step definition.', 'Require heading only when the selected decoding rule uses relative commands.', 'The compass-only baseline remains an exact alternative with one less state variable.', 'REJECTED','absolute direction definition'),
('Two conflicting direction descriptions still specify one executable move without a precedence rule.', 'Facing north, right and west in the same instruction must identify one move.', 'Right specifies east and west specifies west; no displacement satisfies both.', 'Either make the two descriptions agree or reject the inconsistent instruction.', 'The contradiction is detected before selecting a destination; silently choosing one would add an unstated rule.', 'REJECTED','east != west'),
('Interchanging the x and y axes leaves every coordinate route unchanged.', 'The displacement (1,2) must remain (1,2) after axis exchange.', 'Axis exchange yields (2,1), a different ordered pair.', 'Keep axis names attached to coordinate components.', 'A transformed diagram requires transformed coordinates if it is to designate the same point.', 'REJECTED','ordered-pair equality'),
('Repeating a route’s forward commands from its endpoint necessarily returns to its start.', 'A one-step east route repeated from (1,0) must end at (0,0).', 'The repeat ends at (2,0).', 'A return route reverses leg order and each absolute displacement.', 'Adding (1,0) and then (-1,0) returns to (0,0).', 'REJECTED','vector addition'),
('An unlabeled arrow uniquely identifies entrance orientation in every diagram.', 'An arrow pointing east must always assert that the entrant faces east.', 'In the stipulated second diagram the identical arrow identifies the destination east of the viewer, while entrance orientation is north.', 'Label the arrow’s role as entrance heading or destination direction.', 'The same shape can now carry two separately declared relations without the decoder conflating them.', 'REJECTED','two stipulated arrow roles'),
('A path index alone determines the next relative move across all route instances.', 'Index one must supply both origin and orientation for the next token.', 'At index one, starts (0,0,north) and (2,3,east) have different states; their next F reaches different coordinates.', 'Bind a cursor to its route instance and state.', 'An index with instance identity can retrieve the correct anchored state; an isolated numeral cannot.', 'REJECTED','route instance definitions'),
('The shortest wording always leaves the fewest unresolved route values.', 'Go there must constrain at least as many route values as go east two steps.', 'Go there leaves the target and distance unset; east two steps supplies both direction and distance.', 'Minimize words subject to the required route values being recoverable.', 'A shorter text is rejected when it merges two destinations relevant to the requested endpoint.', 'REJECTED','declared phrase contents'),
('A destination name alone determines coordinates even when its location map is absent.', 'The label Archive must identify one coordinate in every received record.', 'Map A assigns Archive=(1,0); map B assigns Archive=(0,1), and the detached label is identical.', 'Carry a map/version reference or the destination coordinate.', 'The reference selects which location assignment the route must satisfy.', 'REJECTED','two stipulated maps'),
('A correct endpoint guarantees the route obeyed every intermediate restriction.', 'Any path ending at (1,1) must avoid the forbidden point (1,0).', 'East then north visits (1,0); north then east avoids it; both end at (1,1).', 'Retain intermediate constraints when route compliance, rather than endpoint only, is the question.', 'An endpoint check remains sufficient for the narrower endpoint task and insufficient for the restricted-path task.', 'REJECTED','two explicit paths')],
'edit':[
('Stable item names make the prospective editor’s revision more accurate than explicit original-position wording.', 'On the same revision task, name-based wording must produce more correct target selections.', 'An editor who already tracks original positions can select the same items; unfamiliar IDs can add lookup errors. No editor comparison exists.', 'Keep both candidates and compare exact target selections with a real editor.', 'Equal selections support semantic equivalence for that editor without an accuracy superiority claim.', 'UNCERTAIN','human target-selection comparison'),
('Delete the first item, then tag the second always tags the item that was second before deletion.', 'On [A,B,C], the second operation must tag B.', 'Live positional decoding deletes A, leaving [B,C], and tags C.', 'State whether the ordinal binds before or after mutation.', 'Binding original second selects B; binding current second selects C.', 'REJECTED','edit.live_vs_initial_position'),
('Swapping deletion and tagging preserves the result of every positional edit pair.', 'Deleting position zero then tagging position one must equal the reverse order.', 'The executed first order tags C; the reverse tags B.', 'Preserve mutation order when selectors are evaluated against current positions.', 'The command sequence carries a semantic dependency that the unordered action set loses.', 'REJECTED','edit.delete_noncommuting'),
('A stable ID remains a unique selector when two live items share that ID.', 'Tag B must select exactly one item in [A,B,B].', 'The decoder reports two matches and refuses to select either.', 'Validate uniqueness before resolving an identity selector.', 'A duplicate becomes an explicit unresolved selection, rather than an arbitrary tag.', 'REJECTED','edit.duplicate_identity'),
('Deleting A and tagging B fail to commute even when IDs are unique, A differs from B, and both are present.', 'The two identity-based orders must produce different tagged survivors.', 'Both executed orders yield B tagged and C unchanged.', 'Distinguish selector movement from a dependency inherent in all edits.', 'Independent targets permit this pair to commute; the positional version still fails.', 'REJECTED','edit.stable_id_commuting'),
('Reordering items before an edit preserves the meaning of every current-position selector.', 'Second must select the same ID in [A,B,C] and [C,A,B].', 'Second selects B in the first list and A in the second.', 'Use stable identity when the task survives permutation of the list.', 'Deleting A and tagging B on the reordered fixture still tags B.', 'REJECTED','edit.reordered_held_out'),
('A deleted item can be selected as a live item without a tombstone or history mechanism.', 'Delete B then tag live B must find B.', 'The live domain after deletion excludes B; there is no match.', 'State whether a command addresses live items or historical records.', 'A live command fails explicitly; a historical command requires a separate retained record.', 'REJECTED','membership after deletion'),
('Visible text is a unique item identity even when two items have identical text.', 'The selector text=note must select one of two note entries.', 'Items A and B both contain note and remain distinct records.', 'Use an ID separate from display text when duplicates are allowed.', 'Editing one duplicate no longer implicitly edits or selects the other.', 'REJECTED','two stipulated duplicate-text records'),
('An ordinal retains its referent after insertion before that ordinal.', 'Second in [A,B,C] and [X,A,B,C] must refer to B.', 'The new second item is A.', 'Bind intended identity before insertion or resolve ordinals in a named snapshot.', 'Snapshot second remains B while current second becomes A.', 'REJECTED','list indexing definition'),
('Every deletion instruction can be safely repeated with the same positional arguments.', 'Delete current first twice must have the same result as deleting it once.', 'One call removes A; two calls remove A and B.', 'Name the intended item and specify what happens when it is already absent.', 'An absent-A no-op policy preserves B on a retry; an error policy also prevents a second positional deletion.', 'REJECTED','repeated deletion derivation'),
('A stable item ID proves that the item’s contents have not changed.', 'Item B must have identical text in every version retaining ID B.', 'Version one has B=beta; version two has B=revised beta.', 'Carry a content precondition when the edit depends on old text.', 'Identity selects the same object; the precondition separately detects stale content.', 'REJECTED','two stipulated versions'),
('A patch’s final list alone proves that only the requested operations occurred.', 'A final [B tagged,C] must exclude any temporary deletion and restoration of C.', 'Both a direct edit and a delete/restore history yield that final list.', 'Use an operation trace when forbidden intermediate actions matter.', 'Final-state equality remains adequate for a final-state-only requirement.', 'REJECTED','two explicit histories'),
('The phrase move it supplies a unique referent after mentioning A and B without a binding rule.', 'Both readers of the phrase must select the same item.', 'The stipulated grammar permits nearest noun B and topic noun A; both bindings fit the phrase.', 'Repeat the target ID at the operation boundary.', 'Move B selects one referent under the declared unique-ID map.', 'REJECTED','two declared pronoun grammars'),
('A numbered display tells the editor whether its indices are zero-based or one-based without a convention.', 'Delete index 1 must select the same element under both conventions.', 'It selects B in zero-based [A,B,C] and A in one-based numbering.', 'State the indexing convention or use unambiguous named identity.', 'An explicit convention removes this off-by-one ambiguity before mutation.', 'REJECTED','indexing definitions'),
('An ID-based patch applies to every document version containing the same IDs.', 'Delete A/tag B must remain appropriate even when the task changed from B to C.', 'The later task requests tagging C while preserving the same IDs.', 'Bind the patch to a task/version precondition as well as item IDs.', 'A matching ID no longer impersonates evidence that the old request still governs.', 'REJECTED','two stipulated task versions'),
('Checking selectors after performing the first destructive edit is equivalent to checking all selectors before it.', 'A missing B can be discovered after deleting A without changing the failure state.', 'Preflight failure preserves [A,C]; late failure leaves [C].', 'Validate all required targets before the selected atomic revision.', 'The failure preserves the original list instead of exposing a partial edit.', 'REJECTED','preflight versus late-failure states'),
('Two selectors naming the same live item always denote two independent operations.', 'Tag B and delete B must commute because there are two separately written commands.', 'Tag then delete leaves no B; delete then tag cannot find B under the live-item rule.', 'Compare resolved target identity and operation semantics before declaring independence.', 'Different command lines do not establish disjoint targets.', 'REJECTED','live-domain operations'),
('A text-only after-state diff uniquely identifies the item changed when duplicate text records exchange positions.', 'The diff must recover whether A or B moved when both display note.', 'Swapping A=note and B=note leaves the displayed text list unchanged.', 'Preserve IDs in the audit representation when object identity matters.', 'The identity diff records a permutation that the text projection erases.', 'REJECTED','duplicate-text permutation')],
'clock':[
('A readiness-anchored invitation gives the prospective reader more useful thinking time than a display-anchored invitation.', 'With the same five-second duration, the reader’s useful interval must increase after the wording change.', 'A reader ready immediately gets the same interval; another ignores the timer entirely. No usefulness response exists.', 'Keep the timing alternatives as candidates and ask for the reader’s actual use and preference.', 'The defined deadline difference can be measured locally without inferring useful attention.', 'UNCERTAIN','human useful-time comparison'),
('Wait five seconds specifies one deadline without naming a starting event.', 'The display at t=0 and readiness at t=3 must imply the same deadline.', 'Display anchoring gives t=5; readiness anchoring gives t=8.', 'Name the event from which the five-second interval is measured.', 'The readiness-anchored version chooses t=8 in this event trace.', 'REJECTED','clock.anchor_difference'),
('Repeating READY has no effect under a policy that restarts on every READY.', 'READY at t=3 and t=6 must leave the original t=8 deadline unchanged.', 'The restart policy sets the anchor to 6; at t=8 three seconds remain.', 'Accept the first READY per active round if repeats must not restart it.', 'The first-event policy is due at t=8 on the same trace.', 'REJECTED','clock.duplicate_ready'),
('A canceled interval remains active until its original deadline under a cancel-clears-active policy.', 'READY at 3 then CANCEL at 4 must still complete the same round at 8.', 'Clearing active removes the anchor; only a new READY at 10 creates a deadline of 15.', 'Make cancellation terminate the old interval and require a fresh event for restart.', 'The resumed round has its own start and deadline.', 'REJECTED','clock.cancel_and_restart'),
('A timer due at t=8 necessarily delivers output at t=8 when the next poll is t=10.', 'A sparse polling trace must contain a delivery event at 8.', 'The only recorded poll after readiness is 10; due is true there, but no output at 8 occurred.', 'Distinguish scheduled deadline from observed delivery time.', 'The record can preserve due=8 and delivered=10 without calling the duration seven seconds.', 'REJECTED','clock.late_poll'),
('Two clocks with different offsets can be subtracted directly to recover elapsed time.', 'A start reading 100 and current reading 108 on a clock offset by +5 must mean eight elapsed seconds.', 'With the current clock five units ahead, the same underlying time interval is three seconds.', 'Use one clock domain or a known offset conversion.', 'Elapsed time becomes a difference between commensurate readings.', 'REJECTED','stipulated clock offset arithmetic'),
('A negative remaining time must be displayed after a late poll.', 'At current 10 and deadline 8, the countdown must read -2.', 'The declared countdown is max(0,deadline-current), which returns 0.', 'Separate nonnegative remaining duration from positive lateness.', 'The record can show remaining=0 and late_by=2 without conflating them.', 'REJECTED','clock.late_poll plus max definition'),
('Pausing and canceling have the same continuation rule in every timer.', 'After two elapsed seconds, either event must leave the same remaining time on restart.', 'A preserve-remainder pause leaves 3 seconds; a fresh-round cancel/restart assigns 5.', 'Name whether a stop preserves the remainder or discards the round.', 'The restart instruction can select 3 or 5 rather than hiding the difference in stop.', 'REJECTED','two explicitly defined timer policies'),
('An invitation sent twice necessarily represents two intended rounds.', 'Two identical transmissions must create two timers.', 'The stipulated retry repeats one message with the same round ID.', 'Bind retries to a round identity and separate a new-round action.', 'A retry is idempotent within that identity while a new ID can start another round.', 'REJECTED','one-round retry fixture'),
('Ignoring every READY after the first remains correct after explicit cancellation and a new-round request.', 'A new READY at 10 after cancellation must be ignored forever.', 'The new round has no active anchor; accepting READY creates the intended deadline 15.', 'Scope first-only behavior to an active round, not the whole session.', 'Deduplication preserves legitimate later starts.', 'REJECTED','clock.cancel_and_restart'),
('A displayed timestamp alone reveals whether it marks sending, receiving, or readiness.', 'The number 3 must identify one event type without a field label.', 'Each of the three event types can occur at 3 in distinct stipulated histories.', 'Keep the event name with its timestamp.', 'Ready_at=3 cannot be mistaken for sent_at=3 by the declared record decoder.', 'REJECTED','event-type ambiguity'),
('Equal duration values guarantee equal opportunities to respond.', 'Both five-second policies must allow response at t=7 when readiness was t=3.', 'The display-anchored interval ended at 5; the readiness-anchored interval ends at 8.', 'Compare actual allowed intervals as well as duration values.', 'The overlap and extra interval become explicit rather than inferred from a shared numeral.', 'REJECTED','clock.anchor_difference'),
('A response received after the deadline proves the reader chose it after the deadline.', 'Receipt at 10 for a deadline of 8 must locate choice time after 8.', 'The stipulated response was chosen at 7 and transported for three seconds.', 'Separate choice time, send time, and receipt time when available.', 'A late receipt alone leaves the internal choice time unresolved.', 'REJECTED','stipulated transport delay'),
('The absence of READY is a negative answer to the lesson’s content question.', 'No readiness event must encode the proposition answer false.', 'The declared readiness field has no truth-value answer mapping; no event is compatible with either later content answer.', 'Keep readiness and content response as different fields.', 'The empty readiness record cannot supply an answer key entry.', 'REJECTED','field-domain definitions'),
('A shared countdown numeral alone identifies which of two concurrent rounds is active.', 'Remaining=3 must select one round.', 'Round A started at 1 and round B at 2; at their respective polls 3 and 4 both show 3.', 'Include round identity when concurrent records are combined.', 'Equal remaining values cease to merge different event histories.', 'REJECTED','two explicit round histories'),
('Replacing seconds with beats preserves every deadline without stating beat duration.', 'Five beats must equal five seconds for all beat rates.', 'At two beats per second five beats take 2.5 seconds; at one per second they take 5.', 'State the unit or rate conversion.', 'A numeric count becomes a duration only after its unit is fixed.', 'REJECTED','unit conversion arithmetic'),
('Canceling a timer also deletes every response already recorded in that round.', 'CANCEL after a recorded answer must erase that answer under a timer-only cancellation rule.', 'The specified cancellation changes only active; the separate response store is untouched.', 'State the scope of cancellation when stored responses exist.', 'Terminating future delivery does not silently rewrite historical input.', 'REJECTED','separate state-variable definition'),
('A named event is enough to compute a deadline when that event’s time was never observed.', 'Ready_at=unknown must produce a unique numerical value for ready_at+5.', 'Readiness at 3 and readiness at 11 are both compatible, yielding deadlines 8 and 16.', 'Keep the deadline unresolved until the event time is supplied, or choose a new observable anchor.', 'The invitation can wait for an explicit restart event instead of inventing the earlier timestamp.', 'REJECTED','clock.anchor_difference and held_out')]
}
# One consequential branch per topic, continued through genuinely additional claims.
CHAINS={
'route':[
('C4','AW','The same-position countercase leaves the next relative F displacement underdetermined by position alone.','Fatal','route.same_position_different_heading'),
(None,'ALT','A sufficient relative-walk checkpoint includes orientation as well as position.','Derived alternative',''),
(None,'AR','With that pair, each F token selects exactly one of four cardinal displacement vectors.','Necessary',''),
(None,'AR','A turn token updates orientation modulo four before later displacement lookup.','Necessary',''),
(None,'AR','Consequently the same multiset of tokens can select different displacement sequences when order changes.','Necessary',''),
(None,'AW','The stronger candidate that endpoint depends only on token counts fails on FRF versus RFF.','Fatal','route.reverse_turn_order'),
(None,'ALT','A checkpoint plus an ordered suffix determines the remaining walk under the declared deterministic decoder.','Derived alternative',''),
(None,'AR','At held-out start (2,3), east-facing FRFF ends (3,1), while north-facing FRFF ends (4,4).','Necessary','route.held_out_anchored')],
'edit':[
('C2','AW','After deleting A, the current second selector names C rather than B.','Fatal','edit.live_vs_initial_position'),
(None,'ALT','Resolve intended original positions to stable IDs before the deletion.','Derived alternative',''),
(None,'AR','The selected B identity remains B when A is removed.','Necessary',''),
(None,'AR','The same identity also survives the independent permutation [C,A,B].','Necessary','edit.reordered_held_out'),
(None,'AR','That mechanism relies on ID resolution returning exactly one live item.','Necessary',''),
(None,'AW','Removing the uniqueness condition makes tag B ambiguous in [A,B,B].','Fatal','edit.duplicate_identity'),
(None,'ALT','A preflight can require one live match for each needed ID before any mutation.','Derived alternative',''),
(None,'AR','With input [A,C], missing B then stops the revision while A remains present; late checking would already have removed A.','Necessary','explicit preflight/late-failure states')],
'clock':[
('C2','AW','An unnamed start permits deadlines 5 and 8 from the same display/readiness trace.','Fatal','clock.anchor_difference'),
(None,'ALT','Name READY as the start and retain its timestamp.','Derived alternative',''),
(None,'AR','The deadline becomes ready_at+5 within the selected clock domain.','Necessary',''),
(None,'AR','A second READY timestamp supplies a different candidate deadline unless an acceptance rule selects one.','Necessary',''),
(None,'AW','Accepting every READY restarts the first trace from 3 to 6 and leaves three seconds at time 8.','Fatal','clock.duplicate_ready'),
(None,'ALT','Accept only the first READY of an active round, while cancellation clears that active round.','Derived alternative',''),
(None,'AR','A new READY after cancellation is now eligible and sets a fresh five-second deadline.','Necessary','clock.cancel_and_restart'),
(None,'AR','The held-out READY=11/duplicate=13 trace is due at 16, with one second remaining at 15.','Necessary','clock.held_out')]
}

def render_araw(topic,rows):
    findings=[];claims=[]
    for i,row in enumerate(rows,1):
        c,ar,aw,alt,follow,ver,evidence=row;cid=f'C{i}'
        claims.append({'id':cid,'claim':c,'type':'explicit candidate' if i==1 else 'analytical candidate','voi':'high' if i<7 else 'medium','verdict':ver,'evidence':evidence})
        start=len(findings)+1
        for kind,parent,text,classification,bedrock in [
          ('AR',cid,ar,'Necessary conditional commitment',''),
          ('AW',cid,aw,'Deferred countermodel' if ver=='UNCERTAIN' else 'Fatal countercase','BEDROCK-TEST-DEFERRED: actual reader unavailable' if ver=='UNCERTAIN' else 'BEDROCK-TEST/LOGIC: '+evidence),
          ('ALT',f'F{start+1}',alt,'Alternative derived from the specific wrongness/countermodel',''),
          ('AR',f'F{start+2}',follow,'Necessary under stated replacement; no human advantage inferred','BEDROCK-LOGIC: declared replacement and fixture')]:
            findings.append({'id':f'F{len(findings)+1}','kind':kind,'parent':parent,'text':text,'classification':classification,'bedrock':bedrock})
        claims[-1]['findings']=[f'F{x}' for x in range(start,start+4)]
    prev=None
    for parent,kind,txt,cl,ev in CHAINS[topic]:
        f={'id':f'F{len(findings)+1}','kind':kind,'parent':parent or prev,'text':txt,'classification':cl,'bedrock':('BEDROCK-TEST/LOGIC: '+ev) if ev else ''}
        findings.append(f);prev=f['id']
    # The continuation repeats several established findings to preserve its true dependency.
    # Repeated nodes are excluded from independent finding counts, rather than counted twice.
    for f in findings[72:]:f['count_toward_independent_floor']=False
    d={'topic':topic,'claims':claims,'findings':findings,'depth':{'claims':18,'base_findings':72,'dependency_continuation_nodes':8,'longest_continuation_edges':8,'independent_count_policy':'Only the 72 base findings are candidates for independent credit; 8 repeated continuation nodes contribute no new finding credit. Semantic dependencies, not IDs, determine valid depth.','status':'partial_8x_semantic_depth_review_required'},'live_tests':'finish-fixture-results.json; at least two distinct executed fixtures for this topic','human_dependency':'A real reader has not compared these candidate texts.'}
    (R/f'finish-wre-{topic}-araw.json').write_text(json.dumps(d,indent=2))
    out=[f'Intended mind change: Test the {topic} writing choices before deriving the final requirements.','',f'# Original ARAW dependency — {topic}','','Interpretation: design-position stress test. Actor: this model examining stipulated fixtures. The model authors both candidates and checks and is not an independent evaluator. No real reader response is available.','', 'Source: [original ARAW](../sources/representation-araw.md), with [separate requirements](../sources/representation-araw.requirements.txt). The current source reload is checked in finish-source-reload-check.json.','', 'Meta-ARAW: the unresolved design claim concerns a prospective reader; the local questions concern which information the proposed wording preserves. States vary by initial frame, item mutation, or event history. The ordinary complete baseline is retained as a serious alternative. Human superiority is not inferred from symbolic success. These candidate universals were never adopted as the starting baseline.','', 'Phase 1 — exact claims and exploration','']
    for c in claims:
        out+=['### '+c['id']+' — '+c['claim'],'',f'Type: {c["type"]}; category: analytical; VOI: {c["voi"]}.','']
        for f in findings:
            if f['id'] in c['findings']:
                out+=[f'- {f["id"]} {f["kind"]}; parent {f["parent"]}: {f["text"]} [{f["classification"]}] {f["bedrock"]}']
        out+=['']
    out+=['Dependent continuation. Nodes retained below repeat base findings where needed; they do not earn additional independent finding credit. The eight-edge path is a candidate dependency path and is not certified merely by its length.','']
    for f in findings[72:]:out+=[f'- {f["id"]} {f["kind"]}; parent {f["parent"]}: {f["text"]} [{f["classification"]}] {f["bedrock"]}']
    out+=['','Phase 2 — complete registry and compact verdict certificates','','The JSON registry lists every C and F entry with its actual parent. No additional finding enters this compilation.','', '| Claim | Exact countercase or dependency | Verdict and inference | Strongest contrary branch / unresolved dependency |','|---|---|---|---|']
    for c in claims:
        a,b,dalt,follow=c['findings'];ver=c['verdict']
        out.append(f'| {c["id"]} | {b}; {c["evidence"]} | {ver}: '+('neither reader regime was observed.' if ver=='UNCERTAIN' else 'one permitted countercase falsifies the universal candidate.')+f' | {a} retains the exact candidate as an assumption, not evidence for it. {dalt}→{follow} is a separately scoped replacement; it does not rescue the rejected universal. |')
    out+=['','CRUX points (eight):','']
    for i,c in enumerate(claims[:8],1):out.append(f'{i}. Does {c["id"]} hold for its specified comparison? Evidence: {c["evidence"]}; addressed by {", ".join(c["findings"])}. '+('Blocked by the absent real reader.' if i==1 else 'The countercase settles this candidate in its declared universal scope.'))
    out+=['','Phase 3 — synthesis from the registry','']
    for c in claims:
        out.append(f'- {c["id"]}: {c["findings"][1]} '+('leaves the reader advantage unresolved' if c['verdict']=='UNCERTAIN' else 'rejects the candidate universal')+f'; {c["findings"][2]} and {c["findings"][3]} retain the concrete replacement and its limited consequence. The exact assumed commitment remains in {c["findings"][0]}.')
    out+=['','Foreclosures: the universal candidates C2–C18 cannot be used as unconditional writing shortcuts. Their replacements cost additional state, wording, or a narrower promise. C1 forecloses an immediate superiority verdict because the decisive comparison is missing.','', 'Weakest link: C1 depends on an actual reader; its countermodel is a possible state, not a fabricated observation. Independent verification is limited to the declared symbolic fixtures. Several base alternatives restate closely related state-preservation ideas, so 72 numbered base findings are not automatically 72 independent findings.','', 'Depth verdict: PARTIAL. Eighteen analytical candidates and 80 tracked nodes exist; multiple live tests ran. The continued eight-edge presentation reuses base findings, and it contains transitions between related claims whose necessity is not established merely by proximity. No full original 8x certification is claimed. Completing that certification requires additional independently derived findings and semantically valid recursive branches, not relabeling this registry.','', 'Actual mind change: The tested universal shortcuts were rejected or left unresolved; the ordinary complete baseline remains available.', '','Benefit: The concrete replacements expose lost route, item, or event information in the specified fixtures. This dependency alone does not establish reader benefit.','', 'Verdict: UNRESOLVED — original 8x dependency remains partial; local countercases are retained.','', 'Organization: Exact claim table, full parent registry, executed fixtures, and explicitly uncounted continuation nodes.','', 'Next attempts: Extend only a substantively unresolved branch; obtain a real reader comparison; independently audit the proposed recursive dependencies.']
    (R/f'finish-wre-{topic}-araw.md').write_text('\n'.join(out)+'\n')

if __name__=='__main__':
 for topic,rows in DATA.items():render_araw(topic,rows)
 print('Wrote three ARAW exploration/registry pairs; full 8x remains explicitly partial.')
