from write_record import record, progress, ROOT
from itertools import product
import json

def box_run(n,run,title,problem,baseline,dimensions,constraints,interactions,prototypes,conclusion,verdict):
    ids=list(dimensions)
    assert len(ids)==6 and all(len(dimensions[d])==6 for d in ids)
    total=sum(1 for _ in product(range(6),repeat=6))
    # A systematic 6x6 slice: every declared value occurs; this is not full pairwise coverage.
    combos=[]
    for i in range(6):
      for j in range(6):
        idx=[i,j,(i+j)%6,(i+2*j)%6,(2*i+j)%6,(i+3*j)%6]
        val={d:dimensions[d][idx[k]] for k,d in enumerate(ids)}
        fails=[why for pred,why in constraints if pred(val)]
        # Defined specimen metrics, not estimated human value: fields preserved and construction parts.
        coverage=sum('scope' in str(x).lower() or 'condition' in str(x).lower() or 'boundary' in str(x).lower() or 'exact' in str(x).lower() for x in val.values())
        novelty=sum(x!=0 for x in idx)
        cost=len(' | '.join(val.values()).split())
        combos.append({'id':len(combos)+1,'indices':idx,'values':val,'feasible':'no for target' if fails else 'design constructible','value_basis':'; '.join(fails) if fails else 'No declared incompatibility; comparative benefit requires prototype test','scope_fields':coverage,'novelty_vs_first_values':novelty,'spec_words':cost})
    assert len({tuple(c['indices']) for c in combos})==36
    dimension_table='\n'.join('| '+d+' | '+' | '.join(dimensions[d])+' |' for d in ids)
    sample='\n'.join('| '+str(c['id'])+' | '+','.join(str(x+1) for x in c['indices'])+' | '+c['feasible']+' | '+str(c['scope_fields'])+' | '+str(c['novelty_vs_first_values'])+' | '+str(c['spec_words'])+' | '+c['value_basis']+' |' for c in combos)
    appendix=f'''Intended mind change: Inspect systematically generated candidate arrangements for {problem}\n\n# Morphological sample {run}\n\nThe six digits in each row select options 1–6 from the six dimensions in the application’s box, in row order. All 46,656 combinations were mechanically enumerated for the count; the 36 distinct combinations below are the explicitly evaluated systematic slice. Every value appears in the sample. Pairwise exhaustiveness is not claimed.\n\nFeasible means a written design can be constructed under the declared target constraints, not that human benefit is established. Scope-field count is a transparent text/specification proxy, not benefit. Novelty is the number of changed dimensions relative to the six first values; it is not a reason to adopt. Cost is words in the six selected specification labels, excluding eventual content. The final choice depends on the actual prototype tests in the parent application, not on maximizing these proxies.\n\n| ID | Six option indices | Feasibility | Scope fields | Novelty dimensions | Spec words | Target-value assessment |\n|---|---|---|---:|---:|---:|---|\n{sample}\n\nActual mind change: The 36 candidate specifications have explicit compatibility and burden observations; no outcome claim is imported from the enumeration.\nBenefit: Candidate coverage is inspectable; comparative benefit is evaluated in the application.\nVerdict: {verdict.split(' — ')[0]} — inherits the parent application’s scoped conclusion; no independent keep credit.\nOrganization: Compact six-index rows point to the full box and actual prototypes.\nNext attempts: Change one declared constraint; sample a different slice; test the nearest rejected combination after repairing its incompatibility.\n'''
    (ROOT/f'ma-{run}-combinations.md').write_text(appendix)
    (ROOT/f'ma-{run}-combinations.json').write_text(json.dumps({'dimensions':dimensions,'total_combinations':total,'sampling':'i,j,i+j,i+2j,2i+j,i+3j mod 6','evaluations':combos},indent=2))
    body=f'''Problem: {problem} Interpretation: structured comparison and generation of unexplored configurations.\n\nThe dimensions are separately choosable design parameters. Some pairs conflict under this target; those interactions are filtered rather than hidden inside a dimension. Values are a bounded design vocabulary, not an exhaustive inventory of every possible representation.\n\n| Dimension | 1 | 2 | 3 | 4 | 5 | 6 |\n|---|---|---|---|---|---|---|\n{dimension_table}\n\nCombination count: 6^6 = {total:,}. The source permits systematic sampling above 1,000. All combinations were enumerated to verify the count, and the 36-case slice is retained in [the full evaluated sample](ma-{run}-combinations.md) and its exact [data](ma-{run}-combinations.json). Constraints and evaluations precede the shortlist. No hidden score is described as measured value.\n\nCross-dimension interactions:\n\n{interactions}\n\nShortlist, constructed outputs, and transfer tests:\n\n{prototypes}\n\n{conclusion}'''
    record(n,'ma',run,title,problem,baseline,body,
           'I generated and evaluated the full stated 36-configuration sample, constructed three materially different shortlisted representations, and changed the candidate disposition as shown in the prototype comparison.',
           'The actual design and finite tests are recorded; model construction effort, semantic preservation, and untested human outcomes remain separate. The verdict concerns the incremental effect relative to the strong ordinary baseline.',
           verdict,
           f'The six-dimensional box and exact 36 rows remain accessible, while only the tested shortlist is an entry surface. Enumeration does not earn keep credit by itself.',
           'Test a nearby excluded combination after a single repair; change the target constraint and rerank; compare the winning prototype with the ordinary baseline on a genuinely new input.',
           'Original 8x floors met: six dimensions, six options each, 36 distinct combinations evaluated, six explicit cross-dimension interactions, constraint filtering, four evaluation aspects, and three diverse shortlist prototypes. 46,656 is the space size, not a claim that every combination received a substantive evaluation.')

box_run(20,1,'The morphological box does not beat a direct counterexample here',
'Find a representation that lets the current model distinguish “not every” from “every not” on a declared finite domain.',
'The strong baseline is the exact plain-language distinction plus the mixed vector `[1,0]` and empty-domain caveat from 012. The goal is incremental access, not merely a new-looking display.',
{
'Encoding':['plain clause','numeric vector','case list','predicate notation','truth table','set membership'],
'Entry':['exact proposition first','concrete case first','question first','counterexample first','scope boundary first','definition first'],
'Case family':['two mixed outcomes','three mixed outcomes','all improve','none improve','one unknown outcome','empty domain'],
'Support':['scope legend','full condition map','minimal counterexample','source pointer','paired completions','boundary note'],
'Layout':['one paragraph','serial cards','side-by-side columns','row table','question and answer','appendix expansion'],
'Use':['immediate classification','later retrieval','new vocabulary transfer','source audit','spoken reading design','scope exception audit']
},
[(lambda v:v['Case family']=='one unknown outcome' and v['Support'] not in ['paired completions','full condition map','scope legend'],'Unknown outcome needs a legend/completion account for this target'),(lambda v:v['Case family']=='empty domain' and v['Support'] not in ['boundary note','full condition map','scope legend'],'Empty domain needs explicit universal convention'),(lambda v:v['Use']=='spoken reading design' and v['Layout']=='side-by-side columns','Written side-by-side layout lacks a specified serial route')],
'''1. Unknown outcome × numeric vector requires a distinct unknown symbol; otherwise a missing observation can become zero.\n2. Empty domain × ordinary “all” wording needs a convention; everyday presupposition does not settle formal truth.\n3. Spoken design × side-by-side columns requires serialization; two-dimensional location alone is insufficient.\n4. Source audit × counterexample-first entry keeps the source link but makes it a second destination; appropriate for use, weaker for audit.\n5. All-improve case × minimal-counterexample support conflicts unless a second case is added; an all-true vector cannot itself separate the negations.\n6. New-vocabulary transfer × fixed familiar labels requires replacing the predicate while retaining its formal scope; surface novelty alone does not test transfer.''',
'''A. Plain case: “Two operations ran. One improved the result; the other did not. At least one did not improve, but they did not both fail to improve.” Test `[1,0]`: correct distinction; four clauses bind the members explicitly.\n\nB. Predicate table: `not(all p)` is true and `all(not p)` false on `[1,0]`; on `[]` they are false and true respectively. This carries the empty-domain case more directly, but requires predicate literacy.\n\nC. Serial question: “Did every operation improve? No. Did every operation fail to improve? No. Which observation answers both? One improvement and one non-improvement.” This makes the two questions explicit but uses more text than the baseline.\n\nAll three were applied to `[0,0]`, `[1,1]`, and `[1,0]`; the truth pairs are `(true,true)`, `(false,false)`, `(true,false)`. Each preserves the tested mapping. No prototype adds an inference or access capability demonstrated absent from the baseline for the current model.''',
'''Certificate: exact claim—the morphological expansion produces additional useful local access over the direct counterexample—is not demonstrated. The direct baseline answers all three tests and the empty-domain exception with less constructed machinery. Strong contrary—a different intended reader may benefit from the serial question or table; no such reader evidence is present. The representation candidates remain viable, but the current incremental-benefit claim is rejected.''',
'REJECT — incremental value of this morphological expansion for the already-solved scope task.')
box_run(21,2,'A veto cue that survives a compact comparison',
'Construct a compact comparison of six proposed changes that keeps a disqualifying condition visible when only one line per option is retained.',
'The strong baseline is a six-row option table with benefits and limitations in separate columns. It supports detailed comparison, but a one-line extraction of option names and benefits can omit the limitation column.',
{
'Primary grouping':['change locus','reader task','time horizon','actor','evidence state','constraint type'],
'First field':['expected benefit','disqualifying condition','performed result','option name','required action','scope boundary'],
'Cue style':['plain text label','bold label','symbol plus exact words','question','conditional clause','numbered trigger'],
'Detail location':['same line','next sentence','linked expansion','table column','footnote','appendix'],
'Comparison order':['benefit descending','constraint first','prerequisite first','least burden first','reversibility first','user-request order'],
'Exit route':['default plus alternatives','single chosen option','unresolved trade-off','request one missing fact','bounded trial','retain current state']
},
[(lambda v:v['Detail location'] in ['footnote','appendix','linked expansion'] and v['First field'] not in ['disqualifying condition','scope boundary'],'A one-line excerpt would omit the disqualifying condition'),(lambda v:v['Cue style']=='symbol plus exact words' and v['Detail location']=='table column','Exact words must remain in excerpt, not only another column')],
'''1. One-line extraction × footnote limitations loses the condition unless the first field already carries it.\n2. Benefit-descending order × disqualifying first field separates a veto from a low score: an inapplicable option is excluded rather than merely ranked lower.\n3. Actor grouping × required action identifies who must do the next step; the label does not establish consent or performance.\n4. Symbol cue × exact words can survive plain text; symbol alone cannot distinguish unknown from rejected reliably without its legend.\n5. Unresolved trade-off × single chosen option cannot both be the sole exit; they are distinct exit states, not coequal decorations.\n6. Least-burden order × prerequisite-first order can conflict; a necessary input stays before its dependent operation even when costly.''',
'''A. Constraint-first line: “Needs a human participant: listening trial — proposed access benefit, untested.” The excerpt retains the disqualifier for a model-only execution count.\n\nB. Conditional clause: “If a reader needs serial access, use the three-clause card; its human effect is untested.” The excerpt retains both trigger and scope; it does not require a technique menu.\n\nC. Result-first line: “On three local retrieval cases, the serial card preserved the rule; transfer to a listener is unresolved.” The exact observed scope precedes the candidate transfer.\n\nTests on six options: rephrase a quantifier, use a serial card, insert a pause, offer a method menu, construct a counterexample, retain the present answer. The limitation survives the one-line versions of all six when carried on the same line. A benefit-only extraction of the baseline omits at least the listener dependency and the menu’s user-choice condition. The revised compact comparison is now used: the listening trial is excluded from immediate model actions; the current counterexample remains the selected executable contribution.''',
'''Certificate: claim—putting the option-specific veto/trigger on the same retained line preserves it under the declared one-line extraction—is supported by the actual six extracted lines. Strong contrary—the full original table already preserves conditions and may be better for comparison; retained for full review. This result extends the scoped-verdict excerpt finding to option selection, but the distinct useful operation is a veto-based choice among concrete changes. Human attention benefits are untested.''',
'KEEP — option-specific condition preserved and used in compact selection.')
box_run(22,3,'A proposed reminder design remains a human hypothesis',
'Construct several feasible ways a person could encounter a prior distinction again without assuming that a saved note will be remembered.',
'The available starting approach is a reusable note with a descriptive title. It is a strong ordinary reference. Whether a person needs a cue, a reminder, or no further encounter is not observed.',
{
'Trigger':['next similar task','chosen calendar time','visible desk object','conversation question','error recurrence','voluntary search'],
'Medium':['short text','spoken script','diagram','printed card','interactive prompt','paired example'],
'Content':['exact distinction','minimal counterexample','scope boundary','own prior report','new transfer case','open question'],
'Pace':['one encounter','self-paced review','optional pause','three spaced encounters','on-demand only','stop after recognition'],
'Choice':['default with decline','two meaningful options','free selection','private response','public discussion','no response requested'],
'Evaluation':['reported experience','classification task','later conduct','retrieval observation','no measurement','criterion revision']
},
[(lambda v:v['Trigger']=='chosen calendar time' and v['Pace']=='on-demand only','A scheduled trigger is incompatible with strictly on-demand-only delivery'),(lambda v:v['Choice']=='no response requested' and v['Evaluation'] in ['reported experience','classification task'],'This outcome collection requires a response; revise the evaluation or preserve no-response choice'),(lambda v:v['Medium']=='spoken script' and v['Content']=='diagram','A diagram needs a serial description before a spoken-only encounter')],
'''1. Calendar trigger × repeated encounters requires a real scheduling mechanism; a written agenda is not scheduling.\n2. No-response choice × classification measure conflicts unless the task becomes optional and missing responses remain unmeasured.\n3. Public discussion × own prior report changes disclosure conditions; it cannot be assumed equivalent to private reflection.\n4. On-demand trigger × retrieval evaluation selects people who already searched, so it cannot by itself show improved spontaneous recall.\n5. Diagram × spoken medium needs an explicit verbal mapping, not merely a different file extension.\n6. Criterion revision × later-conduct evaluation requires preserving both old and new criteria; otherwise a changed judgment can masquerade as changed behavior.''',
'''A. Task cue: “When the next statement says ‘every’, try one mixed case. Keep the original scope beside the result.” Medium: text; choice: default with decline; evaluation: optional classification.\n\nB. Private card: “Did this reminder change your question, your distinction, your action, or nothing you want to report?” Medium: print-ready plain text; pace: on demand; evaluation: attributed self-report only.\n\nC. Paired example: `[1,0]` and `[1,?]`, with the exact question “Which refutes every?” Medium: paired example with legend; pace: one voluntary encounter; evaluation: task response.\n\nLocal tests show that A has a cue, B permits non-disclosure, and C distinguishes unknown from false. The candidates were compared with the ordinary titled note: the note is simpler and user-initiated; the new candidates add a trigger, a response route, or a discrimination demand. No person encountered any of them, no automation was created, and no later conduct was observed.''',
'''Certificate: claim—one of these cue designs improves this person’s memory or benefit—is unresolved. The design properties and constraint filter are inspectable, but the relevant preference, encounter, and outcome are absent. Strong contrary—a well-titled reference may be all the person wants, so extra prompting can add burden. Keep the three candidates as distinct untested approaches, not established interventions.''',
'UNRESOLVED — human reminder and memory benefit.')
progress()
