from pathlib import Path
import json
B=Path('/workspace/scratch/78b838bd97fc/mind-change-research/values')

def araw(name,goal,rows,deep,crux,tests):
 findings=[];groups=[]
 def f(parent,kind,text,bedrock='BEDROCK-LOGIC within the constructed or definitional scope'):
  z={'id':f'F{len(findings)+1}','parent':parent,'kind':kind,'text':text,'bedrock':bedrock};findings.append(z);return z['id']
 for i,(claim,ar,aw,alt,probe,verdict,certificate) in enumerate(rows,1):
  c=f'C{i}';r=f(c,'AR necessary conditional implication',ar);w=f(c,'AW concrete countercase',aw);a=f(w,'Derived alternative',alt,'Candidate tested by following finding');t=f(a,'AR of alternative and exact countercase disposition',probe)
  groups.append({'id':c,'claim':claim,'findings':[r,w,a,t],'verdict':verdict,'certificate':certificate})
 anchor=deep[0][0]
 for parent,kind,statement,bedrock in deep:
  if parent=='PREV':parent=findings[-1]['id']
  f(parent,kind,statement,bedrock)
 report={'name':name,'goal':goal,'claims':groups,'findings':findings,'cruxes':crux,'live_tests':tests}
 (B/(name+'.json')).write_text(json.dumps(report,indent=2))
 lines=[f'Intended mind change: Test the OPEN implementation claims for {goal} without changing the authorized goal.','',f'# {name}: original /araw 8x dependency','',
 'Source: ../sources/values-araw.md; receipt: ../sources/values-araw.receipt.txt. Exact original loaded through read_original.py. This is a separate invoked procedure, not counted as another allocated skill application.',
 '', 'Starting judgment: the supplied broad goal is accepted as the working premise; the means below are open hypotheses, not assertions attributed to the user. This assistant evaluates its own generated products, so favorable findings need concrete countercases and narrow scope. The analysis begins from the exact claims below; prior value/social records inform context but imported conclusions do not count as independent findings.',
 '', 'Meta-ARAW: evaluand is implementation sufficiency, not whether the user really wants the stated goal. Uncertainty includes missing human responses, incomplete value priorities, and causal attribution. State dimensions include actor, target, participation, permission, time, role and evidence. The uncomfortable alternative is that an apparently productive intervention can correctly be declined, or that a proposed success metric itself should be abandoned. These alternatives preserve the user’s broad goal rather than replace it.',
 '', '## Frozen OPEN claims', '']
 for g in groups:lines.append(f"{g['id']}. {g['claim']} — analytical; hypothesis; VOI high where it changes selected action, medium for reporting boundaries.")
 lines+=['','## Phase 1: exploration','']
 for g in groups:
  lines.append(f"### {g['id']}: {g['claim']}")
  for z in findings:
   if z['id'] in g['findings']:lines.append(f"{z['id']} — parent {z['parent']}; {z['kind']}. {z['text']} [{z['bedrock']}]")
  lines.append('')
 lines+=['### Recursive continuation of the first high-value branch','']
 for z in findings[4*len(rows):]:lines.append(f"{z['id']} — parent {z['parent']}; {z['kind']}. {z['text']} [{z['bedrock']}]")
 lines+=['','## Live applications performed','']
 for i,t in enumerate(tests,1):lines.append(f'Test {i}: {t}')
 lines+=['','## Phase 2: complete finding registry','']
 for z in findings:lines.append(f"{z['id']} | {z['kind']} | parent {z['parent']} | {z['text']} | {z['bedrock']}")
 lines+=['','### Verdict certificates','']
 for g in groups:lines.append(f"{g['id']} — {g['verdict']}. Exact claim: {g['claim']} Evidence: {', '.join(g['findings'])}. {g['certificate']}")
 lines+=['','### Cruxes','']
 for i,t in enumerate(crux,1):lines.append(f'CRUX-{i}: {t}')
 lines+=['',f"Counts: {len(groups)} claims; {len(findings)} separately numbered findings; {len(crux)} cruxes; {len(tests)} actual generated-input/output tests. The recursive continuation has {len(deep)-1} substantive linked edges from its stated root; its final compatible-boundary objection fails and contributes no further depth or alternative support. Terminal logical/case branches are not padded to this length. Constructed tests establish the stated mappings, not general human effects.",'','## Phase 3: synthesis from registry only','']
 for g in groups:lines.append(f"{g['id']} / {','.join(g['findings'])}: {g['verdict']} — {g['certificate']}")
 lines+=['','The deeper branch keeps its alternatives conditional on the tested information and permission state. Testable human effects remain BEDROCK-TEST-DEFERRED because no participants, responses, or longitudinal data are available. Do-first within this run is the revised classification shown in the two live applications; no external invitation or intervention is sent.',
 '', 'Actual mind change: The implementation claims now have distinct verdicts, derived from exact countercases and scoped tests; the authorized broad goal remains the premise.',
 '', 'Benefit: Two later classifications distinguish the available evidence from a broader motivational or social outcome claim.',
 '', 'Verdict: UNRESOLVED',
 '', 'Organization: The registry preserves all explored findings and exact parents. Source products are separate from these applications; no new finding enters synthesis. Live human dependencies remain explicit.',
 '', 'Next attempts: Supply a real discriminating response if available; test a new case that challenges a surviving scope; compare decisions under a genuinely different value priority.','']
 (B/(name+'.md')).write_text('\n'.join(lines))
 return report

R1=[
('Raising task-initiation frequency is sufficient for beneficial motivational change in every case in this inquiry.','If this is sufficient, an initiation increase alone settles benefit even when interest and agency are not observed.','Constructed actor starts ten tasks under an unwanted obligation but explicitly values fewer self-chosen inquiries; initiation rises while the accepted agency criterion worsens.','Motivational evaluation distinguishes initiation from voluntary interest and agency.','With those fields separate, the example is a trade-off rather than automatic benefit. A person who values imposed starts could differ, but that does not rescue the universal claim.','REJECTED','The concrete value conflict defeats sufficiency; the favorable quick-start case proves only a scoped benefit.'),
('An absent optional behavior establishes that the actor values it little.','Then one missed discussion would settle the actor’s low priority without checking opportunity.','The actor wants discussion but lacks the channel invitation; absence occurs with high stated interest.','Absence is evaluated together with opportunity and stated preferences.','The missing-channel case remains an access gap. Confirmed access plus explicit disinterest supports a different case-specific judgment.','REJECTED','Same absent behavior has different permitted causes; no intrinsic ranking follows alone.'),
('A detailed motivational plan establishes a human motivational improvement.','A completed plan would then count as the target human change before anyone undertakes it.','A plan sits unread and no human state changes; the document exists without the claimed outcome.','A plan establishes a proposed intervention; human improvement requires an actual outcome record.','A real later outcome can change the status; the unread plan cannot.','REJECTED','The unread-plan countercase is decisive; good design remains valuable but is not the claimed human effect.'),
('Unelicited personal intrinsic goals prevent all useful work on the supplied task.','Then no source reading, case comparison, or faithful local transformation can be useful before a person supplies terminal values.','The supplied task explicitly requires original-source execution; exact source loading is possible without knowing a personal ultimate reason.','Explicit task commitments can guide bounded work while personal intrinsic termini remain unknown.','The line can produce stipulated comparisons and keep human termini open. A decision depending on an unknown personal priority still waits or remains conditional.','REJECTED','A concrete authorized operation defeats the universal prohibition; the missing-priority exception remains.'),
('If two people value different outcomes, at least one of their factual beliefs is false.','A privacy/discoverability disagreement would require a false empirical claim on one side.','Both accept that publicity increases reach and still rank privacy and reach differently.','Value disagreement and factual disagreement are distinct evaluands.','The explicit acceptance-plus-priority sentence is classified as a value trade-off. A disputed reach estimate would add a factual disagreement without erasing it.','REJECTED','Different ordering does not imply a contradictory fact.'),
('Every beneficial mind change must end in an immediate external action.','A corrected interpretation with no external act could never count as beneficial within this task.','A generated consensus record removes a falsely included absent member; the correction improves an actual representation without an external intervention.','Beneficial local change can occur in inference or representation; external actions are one target class.','The record’s accuracy difference is observable in text. Human cooperation remains a separate unknown.','REJECTED','The current task includes these non-action targets; the scoped representational change defeats the universal.'),
('A reported emotion determines the action that should follow.','Embarrassment would select a response independently of the critique’s content or chosen values.','Two embarrassed writers face respectively a correct denominator objection and a baseless insult; the same feeling does not settle the same response.','Reported emotion, appraisal, evidence and selected response are recorded separately.','A specific correction can be made while embarrassment remains; a mistaken critique can be challenged without denying the feeling.','REJECTED','The matched-emotion/different-evidence cases defeat sufficiency.'),
('A common information set guarantees common priorities.','Sharing all evidence would remove every value disagreement.','Artist and archivist know identical object facts but rank mutability and preservation differently.','Common information can settle a factual gap while value trade-offs remain.','Replicas offer one bounded integration; a disputed original can remain a real conflict.','REJECTED','Identical facts coexist with different priorities in the constructed case.'),
('A local model change is useful whenever its wording is novel.','Every paraphrase with new words would deserve benefit credit.','“He declined” is changed to “He opted not to attend” while every inference and choice remains identical.','Novel wording is a candidate representation; useful difference depends on a changed relevant inference or operation.','The paraphrase alone gets no new KEEP; an access-aware consensus correction has a distinct observable consequence.','REJECTED','The synonymous-output countercase defeats novelty sufficiency.'),
('One successful local transfer completes the entire broad mind-change goal.','A corrected schedule would settle trust, interest, appraisal and every remaining target.','The access-window schedule improves while every human trust outcome remains unobserved.','A demonstrated local transfer completes its scoped comparison and leaves the broader portfolio open.','Local KEEP can coexist with unfinished other targets. A genuinely complete future portfolio would need its own evidence.','REJECTED','The untouched target classes refute scope equivalence.'),
('Effort spent loading sources proves intrinsic enjoyment of documentation.','Required source reading would reveal enjoyment even without any choice or report.','The instruction requires loading; a compliant but uninterested actor performs the same reading.','Source effort reveals task allocation under constraints, not enjoyment by itself.','The constrained audit preserves intrinsic interest as unknown; discretionary choices could supply different evidence.','REJECTED','Mandatory expenditure is an alternative explanation of the same behavior.'),
('A context-specific preference must be inconsistent if it reverses elsewhere.','Choosing polish on a free weekend and a rough draft before a deadline would be an error of preference.','The actor explicitly values polish when time is free and completion when a fixed deadline binds.','A preference profile can condition on the actual situation.','Both choices fit the declared conditional policy; an unexplained same-context reversal remains a new question.','REJECTED','The conditions differ, so the opposite choices need not conflict.'),
('A fixed deadline can constrain where a motivational quick win belongs.','An easy task must follow the deadline-dependent task if putting it first misses that required opportunity and supplies no offsetting benefit.','Attempted countercase: quick win is enjoyable. Enjoyment alone does not erase the specified missed deadline; it fails to refute this scoped claim.','An offsetting task effect or a freely abandoned deadline would change the decision premises.','Under the actual constructed times, access first finishes at 15 rather than 25. A task that genuinely reduces setup by ten minutes is a different tested condition.','CONDITIONAL','The displayed timing establishes the scoped constraint; psychological response and alternative effects remain open.'),
('A single total trust score is sufficient for allocating every different responsibility.','Actors with equal total scores would be interchangeable for calculation and scheduling tasks.','One actor calculates accurately but is late; another is punctual but miscalculates. Equal summary scores hide which task each can perform.','Reliance is indexed to competence evidence and commitment scope.','Assign calculation to the demonstrated calculator and scheduling separately. A hidden new accuracy result could alter this allocation, not restore score sufficiency.','REJECTED','Task-specific countercase defeats the monolithic score.'),
('A partially ordered value map can preserve a genuine unresolved trade-off.','The map can state two incomparable options without silently inventing a winner.','Attempted countercase: an explicit priority later selects one. This updates the map and does not refute preservation before the priority exists.','A later declared priority can resolve a previously retained comparison.','Before the priority, label the pair unresolved; afterward, apply the exact priority only in its stated scope.','VALIDATED','The representation follows from the definition of incomparability; its accuracy still depends on correct input.'),
('An interesting claim must also be a claim the investigator wants to be true.','Selecting a dangerous or absurd hypothesis for examination would imply endorsement of its truth.','The investigator selects “all identity threats stop rational thought” specifically to test its doubtful universal.','Exploratory interest and truth endorsement are separate fields.','The claim stays interesting with truth status unverified. A later endorsement would require evidence, not frequency of attention.','REJECTED','The present counterexample is an actual selection with explicitly withheld endorsement.'),
('An unchanged warranted uncertainty can be a useful output when it prevents an unsupported decision.','A comparison can benefit the next operation by retaining the missing discriminator instead of inventing a preference.','Countercase to an overbroad reading: restating uncertainty that changes nothing adds no new benefit. That does not defeat the stated case with a prevented unsupported decision.','Credit depends on the specific prevented inference or changed selection, not uncertainty language alone.','A permission field left unresolved prevents publication in the constructed rule set; repeated “unknown” with no consequence gets no extra KEEP.','CONDITIONAL','The useful consequence is required by the claim and shown in the rule-governed case; human effects are not implied.'),
('Autonomous continuation means never asking any question.','The actor would have to guess even when a new irreversible choice requires another person’s explicit scope.','A contributor’s permission is missing; guessing it would exceed their authority.','Autonomy includes doing available authorized work while retaining specific dependencies on others.','The worker completes source and case analysis while marking permission unobserved. A truly necessary permission question remains possible; no optional interrogation is forced.','REJECTED','Doing available work and recognizing another actor’s authority are compatible; the universal no-question interpretation fails.')]
D1=[
('C1','AW continuation','A constructed increase in initiated tasks coexists with explicitly unwanted obligation and lower chosen agency; initiation alone cannot classify the change as beneficial.','BEDROCK-LOGIC countercase'),
('PREV','Derived alternative','Candidate A: initiation frequency and voluntary-interest evidence together suffice to classify every motivational change in these cases.','Candidate requiring test'),
('PREV','AR consequence','If candidate A is right, two cases identical on those two measurements receive the same motivational-benefit classification.','Conditional consequence to be challenged'),
('PREV','AW of preceding consequence','Case pair: both start two tasks and report equal interest, but one honors an accepted commitment and the other breaks it; the supplied value of reliability distinguishes their benefit.','BEDROCK-LOGIC countercase to sufficiency'),
('PREV','Derived alternative','Candidate B: initiation, voluntary-interest and accepted-commitment outcomes together suffice to classify every motivational change in these cases.','Candidate requiring test'),
('PREV','AR consequence','If candidate B is sufficient, equal initiation, interest and commitment outcomes leave no motivationally relevant distinction for this inquiry.','Conditional consequence to be challenged'),
('PREV','AW of preceding consequence','Matched cases retain those three outcomes, but in one the actor freely chooses the method and in the other a required preferred method is imposed; autonomy is an explicit remaining task value.','BEDROCK-LOGIC countercase'),
('PREV','Derived alternative','Candidate C: the full explicit task-value vector alone suffices to choose between the motivational options in every case.','Candidate requiring test'),
('PREV','AR consequence','If the full vector alone suffices to choose, two cases with the same curiosity gain and autonomy loss receive the same choice without consulting value priorities.','Conditional consequence'),
('PREV','AW of preceding sufficiency consequence','The same curiosity gain and autonomy loss are accepted by an actor who explicitly prioritizes curiosity and rejected by an actor who explicitly prioritizes autonomy; the vector alone cannot recover both choices.','BEDROCK-LOGIC countercase to the exact vector-alone sufficiency claim'),
('PREV','Derived alternative','Candidate D uses the explicit vector plus applicable declared priorities and otherwise returns a partial order, preserving unresolved comparison.','Candidate tested next'),
('PREV','AR consequence','In the matched trade-off case with no priority, candidate D returns unresolved; in a dominance case with every specified value no worse and one better, it returns a conditional preference for the dominating option.','BEDROCK-LOGIC mapping tested in live Test 1'),
('PREV','FAILED AW against the scoped mapping','If the actor’s reported vector omits an affected value, that conditional preference need not generalize; this is an input-completeness limitation, not a counterexample to the specified-vector mapping.','BEDROCK-TEST-DEFERRED: real actor values unavailable')]
C1=['Does the actor actually want this change, rather than an imposed proxy? — resolves C1/C18; actual choice needed.', 'Was the opportunity to perform the behavior present? — C2; inspect access fact.', 'Which human outcome was observed after the plan? — C3; absent here.', 'Which explicit task commitment is enough to continue locally? — C4; supplied instruction.', 'Are the parties disagreeing about efficacy or priority? — C5/C8; exact statement.', 'What changes in a later operation besides wording? — C9/C17; compare actual output.', 'Does a deadline or dependency bind the first task? — C13; schedule arithmetic.', 'Which dimension of trust is relevant to the assigned responsibility? — C14; task evidence.', 'Is the value ordering declared or still partial? — C15; actor priority unavailable.', 'Did a repeated interesting topic gain truth evidence? — C16; source/claim status.']
T1=['Actual generated classification on new input: option X improves curiosity by one declared unit and reduces autonomy by one; option Y leaves both unchanged; no priority supplied. Candidate output from the initiation/interest-only rule: “X increases interest, choose X.” Actual output using the retained vector: “X and Y are incomparable under the supplied information.” The revised record preserves the explicit autonomy cost. Units are constructed ordinal case labels, not psychological measurements.', 'Actual generated classification: “I agree visibility increases reach, but I choose privacy for unfinished work.” Output: efficacy accepted; priority/permission conflict remains. A second outreach statistic is not selected as the next operation; exact-content options are compared. This directly tests C5/C8 on a distinct statement, not a real persuasion outcome.']

R2=[
('A detailed imagined internal narrative is sufficient to select the appropriate social response in every constructed case.','Then narrative richness alone could settle response even when the person’s actual information or values differ.','A fluent narrative attributes disinterest to a reviewer who explicitly lacked access to the proposal.','Social response uses known context and keeps imagined motives as hypotheses.','The access statement changes the response to making the proposal inspectable. A detailed narrative that matches actual evidence can help, but detail is not sufficiency.','REJECTED','The explicit access countercase defeats narrative sufficiency.'),
('A person’s silence after a proposal establishes assent.','The decision record could include everyone silent as accepting the proposal.','A member was absent from the channel and could not receive the proposal.','Assent is tied to a specific communicated proposition and an actual acceptance signal or authorized rule.','Absent member remains unresolved. An explicit delegation rule would supply a different authority premise.','REJECTED','Absence of objection without participation is not acceptance.'),
('Correcting a factual misunderstanding always removes a social disagreement.','Once both know the same facts, no objection remains.','Both accept outreach effectiveness but one rejects recording tentative work.','Factual and value/permission components are addressed separately.','Share a missing fact only if it is missing; compare the accepted trade-off afterwards.','REJECTED','The explicit value difference survives common facts.'),
('Inviting participation and obtaining participation are the same success state.','A sent invitation would establish reciprocal engagement.','Recipient declines an optional invitation; the invitation exists without engagement.','Record invitation, response and shared activity separately.','A decline is a valid response but not the hoped-for activity. A later accepted exchange supplies new evidence.','REJECTED','The optional-decline countercase is decisive.'),
('A one-sided violation must be explained by an equal violation from the other party.','A misattributed quote would require wrongdoing by its recipient before an accurate account could be complete.','Case explicitly contains discussion-only permission and unapproved forwarding, with no recipient counter-violation.','Map both directions without inventing symmetric blame.','Recipient refusal can be recorded as a boundary. New evidence of reciprocal wrongdoing could add a claim but is not required by directionality.','REJECTED','Bidirectional analysis does not logically entail equal fault.'),
('Repairing an artifact necessarily restores interpersonal trust.','Removing an unapproved quote would establish renewed willingness to rely on the publisher.','Quote is removed but contributor explicitly declines future publication reliance.','Artifact repair and later reliance are separately observed outcomes.','The correction can be complete while future trust stays low or unknown.','REJECTED','The correction-plus-declined-reliance state refutes necessity.'),
('Understanding an objection means agreeing with the objection.','A faithful summary would require accepting its proposed decision.','Organizer accurately states the contributor’s privacy priority while retaining a preference for a different public-only project.','Understanding, agreement and permission are distinct statuses.','A summary can be accurate and the project incompatible. Shared meaning does not compel endorsement.','REJECTED','The coherent disagreement-after-understanding case defeats equivalence.'),
('A generated panel of seven roles constitutes independent group input.','Simulated role statements would satisfy the source’s independent-submission requirement.','All seven were generated by one assistant from one prompt; no stakeholder submitted a view.','Generated perspectives inform design; independent group input remains a separate missing stage.','The group-decision record stays partial. Distinct real submissions would change that status.','REJECTED','Different content labels do not change common origin.'),
('A majority vote can override every participant’s contribution-permission boundary.','A vote would authorize publishing a discussion-only quote against its contributor’s limit.','The stipulated participation rule gives the contributor control of that quote, and majority members lack that authority.','Decision rules are applied within their declared authority; permission holders keep their specified boundaries.','A majority can choose among authorized designs but cannot create the missing permission under these rules.','REJECTED','The rule-defined authority countercase defeats unlimited majority scope.'),
('A confident social prediction is stronger evidence than an acknowledged unknown.','An unsupported high-confidence motive claim would outrank a truthful absence of information.','The confident claim “B dislikes the topic” conflicts with B’s explicit “I could not open the file.”','Prediction confidence is separate from evidential support and calibrated by available information.','The explicit access evidence changes the model; unsupported confidence gets no extra weight.','REJECTED','Confidence cannot repair contradiction with the supplied case fact.'),
('A reversible prototype permits any group to proceed despite all objections.','Every dissent would become irrelevant once the object can be restored.','The prototype displays an unapproved personal quote; restoring the object does not undo the exposure.','Reversibility is indexed to each affected exposure, not just object state.','A replica can protect originals while leaving consent or time costs unresolved.','REJECTED','One irreversible exposure defeats the universal proceed rule.'),
('A bounded disagreement can coexist with a useful shared action.','Two parties can share a permitted trial while retaining distinct conclusions.','Attempted countercase: a party refuses all shared actions. That is a different case, not a refutation of the possibility asserted.','Shared action is classified by its actual permission and retained disagreement.','The permitted replica trial demonstrates the logical possibility; acceptance in a real group remains unobserved.','VALIDATED','Existence of the constructed permitted trial supports the modal claim; no universal prescription follows.'),
('The role with the most authority always has the most relevant information.','A venue owner’s view would dominate access, provenance and artistic evidence alike.','Access reviewer finds a visual-only instruction that the venue owner has not inspected.','Authority and information advantage are separate fields.','The owner can decide within authority while the review finding remains relevant and visible.','REJECTED','Unique lower-authority information defeats the universal.'),
('A specific observation can change a social interpretation without identifying a hidden motive.','An access fact could redirect a response while leaving interest unknown.','Attempted countercase: the new fact does not determine all motives. The claim does not require it to, so the objection fails.','Known situational evidence can support a narrower response with motives unresolved.','Make the unreadable proposal available, then preserve the person’s preference as unknown.','VALIDATED','The case mapping demonstrates the limited claim; no hidden emotion is inferred.'),
('The proper facilitator must also decide the content to ensure progress.','Separating process from decision authority would necessarily block a decision.','A facilitator records options and constraints while a named owner decides within those constraints.','Facilitation and content authority can be separated with an explicit handoff.','The constructed agenda has a distinct decision owner; a real session is still pending.','REJECTED','The coherent split-role process refutes necessity.'),
('A relationship goal is achieved when one party performs every controllable action.','A perfect invitation and reliable follow-through would establish mutual initiation even if the other person never reciprocates.','The second person politely declines further contact after the first does all their part.','Track own contribution and reciprocal outcome separately while preserving the full relationship aim.','The full aim stays unachieved; the first person’s completed actions remain accurately recorded.','REJECTED','The decline case defeats sufficiency without rejecting the coherent mutual aim.'),
('A real value conflict should be removed from the record after a compromise is selected.','Choosing a replica trial would make preservation/creative-freedom disagreement irrelevant in future original-object decisions.','Later proposal concerns an original, so the previous unresolved conflict becomes decisive again.','Retain the conflict’s scope and the particular settlement beside it.','Replica permission does not become original permission. A future explicit agreement could broaden it.','REJECTED','The new-object countercase shows why deleting the conflict loses relevant information.'),
('A truthful partial status can coexist with a demonstrated useful local model change.','A listening design can improve a generated question while the live conversation stage remains missing.','Attempted countercase: a design has no local effect. That defeats its KEEP claim, not the possible coexistence asserted.','Evaluate local consequence and original-stage completion as separate judgments.','The question changes from motive accusation to access inquiry; human conversation stays partial.','CONDITIONAL','Local benefit needs actual changed use; when present, missing human stages do not erase it or become complete.')]
D2=[
('C1','AW continuation','A detailed narrative says a quiet reviewer is uninterested, while the case states the reviewer could not access the image; narrative coherence does not select the right next response.','BEDROCK-LOGIC countercase'),
('PREV','Derived alternative','Candidate A: attendance and comment counts alone suffice to select the social response in these cases.','Candidate requiring test'),
('PREV','AR consequence','If those counts suffice, two reviewers with zero attendance and zero comments in this meeting receive the same response despite differing access and standing-delegation states.','Conditional consequence'),
('PREV','AW of consequence','One absent reviewer lacked an invitation; another had a standing delegation rule authorizing the chair to decide. Both have zero attendance/comments in the meeting, but only the second supplies authority for inclusion in the decision.','BEDROCK-LOGIC countercase'),
('PREV','Derived alternative','Candidate B: adding the actor’s own stated reason to the attendance/comment record suffices to determine the disputed condition.','Candidate requiring test'),
('PREV','AR consequence','If the stated reason resolves the response, “this is too much” should identify what needs to change.','Conditional consequence'),
('PREV','AW of consequence','“Too much” is compatible with duration, technical density or an unwanted obligation, each producing a different remedy; the phrase alone does not discriminate.','BEDROCK-LOGIC ambiguity case'),
('PREV','Derived alternative','Candidate C: replacing a vague reason with a concrete disputed-condition statement suffices to record the corresponding remedy as accepted.','Candidate tested next'),
('PREV','AR consequence','If candidate C is right, the reply “the one-hour length is fine; I do not want required homework” permits recording a no-homework role as accepted even before that role is offered.','Conditional implication tested by next countercase'),
('PREV','AW of preceding acceptance consequence','Constructed actor makes that exact complaint, is offered a no-homework role, and declines because they no longer want to join. The complaint identified the disputed condition but did not constitute acceptance of the remedy.','BEDROCK-LOGIC exact countercase to remedy-acceptance sufficiency'),
('PREV','Derived alternative','Candidate D separates identified meaning, proposed remedy and actual acceptance before recording an agreement.','Candidate tested next'),
('PREV','AR consequence','The draft can offer a no-homework role while the agreement field remains pending; an explicit yes later changes only the specified role’s acceptance.','BEDROCK-LOGIC mapping tested in Test 2'),
('PREV','FAILED AW against exact acceptance scope','An explicit yes to attending one session cannot support a promise of weekly participation; extending the acceptance would exceed the proposition actually accepted.','BEDROCK-LOGIC scoped countercase')]
C2=['Was the proposal accessible to each party? — C1/C2/C14; direct case fact.', 'Which exact proposition did a person accept? — C2/C7/C18; exact reply.', 'Is the issue factual, interpretive, value-based or permission-based? — C3; compare statements.', 'Was an invitation actually accepted? — C4/C16; response needed.', 'Which directional violation is evidenced? — C5; do not manufacture symmetry.', 'Did later reliance change after artifact correction? — C6; human response absent.', 'Are perspectives independently submitted or generated? — C8; inspect origin.', 'Who holds the relevant decision authority? — C9/C13/C15; participation rule.', 'Which exposure is reversible? — C11; inspect affected state.', 'Which unresolved conflict can recur under a new object or version? — C17; retain scope.']
T2=['Actual generated interpretation on new statement: “The hour is fine; I do not want mandatory preparation.” Output is “duration accepted; obligation disputed.” Proposed response offers an optional no-preparation role; it does not shorten the hour or infer laziness. This tests the deep branch’s concrete meaning check.', 'Actual generated acceptance record for “Yes, I can attend this one session”: one-session attendance accepted; recurring attendance unknown; homework acceptance unknown. This tests separation of remedy and exact acceptance; the record contains no invented weekly commitment.']

if __name__=='__main__':
 araw('dependency-gu-1-araw','autonomous beneficial efficient broad mind change',R1,D1,C1,T1)
 araw('dependency-gu-2-araw','social and reciprocal change without forced agreement',R2,D2,C2,T2)
 print('Two ARAW dependency registries written')
