from write_records import add

def tab(h,rs):return '| '+' | '.join(h)+' |\n|'+'|'.join('---' for x in h)+'|\n'+'\n'.join('| '+' | '.join(r)+' |' for r in rs)

def empth(n,title,intent,start,context,narrative,divergences,findings,summary,transfer,change,benefit,verdict):
 body=f'''Interpretation: perspective-gap diagnosis. All people and situations below are explicitly constructed. First-person narrative is a hypothetical model, not access to a real person’s hidden thoughts. The corruption-pre-inoculation source was loaded separately. Six context categories are reconstructed before interpretation.

{tab(['Context category','Stipulated information and resulting model boundary'],context)}

Hypothetical internal narrative, six sentences:

“{narrative}”

Ten divergence points, each typed and tested:

{tab(['Finding','Type / issue','Other party versus proposer','Model test, simpler alternative, confidence'],[(f'F{i}',*r) for i,r in enumerate(divergences,1)])}

Twelve additional independent findings developed from the context and divergences:

{chr(10).join(f'F{i+11}. {s}' for i,s in enumerate(findings))}

Model synthesis: {summary}

Source boundary: the archive’s assertions about universal local rationality and identity threats shutting down rational processing are not adopted as case facts. In the primary perspective-taking experiments, imagining another person’s perspective did not consistently improve accuracy; direct perspective-getting improved accuracy in the final reported experiment. These results motivate a limit on the confidence of this constructed model, not a universal instruction to interrogate others. [Eyal, Steffel and Epley, primary article](https://www.researchgate.net/publication/324232939_Perspective_mistaking_Accurately_understanding_the_mind_of_another_requires_getting_perspective_not_taking_perspective)

Certificate: the model is justified only to the extent the stipulated information and explicit preferences discriminate it from simpler alternatives. A plausible internal narrative alone has no confirmatory force. Every speculative motive remains open to contradiction by the person’s actual reply; no human change is reported.'''
 add('empth',n,title,intent,start,body,change,benefit,verdict,'Content includes a view that does not serve the proposer’s preferred outcome. Organization preserves context facts, typed divergences, confidence, and disconfirmers; it does not merge them into one definitive character portrait.','Obtain real perspective when available; test a simpler logistical account; compare what changes when the value difference is explicit versus inferred.','Original 8x floors: 10 divergence points, 6 context categories, 6-sentence internal narrative, 22 findings. Executed: those counts exactly, with independent F1–F22 findings and model alternatives/disconfirmers.',transfer)

empth(1,'More evidence does not settle an explicit value difference','Replace an information-gap remedy when the other party already accepts the factual claim but values a different outcome.','For a fictional organizer facing resistance to public project updates, I initially favored showing more evidence that visibility improves opportunities.',
[('Information access','Reviewer R has seen the same outreach results as organizer O and explicitly accepts that visibility can bring opportunities; disbelief in that benefit is not a necessary premise.'),('History','R previously participated only in private working sessions in this constructed case; no history of betrayal or social anxiety is invented.'),('Beliefs','R says public summaries can oversimplify unfinished work; O believes concise updates help outsiders understand. Both can be true for different drafts.'),('Values','R states privacy and freedom to revise outrank additional exposure for this project; O prioritizes discoverability. This difference is explicit in the case.'),('Incentives','O gains new collaborators from updates; R bears the cost of being represented publicly. The distribution of benefit and exposure differs.'),('Constraints','R permits sharing finalized results but not raw discussion notes; O has authority over the project page but not authority to convert private comments into endorsement.')],
'I understand that public updates can bring useful opportunities. I still do not want unfinished comments attributed to me. I want room to revise a thought without managing an audience for each revision. A finalized result is different from a rough discussion note. I am willing to help produce an accurate public result within that boundary. More proof that publicity works will not by itself change what I am choosing to expose.',
[('Information','O suspects R doubts outreach value; R explicitly accepts it.','The stated acceptance defeats that explanation; CONFIDENT within case.'),('Values','O favors additional exposure; R prioritizes privacy for unfinished work.','Explicit priorities, not projected fear; CONFIDENT.'),('Interpretation','O treats an update as an invitation; R treats attributed notes as a representation of a person’s position.','Both descriptions fit different update contents; PLAUSIBLE.'),('Interest','O receives outreach benefit; R bears attribution exposure.','Distribution follows roles; no claim of selfish motive; CONFIDENT.'),('Identity','O could treat publicity as proof of commitment; R does not state that identity criterion.','Identity threat is SPECULATIVE and not needed for the value account.'),('Information','O knows the posting workflow; R lacks preview of the exact proposed text.','A concrete preview could settle wording questions, not the whole value difference; PLAUSIBLE.'),('Interpretation','O calls comments “project material”; R distinguishes rough contributions from consented statements.','Permission scope is explicit; CONFIDENT.'),('Values','O wants frequent updates; R prefers infrequent finalized milestones.','Cadence is a genuine trade-off, not necessarily misunderstanding; CONFIDENT.'),('Interest','O wants O’s page to be active; R’s participation is optional.','Exit is an allowed case state, not a threat inferred from silence; CONFIDENT.'),('Information','O assumes a summary anonymizes enough; R’s actual recognition standard is not provided.','Need a real criterion; SPECULATIVE until R responds.')],
['F1 and F2 together mean an additional outreach statistic does not answer R’s stated objection; information about efficacy and priority over privacy are different propositions.',
'A finalized result preview is relevant because R explicitly permits finalized sharing; it is a candidate within the boundary, not a substitute demand for raw notes.',
'A refusal to publicize raw discussion is compatible with continued private collaboration, so “R is withdrawing from the project” does not follow.',
'Anonymization cannot be presumed acceptable because R’s permitted scope may concern unfinished content as well as name attribution.',
'If O controls the website, R’s inability to edit it creates a reliance exposure that a verbal reassurance does not remove by itself.',
'R’s acceptance of outreach benefits prevents the model from explaining resistance solely as ignorance without contradicting the input.',
'If R later accepts attributed rough notes without conditions, the current strict-boundary model needs revision rather than an invented hidden fear.',
'If R rejects even finalized results, the stated finalized/raw distinction was incomplete or changed; the model must retain that possible update.',
'A public-only project can remain incompatible with R’s chosen participation, even after complete mutual understanding.',
'The least-powerful voice in this case holds unique authority over its own endorsement; formal website control does not settle that scope.',
'An accurate objection summary can preserve both the factual benefit and the chosen privacy cost; treating one as false loses a declared value.',
'The next useful inquiry is about acceptable content and exposure, because those variables remain unsettled while efficacy is already accepted.'],
'R accepts the claimed opportunity benefit and chooses a narrower publicity boundary. Key divergences are F1, F2, F4 and F7. R needs the actual proposed content and a respected scope choice, not an invented diagnosis of fear. A factual summary of the boundary could make R recognize the description; whether it makes R feel heard is unobserved. Predicted rejection of another generic efficacy argument follows from F1/F2, not from a supposed personality trait. Confidence is high for the explicit value difference and low for unstated emotions. Weakest assumption is whether “finalized” has the same meaning for both. Disconfirmers are R’s revised stated boundary or evidence that the efficacy claim was not actually accepted.',
'New constructed statement: “I agree the recorded workshop reaches more people; I still want an unrecorded session for tentative ideas.” The initial remedy “show reach statistics” treats an already accepted fact as missing. Applying this model produces the actual issue classification “values/permission conflict over recording, with reach benefit accepted,” then a generated option comparison between recorded finalized talk and unrecorded exploratory session. The representation now preserves both explicit propositions; no human acceptance of either option is claimed.',
'I now classify accepted-fact/different-priority statements as value or permission differences, not unresolved efficacy disputes.',
'The subsequent issue classification avoids spending another operation proving what the constructed speaker already accepts and directs comparison to the actual disputed exposure.','KEEP')

empth(2,'A critic can be invested in a project they oppose','Model an opponent’s commitment without making opposition a proxy for disloyalty or inventing a flattering motive.','Repeated objections in a constructed team can look like low commitment, but the relation between critique and investment has not been established.',
[('Information access','Technical reviewer T sees failure logs that proposer P has summarized but not read in detail; P has user requests T has not seen.'),('History','T signed off one earlier component and rejected another. This mixed case history does not support blanket opposition.'),('Beliefs','T thinks the new interface hides error states; P thinks an uncluttered interface helps use. Each belief concerns a different failure cost.'),('Values','T explicitly values diagnosability; P explicitly values simplicity. T’s deeper personal identity is unknown.'),('Incentives','T will support the product after release; P is evaluated on completing the demonstration. These stipulated responsibilities distribute later costs differently.'),('Constraints','Demonstration date is fixed; release date is not. The demo can be simulated if honestly labeled; production behavior cannot be inferred from it.')],
'I want the project to work after the demonstration as well as during it. I have seen errors that the current summary does not show. I do not object to a simple interface in itself. I object to removing the information needed when something fails. I can support a clearly labeled demo while the release issue remains unresolved. I need the decision to say which claim is being approved.',
[('Information','P sees a short summary; T sees detailed failures.','Logs are stipulated; CONFIDENT information gap.'),('Values','P prioritizes interface simplicity; T prioritizes diagnosis.','Explicit trade-off; CONFIDENT, no hidden motive needed.'),('Interest','P benefits from a completed demo; T bears later support work.','Role costs differ; CONFIDENT without moral judgment.'),('Interpretation','P hears “block release”; T says “preserve error visibility.”','Quoting exact objection discriminates; PLAUSIBLE.'),('Identity','P interprets objections as not being a team player; T’s self-view is unknown.','SPECULATIVE; do not use as evidence.'),('Information','P knows user requests; T has not seen them.','T’s critique may omit a real simplicity need; CONFIDENT gap.'),('Interpretation','P treats demo approval as release approval; T distinguishes them.','Case dates differ; CONFIDENT.'),('Values','T can prefer a labeled simulation over a misleading live claim.','Supported by stipulated permission, not universal honesty trait; PLAUSIBLE.'),('Information','Neither has tested the proposed error panel with users.','Both outcome predictions remain open; CONFIDENT absence.'),('Interest','Both lose if a misleading demonstration drives a premature release.','Shared risk conditional on decision use; PLAUSIBLE.')],
['The mixed sign-off history defeats a blanket “T opposes everything” description in this case.',
'T’s support burden supplies a reason to notice diagnosis problems even if T has no personal animosity toward P.',
'P’s missing logs can be addressed by a concrete failure example; that does not settle the separate simplicity priority.',
'T’s missing user requests can be addressed by direct requirements; that does not erase actual failure logs.',
'A demo-only decision can proceed while release remains open if the demonstration is honestly labeled and no other constraint forbids it.',
'Calling a simulation production-ready would create a new claim, not resolve the diagnosed information gap.',
'An error-detail expansion could preserve uncluttered default presentation while offering diagnosis; it remains an untested design.',
'T’s criticism can be consistent with investment, but the model cannot infer sincere care solely from criticism.',
'If T rejects every alternative without referencing the issue, the present task-grounded model needs additional evidence.',
'If P accepts visible errors despite a less polished demo, a supposed status-only motive is weakened.',
'The current account risks flattering T as the sole responsible person; P’s real usability constraint remains represented to counter that bias.',
'The precise next comparison is between hidden error states, an optional diagnostic view, and a labeled demo boundary—not between loyalty and disloyalty.'],
'T has task-specific reasons to object and a separate permission boundary for a demo. F1/F6 show reciprocal information gaps; F2 is a real priority tension; F5 is an unsupported identity interpretation. What could make T recognize the account is an exact restatement of the error-visibility concern. What could provoke defensiveness is labeling the objection disloyalty, but no emotional outcome is observed. Model confidence is moderate within case. The weakest assumption is that T’s stated concern captures the full objection; a specific different explanation from T would disconfirm it.',
'Later generated decision summary: “Proceed with a labeled demo; production release remains pending an error-visibility decision. T’s objection concerns diagnosis, and P’s concern concerns a simple default view.” The summary is concrete and retains both views; actual mutual understanding or support is unobserved.',
'The constructed critic is represented as potentially invested while still opposed; no real motive or cooperation change has been established.',
'A decision summary preserves the actual disputed claim and reciprocal missing information instead of collapsing it into a loyalty judgment.','UNRESOLVED')
