from write_records import add

def tab(headers,rows):return '| '+' | '.join(headers)+' |\n|'+'|'.join('---' for x in headers)+'|\n'+'\n'.join('| '+' | '.join(r)+' |' for r in rows)

def trust(n,title,intent,start,parties,events,pairs,asym,system,interventions,sequence,uncomfortable,transfer,change,benefit,verdict):
 et=tab(['Event','Constructed fact','Trust relevance'],[(f'E{i}',e,r) for i,(e,r) in enumerate(events,1)])
 pt=tab(['Direction','Competence','Integrity','Benevolence','Risk accepted / withheld','Structural/system exposure'],pairs)
 it=tab(['Intervention','Target and concrete act','Mechanism, cost, signal and prerequisite'],[(f'I{i}',a,b) for i,(a,b) in enumerate(interventions,1)])
 body=f'''Interpretation: {'assessment and allocation' if n==1 else 'repair' if n==2 else 'design'}. Entire social situation is constructed. Each fact below is stipulated; trust levels are conditional reliance assessments generated from those facts, not measurements of a human’s feelings. H/M/L/U mean high/medium/low/unknown within the stated task. No broad allegation of reciprocal blame is imported from the source. The corruption-pre-inoculation original was also loaded and retained.

Parties: {parties}

Trust trajectory, twelve events:

{et}

Six unordered pairs, mapped in both directions (twelve directional assessments); all include competence, integrity, benevolence, structural exposure, and wider system effects:

{pt}

Asymmetry and history: {asym}

System analysis: {system}

Specific interventions, ten:

{it}

Repair/design sequence: {sequence} The checkpoints are proposed opportunities to observe commitments, not a forecast that a person’s trust will recover in a fixed number of days. Actual trust change would require observed recipient reliance, disclosures, or reports across later interactions; none exists in this constructed application.

Uncomfortable case contribution: {uncomfortable} This concerns the fictional party’s role, not a discovered trait of the real user. Confidence is moderate for the map’s logical fit to stipulated facts and low for any reaction prediction. Weakest assumption: how parties interpret the same event; their actual perspectives were not collected.

Source-claim boundary: this application does not assume that violations always outweigh trust-building, that erosion is always bidirectional, or that every integrity breach should be answered by over-delivery. The original research on response to alleged competence and integrity violations examined different conditions; it does not license false denial or a universal repair rule. [Kim, Ferrin, Cooper and Dirks, primary study](https://ink.library.smu.edu.sg/lkcsb_research/2368/)

Certificate: the dimensional assessment depends on event-specific evidence; a favorable event on competence does not supply an integrity commitment, and an unknown benevolence judgment is not a negative finding. The strongest alternative is that a hidden event changes the map, so the resulting allocation remains scoped to this case.'''
 add('trust',n,title,intent,start,body,change,benefit,verdict,'The content preserves unknown dimensions and unilateral as well as reciprocal failure possibilities. The directional table retains risk and system exposure beside each assessment; intervention plans are distinct from observed outcomes.','Test a new event that changes one dimension only; obtain actual recipient perspective if a real case is supplied; compare a reliance decision before and after an intervention.','Original 8x floors: 6+ party pairs, 3 dimensions plus structural and system analysis, 12 events, 10 interventions. Executed: six unordered pairs in both directions, twelve events, ten interventions, each with costs/prerequisites and a scoped signal assessment.',transfer)

trust(1,'Trust dimensions change a concrete delegation','Replace one overall trust score with task-specific reliance where evidence differs by dimension.','I initially favored a medium overall reliance posture for the fictional analyst because accurate work and a late delivery offset each other in a single summary.',
'A analyst; B editor; C coordinator; D decision owner. The concern is which responsibilities to delegate before the next research review.',
[('A correctly recomputes a disputed denominator in front of B.','B→A competence evidence for that calculation'),('A misses an agreed draft time but reports the delay before the deadline.','Schedule reliability mixed; no concealed lateness'),('B changes “possible” to “certain” in A’s draft.','A→B integrity/claim-preservation concern'),('B restores the qualifier and logs the edit after correction.','Repair evidence, not erasure of E3'),('C receives D’s decision deadline but initially omits it from the shared plan.','A/B lack coordination information'),('C posts the deadline with acknowledgement.','Information-flow repair'),('D accepts an explicitly unresolved appendix.','Candor permitted in this interaction'),('D declines to request unrelated private background.','Task boundary respected'),('A refuses to present an untested intervention as a result.','Claim discipline evidence'),('B preserves a negative example despite its awkward prose.','Fidelity evidence beyond polishing'),('C records their own omitted deadline in the change log.','Visible accountability'),('D asks which conclusions change under a different criterion.','Decision standard becomes inspectable')],
[('A→B','M E3/E10','M E3/E4','U','Small edits / final inference wording','Edit history exists; release standard shared'),('B→A','H E1','M E2','U','Calculation check / sole schedule owner','Deadline dependence remains'),('A→C','M E5/E6','M E11','U','Coordination updates / silent deadline assumptions','Shared calendar controls access'),('C→A','M E1','M E2','U','Bounded review / deadline guarantee','C owns timing escalation'),('A→D','M E12','M E7/E8','M E8','Uncertainty disclosure / private biography','D controls acceptance criteria'),('D→A','H E1/E9','M E2','U','Reasoned result / guaranteed completion time','Release decision stays with D'),('B→C','M E6','M E11','U','Published deadline / inferred deadlines','Calendar is common source'),('C→B','M E10','M E4','U','Formatting / unchecked certainty edits','Claim changes need explicit mark'),('B→D','M E12','M E7','U','Show weak claim / assume approval','Decision criteria affect all edits'),('D→B','M E10','M E3/E4','U','Source-linked copyedit / factual upgrade','D keeps release authority'),('C→D','M E12','M E7','U','Decision deadline / hidden criteria','Power lies with D'),('D→C','M E5/E6','M E11','U','Acknowledged scheduling / assumed transmission','Shared acknowledgement required')],
'B’s confidence in A’s calculation is stronger than A’s confidence in B’s claim editing. The late draft affects schedule reliance without undoing the displayed correct calculation. E3/E4 and E5/E6 show local repair sequences; they do not establish a long-term rising trajectory.',
'Incentives favor concise confident outputs, while the task needs uncertainty preserved. Commitments become trackable through dated changes; claim revisions become visible through edit records. D can approve or reject, so A/B need a way to state a missing premise without pretending confidence. The system makes bounded reliance rational only partially: calculation verification is available, future timeliness remains uncertain.',
[('B→A competence: assign one disputed calculation with original inputs.','Direct task evidence; 15-minute budget; potentially strong for that calculation; inputs must be complete'),('D→A integrity: agree a checkable intermediate time instead of a final-time guarantee.','Smaller commitment; coordination cost; medium evidence after performance; A must accept'),('A→B integrity: mark every certainty-word edit in the diff.','Claim-change visibility; editing cost; strong detectability, no inferred goodwill; shared diff access'),('D→B system: require one source pointer for each strengthened claim.','Release structure; review cost; detects unsupported strengthening; D enforces criterion'),('A/B→C coordination: acknowledge the displayed deadline.','Common information; one message cost; observable receipt, not agreement; channel available'),('C→D integrity: publish criteria changes with time.','Power accountable; D gives up silent changes; signal after actual use; criteria known'),('D→A benevolence: invite one objection that could delay D’s preferred decision.','Vulnerability from D; possible delay; meaningful only if objection is considered'),('A→D integrity: present a disconfirming case alongside preferred conclusion.','A risks a weaker recommendation; evidence visible; depends on an actual countercase'),('B→A competence: ask A to distinguish arithmetic from framing correction.','Separates task evidence; small review cost; narrow diagnostic signal'),('All directions system: review two completed handoffs and one failed one.','Pattern visibility; shared time cost; medium after records exist; failures not hidden')],
'First preserve E3’s exact qualifier correction and E5’s deadline omission. Next complete one bounded calculation and one acknowledged handoff. At the next three handoffs, examine whether the respective commitments held; change reliance only on the observed dimension.',
'D’s wish for a quick confident answer can create pressure that D then interprets as an author’s unreliability. The case therefore needs visible criteria, not only better author conduct.',
'New constructed delegation: analyst P has two correct calculations and one late report; analyst Q has on-time reports but an uncorrected denominator error. An overall “both medium” summary leaves both interchangeable. Applying the dimensional map produces P for arithmetic review and Q for a deadline reminder only, with a separate verifier for Q’s calculation. The generated allocation now matches the provided task evidence and avoids assigning arithmetic to the known incorrect calculator.',
'The working reliance judgment now separates demonstrated task competence from future commitment reliability; one medium score no longer makes unlike risks interchangeable.',
'The subsequent allocation assigns the calculation to the actor with direct calculation evidence and treats scheduling as a separate responsibility. Human trust repair is unobserved.','KEEP')

trust(2,'Repair after an unapproved public attribution','Design a repair targeted to the violated commitment without inventing equal blame.','An apology and stronger future collaboration seem plausible ingredients, but neither directly repairs an unapproved attribution already published in a fictional community project.',
'A proposer; B participant whose words were quoted; C facilitator; D community archive editor. B’s draft comment was published as endorsement although B had permitted discussion only.',
[('B gives A a draft comment marked discussion-only.','A receives an explicit scope limit'),('A forwards it as endorsement to D.','B→A integrity violation within the case'),('D publishes the endorsement without checking scope.','B→D competence/process failure'),('C asks whether the text was approved.','C surfaces missing evidence'),('B requests removal.','Clear desired immediate repair'),('A acknowledges forwarding exceeded permission.','Specific acknowledgement'),('D removes the quote and logs the correction.','Artifact repair, not trust restoration'),('A asks B for another endorsement immediately.','Pressure can be assessed without guessing motive'),('B declines a new endorsement.','Observed fictional boundary, not irrationality'),('C records an opt-in quote rule.','Structural proposal'),('D adds an approval-status field.','Process change'),('A shares a draft of the correction for factual checking only.','Bounded opportunity for renewed reliance')],
[('A→B','M E1','M E9','U','Fact check / endorsement assumption','Consent scope explicit'),('B→A','U','L E2','U','Correction fact check / public representation','A has forwarding power'),('A→C','M E4','U','U','Facilitation / presumed absolution','C controls session'),('C→A','U','L E2','U','Specific acknowledgement / future scope compliance','Rule enforcement needed'),('A→D','M E7','M E11','U','Removal record / unchecked new quote','Archive field now visible'),('D→A','U','L E2','U','Correction draft / approval assertion','D must verify source permission'),('B→C','M E4','M E10','U','State boundary / private emotional disclosure','C can invite not compel'),('C→B','M E5','M E9','U','Scope clarification / obligation to reconcile','B owns participation'),('B→D','M E3/E7','M E7','U','Verify removal / new publication','D controls public artifact'),('D→B','M E5','M E9','U','Permission statement / assumed endorsement','B’s refusal remains valid'),('C→D','M E7','M E11','U','Approval log / automatic uptake','Rule needs actual use'),('D→C','M E4','M E10','U','Process review / relationship repair guarantee','Separate roles')],
'The case has an explicit one-sided permission violation. B’s refusal is consistent with the available evidence; no counter-violation is invented to force symmetry. D’s prompt correction repairs the artifact, but B’s willingness to rely on D afterwards is unknown.',
'Public-credit incentives favored endorsement claims; approval evidence was not visible. A possessed forwarding power, D publication power, and B the represented voice. The new approval field improves detectability but fails if D publishes unchecked content anyway. Structural rationality is partial until the next actual permission decision is observed.',
[('B→A integrity: A identifies exactly which forwarding exceeded permission.','No motive claim; reputational cost to A; high specificity, effect unknown; acknowledgement truthful'),('B→D process: retain a visible correction beside any cached reference.','Artifact remedy; archive work; observable scope, no emotional guarantee'),('B→A autonomy: A withdraws the immediate new-endorsement request.','Removes a new demand; A loses promotional option; requires genuine optionality'),('All publication pairs: default approval status to unapproved.','Structural control; editing effort; detectable status; D uses it'),('D→A integrity: require the approver’s exact scope record.','Verification; coordination cost; narrow strong evidence; record available'),('A→B benevolence: offer B no obligation to review the whole project.','Vulnerability from A; less promotion; meaning depends on actual respect'),('B→C process: private channel for factual correction without reconciliation demand.','Separates remedy and relationship; facilitator time; B may decline'),('C→D competence: inspect one removed quote and one permitted quote.','Different scope examples; review cost; tests archive behavior'),('D→B integrity: return what was removed and where.','Verifiable completion; audit cost; does not require forgiveness'),('All: review the next proposed quotation before publication.','Prospective checkpoint; slows release; observable operation; permission source known')],
'Immediate repair: remove misattribution and retain a correction trace. Next: avoid requesting replacement endorsement. After one future permission decision and again after three publication cycles, compare stated approval scope with actual use. The actual relationship can remain distant even if the process works.',
'A’s desired restoration of collaboration is not an obligation on B. A can incur the cost of accurate correction without receiving renewed endorsement.',
'Later generated invitation: “You can check whether this correction accurately describes your permitted scope; you do not need to endorse the project or resume participation.” This differs from an apology followed by a new endorsement request, but no real recipient receives it or responds.',
'The repair plan targets representation permission and separates correction from renewed cooperation. The social outcome is still untested.',
'A concrete repair and opt-in invitation exist; no forgiveness, restored trust, or increased interest is claimed.','UNRESOLVED')

trust(3,'Trust design for disagreement that remains disagreement','Design cooperation between people whose priorities need not converge.','A shared statement of purpose seems a useful first trust structure, but it may conceal different assumptions about which disagreements will be tolerated.',
'A experimental artist; B archivist; C accessibility reviewer; D venue coordinator. They are planning a fictional exhibition that can change during visitors’ interaction.',
[('A proposes visitors rearrange objects.','Creative competence proposal, not tested'),('B states originals must remain traceable.','Explicit preservation criterion'),('C requests a non-visual route through the work.','Distinct access information'),('D states the room must close at a fixed time.','External operating constraint'),('A builds a reversible sample rearrangement.','One demonstrated prototype'),('B logs sample provenance.','One demonstrated archive operation'),('C identifies a visual-only instruction in the sample.','Specific review evidence'),('D provides an alternate access time for testing.','Concrete accommodation in case'),('A agrees to replicas for fragile originals.','Interest integration'),('B agrees that replica order can change.','Preservation not total stasis'),('C supplies a text-and-audio draft instruction.','Alternative representation'),('D declines an extension beyond closing.','Constraint enforced rather than hidden')],
[('A→B','M E6','M E10','U','Provenance / unrestricted change approval','Archive scope defined'),('B→A','M E5','M E9','U','Replica changes / original alteration','Reversibility is conditional'),('A→C','M E7/E11','U','U','Access review / creative endorsement','C reviews access, not aesthetic worth'),('C→A','M E5','M E9','U','Reversible sample / accessible final work assumption','Final review still needed'),('A→D','M E8','M E12','U','Test slot / closing extension','Venue limit fixed'),('D→A','M E5','M E9','U','Prototype trial / unbounded visitor activity','Staffing exposure'),('B→C','M E7','U','U','Instruction access / provenance authority','Distinct review domains'),('C→B','M E6','M E10','U','Traceability / sensory access inference','Archive cannot certify access'),('B→D','M E8','M E12','U','Storage schedule / extra hours','Shared resource limit'),('D→B','M E6','M E10','U','Object log / visitor-flow expertise','Handoff needs closing record'),('C→D','M E8','M E12','M E8','Testing accommodation / unlimited timing','Constraint and access interact'),('D→C','M E7/E11','U','U','Concrete access critique / final approval assumption','Review findings need implementation')],
'A and B disagree about originals but agree about changeable replicas. C’s competence evidence concerns access, not aesthetics. D’s refusal of late closing is not evidence of hostility. Statements of shared purpose do not remove these distinct scopes.',
'One approval label would let a provenance check be mistaken for an access check. Different criteria therefore need separate owners, and a change to the installation can invalidate one approval while leaving another intact. Decision power lies with D for hours, B for original handling, and A for artistic choices within those constraints; C’s access findings must be visible even without final decision power.',
[('A↔B: label original and replica before trial.','Separate preservation exposure; labeling cost; observable status; inventory accurate'),('B→A: log each reversible rearrangement once.','Traceability with creative freedom; record cost; applies to replicas only'),('C→A: attach access finding to the specific instruction version.','Narrow evidence; review cost; prevents stale approval; version visible'),('A→C: demonstrate text/audio alternative.','Capability evidence; design time; effect unknown until used'),('D→all: publish fixed room-close time before selection.','Transparent constraint; gives up late discretion; no trust feeling assumed'),('A→D: commit to reset task and duration estimate.','Trackable promise; cleanup cost; estimate unverified'),('D→C: reserve a test slot accessible to the review format.','Structural opportunity; venue cost; depends on availability'),('B→C: distinguish object history from visitor instructions.','No cross-domain authority inference; small annotation cost'),('A→B vulnerability: show a sample whose aesthetic choice may be vetoed for original safety.','A exposes preferred design to a bounded veto; meaningful only within agreed scope'),('All: use separate provenance, access, and timing acceptance fields.','Structural system change; coordination effort; narrower approvals survive unrelated changes')],
'First classify objects and version the sample. Next test a reversible change, record provenance, and examine both instruction modalities. Before opening, inspect timing/reset; after each material version change, recheck only the affected approval. These are proposed trials, not a claim that the team has agreed.',
'A’s wish for creative latitude is compatible with B’s original-handling limit, but not with silently treating every review as aesthetic endorsement. D’s closing constraint may remain even if all share the exhibition’s purpose.',
'New generated acceptance record has three independent fields: provenance accepted for replica set v1; access instruction unresolved for audio draft v2; closing/reset plan accepted for the stated time. A single “team approves” badge is not used. No actual team has adopted the record.',
'The trust design makes disagreement scopes inspectable while cooperation remains a proposed arrangement.',
'The constructed artifact prevents one kind of approval from standing in for another; real coordination and trust effects remain unobserved.','UNRESOLVED')
