from write_records import add,N
add('mp',1,'A motivating start still has to catch the dependency window','Revise a quick-win-first draft when its short task blocks a more valuable time-sensitive opportunity.','For a hypothetical resistant researcher, I initially placed a ten-minute easy cleanup first to create visible progress before harder work.', '''Constructed input: the researcher reports low energy and resistance; a two-hour session contains an external approval window. These states are stipulated, not measured for the user. The archive’s claims about dopamine, typical peak hours, and universal recovery intervals are not assumed established.

Eight tasks: Q clear two obsolete notes, 10 minutes/easy; A submit the access request, 15 minutes/medium, due by minute 20; R inspect an available result, 25 minutes/hard, requires A; C annotate one example, 10 minutes/easy; D compare two explanations, 20 minutes/hard; E name the next question, 5 minutes/easy; F prepare materials, 10 minutes/easy; G record uncertainty, 5 minutes/medium. Recovery allocation: 10 minutes after the first demanding block and 10 after the second. Total is 120 minutes.

Rule application: quick win is available but cannot displace A’s window; hardest work follows access and a state check, not an assumed morning peak; difficulty alternates where dependencies permit; minimum initial commitment is opening and completing A’s request fields, not a promise of escalating motivation; visible progress is the submitted request; ending leaves E as a named next question. Recovery is a design allocation, not a physiological guarantee.

Initial sequence Q(0–10), A(10–25) misses the minute-20 access deadline by five minutes. Revised sequence A(0–15), Q(15–25), R(25–50), recovery(50–60), C(60–70), D(70–90), recovery(90–100), F(100–110), G(110–115), E(115–120). The request finishes five minutes before its deadline. This does not prove the person will feel more motivated; it preserves an opportunity the first schedule loses.

Eight state/dependency countercases: high energy starts with the hardest ready task; low energy with no deadline permits Q first; low energy with the window retains A first; medium state permits alternation; blocked R cannot occupy the first slot; an overlong A requires smaller complete submission only if accepted; an exhausted actor has no evidence-based duty to continue from this design; a recovered actor can choose D if its prerequisites hold.

Certificate: claim “the quick win should be first in this case” fails because the displayed times miss an externally fixed window. The alternative first task is itself a complete, bounded access action. Strongest contrary branch: Q could shorten later work by more than five minutes; the constructed input provides no such effect. The exact scheduling improvement stands; motivational effect does not.''','The task order now conditions motivational heuristics on dependency windows; the easy first draft is replaced.','A later schedule also meets its reservation window without relying on an unobserved motivational boost.','KEEP','Content improves by evaluating actual finish times. Organization puts immovable opportunities before state-matched ready tasks; the person’s reported state remains an input, not inferred from a clock.','Test a real measured energy profile; compare quick-win and direct-start sessions without deadlines; test whether the access action itself supplies satisfying progress.',N+' Eight tasks, six original ordering rules, eight state/dependency cases, two complete schedules, and a distinct later window calculation.','New constructed session: a studio station becomes unavailable at minute 20; setup needs 15 minutes and an optional confidence exercise needs 8. The initial easy-first schedule finishes setup at minute 23 and loses the station. Applying the revised ordering puts setup first, finishing at 15; the confidence exercise follows. The actual generated plan removes three minutes of deadline lateness. This is scheduling arithmetic, not a demonstrated human motivation change.')
add('mp',2,'Difficulty alternation and switching cost pull apart','Compare a motivational alternation recipe with a grouped sequence when task switching has explicit setup costs.','For a medium-energy, neutral-motivation constructed researcher, alternating hard and easy tasks is a plausible first draft.', '''Constructed state: medium energy, neutral motivation, 150 minutes. No user energy cycle is inferred. Eight tasks: two hard diagram comparisons (20 minutes each), two easy diagram label cleanups (5 each), two hard prose comparisons (20 each), two easy prose citation cleanups (5 each). Switching between diagram and prose work requires 8 minutes of setup by stipulation; same-type switches require zero. Two ten-minute recovery intervals are budgeted.

The six original ordering rules produce alternatives: quick win first is one diagram cleanup; hardest task at peak cannot be assigned because no peak observation exists; alternating difficulty can occur within the diagram block and then within the prose block; commitment escalation starts with one valid label repair; end on a high means preserve a clear next task, not require positive feeling; visible progress uses completed comparisons and their open questions.

Plan A alternates modality as well as difficulty: hard diagram, easy prose, hard diagram, easy prose, hard prose, easy diagram, hard prose, easy diagram. Seven modality switches cost 56 minutes, base work is 100, recovery 20, total 176: exceeds the session by 26 minutes. Plan B keeps difficulty alternation inside each modality: easy diagram, hard diagram, easy diagram, hard diagram, break, easy prose, hard prose, easy prose, hard prose, break. One switch costs 8; total 128. Remaining 22 minutes is slack, not an obligation to add work.

Eight variations considered: no switching cost → A becomes time-feasible; a deadline on prose → prose block moves first; diagram fatigue reported → shorten that block; no peak data → no universal clock rule; resistance to diagram → choose a complete easy diagram start if still desired; source already open → setup estimate changes; inability to concentrate → stop/seek a different task rather than interpret as lack of values; most interesting thread appears → optional choice competes with scheduled requirements.

Recovery and emotional payoff remain hypotheses for the fictional actor. The source’s biological mechanism claims are not necessary for either arithmetic result. No direct estimate of burnout, boredom, or dopamine is made.

Later application: a three-task draft with a 6-minute setup cost is grouped into one context before the next. The output is more time-feasible by construction; this transfers the already retained dependency/state constraint logic from mp-1, so it is not another KEEP.''','The revised hypothetical schedule separates difficulty alternation from modality switching, but no human motivation response is observed.','The constructed plan has 22 minutes of slack instead of a 26-minute overrun; the general psychological advantage remains untested.','UNRESOLVED','Content captures a genuine conflict between two organizing dimensions. Organization records setup costs beside difficulty rather than treating hard/easy as the whole sequence.','Measure actual setup cost; test a group that enjoys switching modalities; compare boredom and task quality with the same total session duration.',N+' Eight tasks, two full sequences, six ordering-rule decisions, and eight variations.')
add('mp',3,'Ending well can mean preserving a live question','Explore an end-of-session design that preserves interest without claiming a positive emotional state or requiring a streak.','An ending with a completed item seems the most likely way to leave a good next starting point; unfinished material initially looks like a liability.', '''Constructed state: a writer reports high current interest, medium energy, and 45 remaining minutes. Eight ready tasks: choose a title (easy/3), write a paragraph (hard/12), compare two endings (hard/10), copy a citation (easy/3), preserve a surprising phrase (easy/2), answer an open question (hard/10), record an unresolved contrast (medium/3), prepare the next entry point (easy/2). Total is 45 minutes; a recovery pause must displace something rather than be silently omitted.

Original rule products: quick win is preserving the phrase; hard work is placed while the actor reports interest rather than because a clock says “peak”; two hard tasks are separated by citation work; a small commitment is one paragraph rather than the whole project; visible progress is a paragraph and an explicit contrast; ending on a high is only a proposed design, not a measured outcome. A five-minute pause is allocated by dropping the ten-minute open-question answer and leaving five minutes slack.

Chosen sequence: phrase 0–2; paragraph 2–14; citation 14–17; pause 17–22; endings 22–32; title 32–35; unresolved contrast 35–38; next entry 38–40. The final five minutes are discretionary. The open question remains “Which ending changes the narrator’s role rather than merely the wording?” It is not relabeled as completed.

Eight endings compared: completed count; clear next action; strongest unresolved question; emotional self-rating; remembered surprise; prepared material; commitment to a fixed next duration; permission to stop. These yield different evidence. A clear question is available in text; a felt high requires the actor’s report; a future return requires observed behavior.

An empirical premise is bounded: intrinsic motivation is defined as doing an activity for its inherent satisfaction, while extrinsic aims concern separable outcomes; this distinction does not establish any effect of the proposed ending. [Ryan and Deci, original theoretical article](https://www.selfdeterminationtheory.org/SDT/documents/2000_RyanDeci_IntExtDefs.pdf)

Later application: a generated handoff retains the live narrator-role question and the last two candidate endings. It does not invent a promise that the writer will return enthusiastically. The content is ready; the motivational prediction remains pending.

Certificate: “unfinished material is necessarily a poor ending” is defeated by the constructed case where it is the clearest next entry. “This ending motivates return” still lacks an observed return. The two claims receive different dispositions.''','An unresolved question can function as a concrete next entry point; its effect on renewed interest is untested.','The next session has a specific starting object without a fabricated emotional-success claim.','UNRESOLVED','Content retains the difference between task completion and readiness to continue. Organization places next question next to its relevant candidates, with the delayed outcome left open.','Observe actual return behavior; compare ending with an answer versus a live contrast; test whether an open question becomes pressure for a particular person.',N+' Eight tasks, six ordering rules, eight end-state alternatives, a full sequence, and a later handoff.')
