from write_records import add,N

def table(headers,rows):return '| '+' | '.join(headers)+' |\n|'+'|'.join('---' for _ in headers)+'|\n'+'\n'.join('| '+' | '.join(map(str,r))+' |' for r in rows)

def pre(n,title,intent,start,pairs,prefs,opts,choice,comment,change):
 t=table(['Dimension','Scenario A: benefit / cost','Scenario B: benefit / cost','Selection and source'],pairs)
 # Match markers supplied per option, no invented psychometric score.
 scores=[sum(c=='✓' for c in marks) for _,marks,_ in opts]
 rows=[]
 for (name,marks,why),score in zip(opts,scores):
  rank=1+sum(s>score for s in scores)
  rows.append((name,*marks,f'{score}/5',rank,why))
 b=table(['Option',*prefs,'Known matches','Tier rank','Specific limitation'],rows)
 body=f'''Concrete domain: {title}. The two columns below are two concrete scenarios for every trade-off. They are design comparisons; no new human questionnaire is administered. Every recorded choice states whether it is supported by the supplied request or merely stipulated for this constructed case.

{t}

Selections and profile: {comment}

Strong task preferences: {', '.join(prefs)}. “Strong” describes explicit constraints or consistent stipulated selections, not estimated latent psychological traits. Unknown dimensions stay unknown. Context reversals are retained in the table rather than counted as inconsistency that needs correction.

Options are matched to this profile below. Fit uses number of known matches only; unknowns do not become failures, and a matching count is not a measurement of utility. Hard constraints remain binding regardless of count.

→ /boc invoked as choice validation with current choice “{choice}.” The exact boc original and separate receipt are preserved as values-boc.md and values-boc.receipt.txt. Commitment is provisional for this concrete application. The options span familiar, overlooked, hybrid, and non-obvious designs; omission from the request is not evidence that the user is unaware of them.

{b}

Better-option result: no option demonstrably dominates the current choice on these five declared criteria; equal-score variants have different unresolved costs. The full space is not literally exhausted—twenty candidates are the source minimum, not a proof of optimality. Three alternatives worth retaining for changed conditions are rows 6, 12, and 18. None is presented as a better match without the missing preference.

Settling check: no evidence of sunk cost, fear, social pressure, emotional attachment, or ignorance is available. Attributing one would invent a motive. The current choice sacrifices immediate brevity or convenience to the particular constraints listed; it does not prove the requester prefers every sacrifice in every setting. Recommendation: PROCEED provisionally with the current bounded option; no EXPLORE_ALTERNATIVES or RECONSIDER branch is activated, so boc does not require cta or another ve invocation here.

Subsequent application: a new candidate which meets four stated preferences but violates the fifth is compared with the current choice. Its higher aesthetic appeal does not change that missing requirement; the current choice is retained. This is an actual selection on supplied/constructed criteria. It does not collect the absent human selections or demonstrate increased motivation.

Certificate: the recorded choices support only the explicit or stipulated profile. The strongest contrary case is an unstated preference that reverses an equal-score comparison; that remains unresolved. The procedure’s real-user elicitation requirement is not falsely marked as collected.'''
 add('pre',n,title,intent,start,body,change,'Concrete preference and option comparisons exist; personal preference change and comparative human usability remain untested.','UNRESOLVED','The scenario and match tables preserve choice provenance. Content improvement requires actual selections when the unknown dimensions become action-relevant; additional scores cannot supply them.','Test one genuinely divergent unknown; compare a BOTH/NEITHER selection with a forced binary; check whether a new option meets all explicit constraints.',N+' Expanded to sixteen trade-off pairs with two concrete scenarios each, twenty-four matched options, complete boc choice-validation output, and one later comparison.')

pairs1=[
('Time/money','Spend 20 minutes checking one original; no extra service cost','Use an unverified one-minute summary; save time','A required for exact-source execution'),
('Risk/reward','Keep a narrow demonstrated inference; smaller claim','Promise general mind change; larger but unsupported claim','A by evidence constraint'),
('Control/convenience','Continue within fixed goal; less interruption','Ask approval before every reversible record; more control prompts','A by autonomy request'),
('Speed/quality','Write source-specific products; slower first document','Produce short generic essays; quicker completion','A by actual-procedure requirement'),
('Autonomy/security','Use judgment for reversible choices; some uncertainty','Wait for exact instructions for every case; less discretion','A explicitly requested'),
('Public/private','Keep task evidence local to authorized output','Publish evolving work immediately; more exposure','A; no publishing authority'),
('Breadth/depth','Use different targets across repeats; more context switches','Repeat one easy target in all records; greater familiarity','A by allocation purpose'),
('Now/later','Transfer a result before KEEP; later verdict','Award KEEP when recipe sounds useful; immediate count','A by benefit criterion'),
('Solo/team','Use assigned worker scope; clear ownership','Edit all lines jointly; uncertain ownership','A by working instruction'),
('Scale/craft','Fifty substantive applications; larger corpus','One polished essay; simpler artifact','A required scope'),
('Interest/use','Retain an interesting dead end without success credit','Delete every unproductive tangent; smaller log','A by exploration coverage'),
('Detail/retrieval','Full record plus linked compact entry','One summary replaces all details','A by consolidation-01'),
('Certainty/scope','Mark human effects unobserved','Infer human change from generated text','A evidence constraint'),
('Novelty/repetition','New targets with reused kept distinctions','Treat same correction as another KEEP','A no duplicate credit'),
('Original/endorsement','Keep exact source and qualify doubtful facts','Normalize original to appear factually settled','A source integrity'),
('Clarification/substitution','Keep original broad goal; use a different method','Replace goal with easy mood improvement','A current premise')]
opts1=[('Linked original records and trigger index','✓✓✓✓✓','Current choice; retrieval costs not yet measured'),('One long narrative','✓✓~✗✓','Weak retrieval boundaries'),('Single motivational essay','✗✗✓✓~','Fails procedure and coverage'),('Checklist only','✗✗✓✓~','Lacks products'),('Unlinked files','✓✓✓~✓','Provenance recovery slower'),('Chronology plus sources','✓✓✓~✓','Sequence clear; trigger lookup indirect'),('Theme tags only','~✓✓✓~','Drops exceptions'),('Twenty repeated easy cases','✓✗✓✓~','Insufficient target diversity'),('Human outcome scorecard','~✓~✓✗','Outcomes absent'),('Daily approval queue','✓✓✗✗✓','Unneeded interruptions'),('Fully automated prose templates','✗~✓✓~','Source operations displaced'),('Two-tier record and index','✓✓✓✓✓','Equal match; effectively same current arrangement'),('Graph of every sentence','✓✓✓✗✓','Excess structure'),('One-page claim registry','~✓✓✓✓','Some procedure products lost'),('Only KEEP records','~✗✓✓✗','Hides negative evidence'),('Only source archive','✓✗✓✓✗','No execution'),('Open exploratory notebook','~✓✓~✓','Source fidelity uncertain'),('Decision-first index plus chronology','✓✓✓✓✓','Equal-match presentation variant'),('User questionnaire before each record','✓✓✗✗✓','Information often not action-relevant'),('Source-receipt bundle alone','✓✗✓✓✓','Faithful bytes not applications'),('Case matrix without sources','✗✓✓✓✓','Fidelity uncheckable'),('Sequential forced-action program','~✓✗✓~','Substitutes action for broad change'),('Comparison ledger with record links','✓✓✓✓✓','Equal match; differs in entry key'),('Adaptive scope reduction','✓✗✓✓✓','Requires changed goal')]
pre(1,'Preference dimensions of the current research workflow','Identify which workflow choices are settled by the supplied request and which remain unelicited.','The user’s broad requirements already favor faithful autonomous work; a preference questionnaire may add little unless it reveals a genuine trade-off.',pairs1,['Fidelity','Breadth','Autonomy','Efficient reuse','Evidence'],opts1,'Linked original records and trigger index','The first sixteen choices are supported by explicit task constraints, not newly collected user answers. Preference strength outside this task is unknown. The detailed record versus compact index choice is context-dependent: discovery uses the record, reuse uses the index.','The explicit task profile is sharper, but no new personal preferences were elicited and the current workflow remains selected.')
pairs2=[
('Time/money','Use free 30-minute sketch walk; costs time','Buy ready-made prompts; saves 20 minutes','A stipulated'),('Risk/reward','Repeat known exercise; reliable finish','Try unfamiliar medium; chance of an interesting failure','B stipulated'),('Control/convenience','Choose own subject; prepare materials','Follow an instructor’s exact subject; ready setup','A stipulated'),('Speed/quality','Make rough studies in 20 minutes','Polish one study for two hours','A on workdays; B on a free weekend'),('Autonomy/security','Self-selected route; uncertain result','Graded sequence; clear credential','A stipulated'),('Public/private','Post every draft; visible feedback','Keep drafts private; less response','B stipulated'),('Breadth/depth','Try three textures; less depth','Study one texture; deeper familiarity','A now; B after a compelling discovery'),('Now/later','Immediate sensory experiment','Build a portfolio for next year','A stipulated'),('Solo/team','Sketch alone at chosen pace','Group assignment at a fixed pace','A stipulated'),('Scale/craft','Ten rough objects','One carefully observed object','B stipulated'),('Interest/use','Follow a strange shadow','Choose a marketable subject','A stipulated'),('Feedback/independence','Ask feedback only on chosen question','Receive full rubric on every draft','A stipulated'),('Novelty/familiarity','New contour method','Comfortable repeated scene','A stipulated'),('Challenge/ease','One difficult feature','Only easy outlines','A if optional; otherwise decline'),('Record/flow','One sentence after experiment','Continuous time log','A stipulated'),('Rest/progress','Stop at selected time even unfinished','Finish to preserve streak','A stipulated')]
opts2=[('Private optional object study','✓✓✓✓✓','Current case choice'),('Graded public drawing course','✗✗~✓✗','Fixed evaluation and exposure'),('Ten daily social posts','~✗✓✗✗','Volume displaces one object'),('Copy one familiar scene','✓✓✗✓✓','Little novelty'),('Marketable portfolio brief','~✓~✓~','Instrumental priority differs'),('Private field notebook','✓✓✓✓✓','Equal match; portability unknown'),('Partner-directed theme','✗✓✓✓~','Subject control lower'),('Random medium lottery','~✓✓~✓','Randomness can override refusal'),('Museum visit with sketch option','✓✓✓~✓','One-object focus unknown'),('Strict two-hour mastery block','~✓~✓✗','Hard ending rule violated'),('No-record free play','✓✓✓~✓','Observation capture absent'),('Optional three-texture lab','✓✓✓~✓','Breadth versus object depth unresolved'),('Public critique circle','~✗✓✓~','Exposure not selected'),('Private audio observation','✓✓✓✓✓','Equal match if drawing not required'),('Rewarded completion challenge','~✓~✓✗','Completion obligation added'),('Quiet copying hour','✓✓✗✓✓','Novelty unmet'),('Self-chosen hard detail','✓✓✓✓✓','Equal match; a component of current choice'),('Shadow study outdoors','✓✓✓✓✓','Equal match; weather logistics unknown'),('Prescribed mindful exercise','✗✓~✓~','Prescribed frame'),('Commercial contest','~✗✓✓✗','External success pressure'),('Object study with opt-in feedback','✓✓✓✓✓','Equal match if feedback unwanted remains off'),('Anonymous gallery archive','✓~✓✓~','Publication remains ambiguous'),('Skill badge program','~✓~✓✗','Adds unselected credential aim'),('Shared silent studio','✓~✓✓~','Social environment unknown')]
pre(2,'A constructed curiosity practice','Expose how concrete context changes a supposed general preference for novelty or depth.','The constructed learner seems novelty-seeking; I would otherwise use one global preference score to choose a practice.',pairs2,['Subject control','Privacy','Novelty','Close observation','Optional ending'],opts2,'Private optional object study','All selections are stipulated for a synthetic learner. Strong case preferences repeat across several choices. Depth depends on having found an object worth studying; polish depends on available free time. Unknowns include accessibility, materials, and any real person’s reactions.','The synthetic profile is context-dependent, but no actual person’s interest or follow-through is observed.')
pairs3=[
('Time/money','Write brief review comments in 15 minutes','Purchase scoring software; save manual time','A stipulated budget'),('Risk/reward','State only checked discrepancy','Offer speculative motive diagnosis','A stipulated'),('Control/convenience','Recipient chooses repair method','Reviewer dictates every step','A stipulated'),('Speed/quality','Correct active decision number now','Wait for a polished full report','A if decision active; B otherwise'),('Autonomy/security','Ask once for response context','Require agreement before recording discrepancy','A stipulated'),('Public/private','Private draft feedback first','Public critique before author sees it','A unless public reliance is active'),('Breadth/depth','Review all formatting details','Review the one load-bearing calculation','B stipulated'),('Now/later','Correct today’s decision input','Build broad feedback culture over months','A for current case; B remains additional'),('Solo/team','Author revises with documented review','Committee edits every line','A stipulated'),('Scale/craft','Reusable comment labels','Specific numerator/denominator example','B stipulated'),('Warmth/precision','Kind direct correction','Comforting vague praise','A stipulated'),('Certainty/inquiry','Claim a motive for error','Ask whether exclusion rule is missing','B stipulated'),('Feedback/ownership','Recommend a fix with author choice','Rewrite without informing author','A stipulated'),('Visibility/blame','Record chart correction provenance','Name author as careless','A stipulated'),('Agreement/accuracy','Invite contrary calculation','Demand acknowledgement of fault','A stipulated'),('Followup/pressure','Check next relevant chart','Daily personal reminders','A stipulated')]
opts3=[('Specific private correction with reliance exception','✓✓✓✓✓','Current case choice'),('Public character critique','~✗✗✓✗','Motive and blame'),('Generic praise sandwich','✗✓~✗~','Calculation obscured'),('Rewrite without notice','✓✗✗✓~','Ownership bypassed'),('Wait for full consensus','~✓✓✗~','Decision urgency unmet'),('Annotated calculation','✓✓✓✓✓','Equal match if audience appropriate'),('No feedback','✗✓✓✗~','Known discrepancy retained'),('Anonymous accusation','~✗~✓✗','Uncheckable attribution'),('Rubric score only','✗~✓✓~','Specific defect absent'),('Private question with evidence','✓✓✓✓✓','Equal match; active reliance still needs mark'),('Public uncertainty flag only','~✓✓✓✓','Partial correction'),('Corrected chart with change note','✓✓✓✓✓','Equal match if author involvement retained'),('Motivational coaching','✗~✓✗~','Wrong problem scope'),('Automated daily nags','~✗✗~~','Unselected pressure'),('Group retrospective','~✓✓~✓','Timing fit unresolved'),('One-line denominator note','✓✓✓✓✓','Equal match when context sufficient'),('Peer asks for hidden motives','✗✗~✗✗','Unsupported inference'),('Author-led fix plus check','✓✓✓✓✓','Equal match; supported variant'),('Private praise only','✗✓✓✗~','Accuracy not addressed'),('Rewrite style guide','✗~✓✗✓','Unrelated remedy'),('Evidence-linked dissent note','✓✓✓✓✓','Equal match if discrepancy unsettled'),('Mandatory apology request','✗✗✗~✗','Confession substituted for correction'),('Training assignment before correction','~~✗✗~','Active input delayed'),('Corrected decision memo','✓✓~✓✓','Author choice unclear')]
pre(3,'A constructed feedback choice','Find whether a concrete feedback menu helps preserve accuracy, ownership, and timing simultaneously.','The specific private correction already appears preferable; option expansion might reveal a better fit, but an unobserved motive should not drive that search.',pairs3,['Accurate issue','Respectful attribution','Recipient choice','Timely correction','Traceable evidence'],opts3,'Specific private correction with reliance exception','All scenario choices are stipulated. The private/public choice changes when active group reliance begins; it is not a universal privacy preference. No real recipient approved, received, or reacted to a draft.','Expanded options reveal several equal-match variants; the current design is retained, and any interpersonal advantage remains untested.')
