import json,sys
from write_records import ROOT,put,refresh
put('consolidation-06','Retain the latest four useful changes in an arrangement that selects the next permissible action.','The last four kept results concern a minimum constraint change, a repaired active graph, stopping a settled proof branch, and truthful execution counts. A simple list would lose which of these controls the next operation.', '''Only the existing KEEP findings memk-01, fr-01, enough-02 and pt-01 enter this consolidation; earlier keeps remain available with their original limits.

| Question at the next decision | Kept answer and evidence | Operational consequence |
|---|---|---|
| What smallest declared change makes this finite case feasible? | memk-01: A needs deadline at least 7; lower bound plus B1–2, C2–4, A4–7 witness | Change A's deadline from 6 to 7 if that variable is permitted |
| Which graph now governs readiness? | fr-01: the final eleven-edge graph puts D before E; old joint readiness was stale | Use the regenerated active rounds, not the superseded graph |
| Would more enumeration change this exact settled answer? | enough-02: necessity and witness already establish the minimum | Stop that branch; invest in a different unresolved target |
| Which written applications still lack required stages? | pt-01: actual ledger has separate complete, partial, blocked and pending fields | Select by executable gate; do not infer completion from a verdict |

Organization comparison: chronological notes show how the graph repair happened but do not expose its active consequence. A list of successes fails to distinguish a finite mathematical result from a corrected progress field. A next-decision table links each different useful result to its controlling evidence and allowed action. It is selected for the final progress application and the methods handoff: leave the proven finite schedule intact, use the current graph, avoid repeating the settled enumeration, and preserve human-rating gates.

Immediate use: pt-02 reports observed response accuracy separately from original practice execution; the assigned ADEp application will not treat the agent's own rating as an observed user's rating. The latter is a use of the existing actor/scope gate, not an additional consolidated discovery. No REJECT or UNRESOLVED finding is promoted here.''','The conditions agent changed the handoff organization from a flat list of kept outcomes to questions that select the next permissible operation.','The four retained changes stay usable without merging their very different scopes or counting the consolidation as another experimental success.','KEEP','The next-decision table is chosen over chronology alone and a successes list, with actual uses in pt-02 and the assigned handoff.','Check the final execution counts; distinguish practice participation from observed task performance; preserve the original active graph and finite lower-bound result when integrating.')
put('pt-02','Determine whether the observed practice results warrant marking learning progress as complete or changing the current capability estimate.','The agent has one recorded fresh-task response and sixteen later correct finite-case predictions, all with same-session context and author/solver overlap. The current working conclusion is supported finite performance, with durable learning and human progress unresolved. I expect a progress report to preserve that conclusion unless a new measure supports change.', '''Interpretation 3: prepare a status report for the capability/practice line. The target differs from pt-01's status-schema repair: measure the actual learning evidence, performance and missing practice conditions. Consolidation-06 selects this scope and excludes repeated enumeration of the already settled lower bound.

1. Data collection. Inputs are fresh-task-attempt.json, fresh-task-feedback.json, practice-predictions.json, practice-feedback.json and the original ska/dlp/acr/spr/memy records. The fresh attempt was saved before computed feedback but the same agent authored the stimulus, which included a suggestive prompt; aid-free novelty is not established. Six permutations in the independent comparator found no feasible schedule, consistent with the recorded answer. Sixteen predictions were saved before the later comparator and all sixteen matched. Time spent on complete original warmup, practice, integration and recovery cycles was not recorded as performed. No human exposure, bodily action, sleep interval or later-session retention measure exists.

2. Metrics. Finite supported prediction agreement is 16/16 = 100%. This exceeds the dlp original's 70–85% working success band for an appropriately challenging practice block, so this block cannot be evidence that difficulty was calibrated into that band. The source's band is used as a procedure target, not asserted as a scientifically universal optimum. One initial diagnosis matches the exhaustive comparator. There is no pre/post durable capability denominator: there is no valid independent held-out baseline, closed context or later occasion. Improvement percentage, retention rate, generalization probability, completed timed-session count beyond zero, and human benefit cannot be computed from these files. No time/cost forecast is inferred from accuracy.

3. Dashboard.

| Dimension | Observed measure | Meaning for progress |
|---|---|---|
| Initial finite answer | Infeasibility response agrees with six-order comparator | Current aided task result supported |
| Later finite variants | 16/16 predictions agree | Supported performance on declared variants |
| Challenge calibration | 100%, outside source's target band | Does not demonstrate target-band calibration |
| Full timed practice | Not performed as prescribed | Original procedure partial |
| Closed-material recall | Not demonstrable for this agent context | Unaided retrieval claim unavailable |
| Later retention | No later-session observation | No retention rate |
| Human action/access | No human encounter observed | No human capability or benefit claim |
| Durable model change | No weights update or independent later-context test | No such claim |

4. Blockers. First priority is missing target-specific independent measurement: owner would be an actual later test participant/evaluator, action define and conduct the encounter if authorized, target event a real separate attempt, open. Physical motor practice owner would be a participating person, action actual baseline and timed cycle, no date fabricated, open. Spaced retrieval owner future authorized continuation, action elapsed intervals after actual exposure, open. The agent can close the reporting task now; it cannot make these events occur by rewriting the report. Parent receives these gates; no unsolicited reminders or outside messages are created.

5. Variance. The block produces correct answers but falls outside the planned challenge range. That supports the specific conclusion 'these cases did not calibrate difficulty as required.' It does not identify why: prior knowledge, task design, exposure and ease are not experimentally separated. The fifty-slot allocation remains fixed; the source-stage gap is preserved instead of redefining a complete learning cycle as a correct response.

6. Parent report. Agent finite performance is supported; general improvement is unresolved. The reports are usable as conditions on further work: define an independent target, conduct actual exposure/practice where possible, preserve response before feedback, and revisit after a real interval. The existing task data do not justify reporting a learned human habit or durable model skill.

7. Communication and follow-up. This file and the corrected ledger are delivered to the parent as the integration payload. The next assigned work uses the same limit for ADEp's user-rating calibration. Actual future ratings are required to close that particular calibration stage; the agent cannot supply them by self-scoring.

8. Baseline/forecast. Keep the original application quotas and the actual response artifacts. No retrospective blind baseline is invented. Full learning completion has no defensible date while participant and later-occasion inputs are absent. The remaining local status is 'all currently executable conditions work addressed', with per-application partial gates retained. This reporting task completes without changing the already bounded capability conclusion.''','No new capability conclusion was warranted. The conditions agent retained the pre-existing distinction between supported finite performance and unmeasured durable learning after the actual metric audit.','The report is useful for handoff and prevents an inflated learning claim, but repeating the already adopted boundary earns no new useful-change credit.','REJECT','A dimension-by-evidence dashboard answers the learning question better than a raw success count or writing chronology. Consolidation-06 supplies the controlling scope; the same gate is used in the assigned ADEp calibration.','Attempt a genuinely independent changed input if available; conduct actual delayed retrieval only in a real later encounter; use participant-provided ratings rather than agent self-ratings for ADEp.','No numerical 8x scale in the original. All eight stages are applied to actual performance records, with eight distinct dimensions and explicit unavailable temporal, cost and human measures; this is not a claim of eightfold empirical practice.')
refresh()
