from write_support import *
def araw(n,roots,deep,tests,crux,synthesis):
 body='Original source: ../sources/methods-araw.original.md; separate requirements: ../sources/methods-araw.requirements.txt.\n\nActor: present model evaluating proposed changes to its own working artifacts. Self-evaluation is not independent confirmation. Compensating evidence consists of explicit countercases, live artifact checks and a preserved no-change boundary; human effects remain unknown.\n\nMeta-ARAW: the exact input is the critical candidate set emerging from GG-'+f'{n:02}'+' and QAG. These are design/analytical claims with truth-evaluable scope. Uncertainty concerns representation adequacy, causal attribution and available operations. Source text and prior parent findings were already read and are marked imported context; the new conditional constructions and live tests below are not copied source verdicts. The C-claims below freeze the analytical hypotheses. An initial fixture inspection preceded this formal record, so it is not a pristine prospective experiment. The same explicit tests are run again after the claims are frozen; source-derived conclusions remain imported and do not count toward independent findings. No source-naive first pass is claimed.\n\nAll roots are analytical candidate propositions; historical source facts are verified in the observation file and do not count as exploratory findings. VOI is HIGH for C1–C8 (they change the operation), MEDIUM for C9–C18 (they change scope or cost). Blind-spot perspectives include later reader, source author and a current user with no need for extra structure.\n\nPHASE 1 — EXPLORATION\n\n'
 regs=[];f=1
 for i,(claim,ar,aw,alternative,altcon,boundary,verdict,certificate) in enumerate(roots,1):
  body+=f'C{i}: {claim} [explicit design candidate; analytical; VOI {"HIGH" if i<=8 else "MEDIUM"}].\n'
  ids=[]
  for typ,txt in [('AR implication',ar),('AW same-scope countercase',aw),('Alternative from preceding AW',alternative),('AR of derived alternative',altcon),('AW/boundary of alternative',boundary)]:
   id=f'F{f}';ids.append(id);body+=f'- {id} ({typ}): {txt}\n';regs.append((id,f'C{i}' if len(ids)<3 else ids[-2],typ,txt));f+=1
  body+='\n'
 body+='Deep recursion on the most load-bearing candidate. Each numbered edge states its actual parent. Contradictory assumption branches remain hypothetical; failed branches are not used as evidence for a later verdict.\n\n'
 for parent,typ,txt in deep:
  id=f'F{f}';parent=parent.replace('PREV',f'F{f-1}').replace('PREV2',f'F{f-2}')
  body+=f'- {id} ← {parent} [{typ}]: {txt}\n';regs.append((id,parent,typ,txt));f+=1
 body+='\nLive tests executed (not merely proposed):\n\n'+tests+'\n\nPHASE 2 — FINDING REGISTRY\n\n'
 body+='All ninety root-branch findings and the deep-branch findings are retained verbatim in Phase 1. This registry indexes every product without importing additional conclusions.\n\n'+table(['Root','AR','AW','Alternative + test','Verdict','Compact certificate'],[[f'C{i}',f'F{5*(i-1)+1}',f'F{5*(i-1)+2}',f'F{5*(i-1)+3}–F{5*i}',r[6],r[7]] for i,r in enumerate(roots,1)])+'\n\nDeep registry: '+', '.join(f'{x[0]} parent={x[1]} type={x[2]}' for x in regs[90:])+'.\n\nCRUX points:\n\n'+ '\n'.join(f'{i+1}. {v}' for i,v in enumerate(crux))+'\n\nTotals: eighteen analytical claims; '+str(len(regs))+' numbered findings; eight CRUX points; at least two live tests; a recursive parent-child path longer than six edges. Original 8x floors are met. The important rejected claims concern the adequacy of the proposed core artifact and inference, not merely cosmetic peripherals. Imported parent conclusions are not counted as new findings.\n\nPHASE 3 — SYNTHESIS\n\n'+synthesis+'\n\nEvery C1–C18 verdict is represented in the complete registry; no new claim is introduced in this synthesis. A source’s prior self-assessment is not the evaluated object; new candidate universal claims are. Disagreement is tested against their exact predicates rather than forced to meet a rejection percentage.'
 text='Intended mind change: Test whether the concrete GG candidate operations deserve endorsement within their exact scope.\n\nActual starting judgment: The candidates look plausible enough to try, but the strong adequacy and transfer claims remain open; the parent’s already-established distinctions are not new benefits.\n\n'+body+'\n\nActual mind change: Several universal adequacy and transfer claims are rejected; the narrower artifact operations remain available under the conditions in the registry.\n\nBenefit: The live tests change what the model endorses and what remains unresolved. They establish only the displayed current artifact behavior and finite logical cases.\n\nVerdict: UNRESOLVED\n\nOrganization: Exploration products, complete verdict registry, CRUX dependencies and synthesis remain separately accessible. No new KEEP credit is assigned to this shared dependency.\n\nNext attempts: Use a surviving artifact on a different exact input; test the strongest retained boundary; obtain an actual later-session or human observation before claiming those effects.\n'
 (D/f'gg-{n:02}-araw.md').write_text(text)
