from pathlib import Path
import json,sys,importlib.util
p=Path(__file__).with_name('conditions-handoff-write.py');sp=importlib.util.spec_from_file_location('hw',p);hw=importlib.util.module_from_spec(sp);sp.loader.exec_module(hw);put=hw.put;ROOT=hw.ROOT
cases=json.loads((ROOT.parent/'conditions/practice-predictions.json').read_text())['cases']
roles={
 'P01':('wait-for-tight-future-job','P01'),'P02':('restrict-A-deadline','P02'),'P03':('shorten-A','P11'),'P04':('fit-A-before-release','P04'),'P05':('wait-for-tight-future-job','P01'),'P06':('three-job-forced-infeasibility','P06'),'P07':('relax-A-deadline','P07'),'P08':('relax-C-deadline-no-repair','P08'),'P09':('earlier-release-no-repair','P09'),'P10':('earlier-release-no-repair','P09'),'P11':('shorten-A','P11'),'P12':('shorten-C','P12'),'P13':('common-release-feasible','P13'),'P14':('common-release-overload','P14'),'P15':('fit-A-before-release','P04'),'P16':('restrict-A-deadline','P02')}
selected=[x for x in cases if roles[x['id']][1]==x['id']]
allroles={v[0] for v in roles.values()};selroles={roles[x['id']][0] for x in selected};assert allroles==selroles and len(selected)==11
artifact={'purpose':'Optional later re-exposure selection only; frozen fifty conditions applications and all historical responses retained','actor':'conditions subagent','original_count':16,'selected_count':11,'reduction_percent':31.25,'comparison_unit':'Declared diagnostic role, not interchangeable human learning effect','coverage_preserved':sorted(allroles),'selected_cases':selected,'mapped_cases':[{'id':k,'role':v[0],'representative':v[1]} for k,v in roles.items()]}
(ROOT/'conditions-handoff-satr-practice-selection.json').write_text(json.dumps(artifact,indent=2)+'\n')
rows='\n'.join(f"| {x['id']} | {roles[x['id']][0]} | {'Feasible' if x['agent_prediction_feasible'] else 'Infeasible'} | LOW: one recorded prediction/comparison | {roles[x['id']][1]} |" for x in cases)
put('satr-01','Change which finite scheduling items would be repeated in an optional later practice block while preserving every required 3/2/1 exposure.','The sixteen prior practice cases all returned correct supported predictions. If asked for another block, I would initially retain all sixteen to avoid losing coverage. I have not yet compared their diagnostic roles for a later repetition.',f'''AREA: optional later re-exposure to the sixteen existing deterministic queue cases. BELONGS TO: scheduling practice and changed-case capability checks. SATURATION SIGNAL: several cases alter a number while preserving the same controlling constraint. This application does not prune source skills, historical evidence or the frozen quotas.

The complete existing inventory follows. A LOW label refers only to the recorded in-session usage log: each item has one prediction and one comparator result, with no logged later attempt. It is not evidence of rare human use.

| Item | Diagnostic role for this selection | Existing answer | Observed usage | Selected representative |
|---|---|---|---|---|
{rows}

COUNT: 16. An initial six-case expectation, based only on two-job/three-job plus feasible/infeasible distinctions, gives 16/6 = 2.667. That expectation omits different effective and ineffective interventions. The explicit role inventory requires eleven representatives here, giving 16/11 = 1.455. The source's 1.5 ratio is a heuristic supplied by the source, not empirical evidence of a universal saturation boundary. The role comparison, rather than the arbitrary first expected count, settles this particular selection.

Redundancy clusters for this later question: P01/P05 both reserve a tight future B interval; P02/P16 both lose feasibility because A cannot fit before or after the required B interval within its deadline; P03/P11 both restore feasibility by shortening A; P04/P15 both fit A before B's release; P09/P10 both fail to repair the three-job schedule through an earlier release alone. Ten of sixteen items overlap with another on the declared role: 62.5%. This does not assert equality of their full inputs or learning effects. P06, P07, P08, P12, P13 and P14 retain unique roles in this inventory.

The strongest objection to suppressing P03 in favor of P11 is that a two-job duration repair can be easier than the three-job version and useful for transfer. That objection defeats a claim of educational equivalence, which is not made. It does not defeat preserving the declared role coverage in a small optional re-exposure selection; P03 remains in the archive and can return when two-versus-three-job transfer is the target.

CONSOLIDATE only the next-use representative list: choose P01, P02, P04, P06, P07, P08, P09, P11, P12, P13 and P14. PRUNE from that optional next-use list only P03, P05, P10, P15 and P16. KEEP every historical input, response and feedback. Result: 16 → 11 proposed repeat items, 31.25% fewer, with all eleven declared diagnostic roles present. The actual selected queue and role-to-representative map are saved in conditions-handoff-satr-practice-selection.json; a set comparison confirms coverage of these declared roles. No elapsed-time saving or learning superiority is observed.

Usage/cost: the five suppressed items would add five repeat decisions and their feedback checks if the block were executed. Actual minutes and human maintenance burden are unknown. The already completed sixteen-item block remains exactly as recorded. Subsequent selection uses this queue as a boundary against further repeats and makes room for the new setup-cost/contiguous-service cases in uf-01 and boc-01.''','The conditions agent replaced its all-sixteen optional repeat list with an eleven-item representative queue, retaining all declared intervention roles and all historical evidence.','Five future repetitions are removed from this particular planned selection without losing the eleven explicit roles. This is a demonstrated selection/artifact change; learning equivalence and human time savings are unresolved.','KEEP','The diagnostic-role → representative → exact-input arrangement preserves more action-relevant differences than grouping only by feasible/infeasible or by source order. The reduced queue is used to select different setup and service-continuity cases for uf-01 and boc-01.','Compare contiguous service with time slicing; compare setup batches under hard deadlines; restore suppressed two-job items only if two-versus-three-job transfer becomes the actual target.','No numerical 8x floor in SATR. All five original stages cover all sixteen actual inputs, exact usage limits, five overlap clusters, six unique roles, expected-count sensitivity and a performed later-queue transformation.',later_use='uf-01 and boc-01 use new service-continuity/setup cases rather than repeating the suppressed role-equivalent queue items.')
index=json.loads((ROOT.parent/'conditions/retrieval-index.json').read_text());used={r['query'] for r in json.loads((ROOT.parent/'conditions/retrieval-results.json').read_text())}
rows='\n'.join(f"| {x['id']} | {x['question']} | {'LOW: one exact-key lookup' if x['id'] in used else 'NEVER in the recorded four-query log'} | {x['exception']} |" for x in index)
put('satr-02','Determine whether the eight retrieval cues can be reduced without removing a distinct condition for action.','The cue index contains superficially related pairs about windows, scheduling and prerequisites. Those similarities invite a smaller index, but the current arrangement already ties each cue to a different operational question. I do not yet have evidence that any is dispensable.',f'''AREA: the existing eight external retrieval cues, with particular attention to the apparent overlap of access/time conditions. BELONGS TO: immediate external-memory support. SATURATION SIGNAL: shared words such as window, before and schedule. The object is later cue selection, not the fixed exposure quota.

| Existing item | Purpose | Logged usage | Boundary that must survive |
|---|---|---|---|
{rows}

TOTAL COUNT: 8. EXPECTED COUNT under the actual next-use question inventory: 8 distinct conditions. RATIO: 1.0. No external population benchmark exists for the proper number of cues; this is a coverage-derived count for this exact index.

Candidate cluster A, continuous-window/location-window: the first compares one uninterrupted duration against the largest usable block; the second adds travel, setup, cleanup and buffer before an access deadline. A 12-minute task in 6/6/10 fails the first. A 20-minute task in a 30-minute room window fails the second when travel5+setup4+cleanup2 gives31. Merging into 'find enough time' loses which arithmetic to perform.

Candidate cluster B, future-release/deadline-before-mean: the first reserves a known future nonpreemptive interval; the second chooses deadlines over average wait among currently available tasks. The two-job release1 case changes whether the processor should be idle; the all-release0 four-job case changes which ready job goes first. Same scheduling vocabulary, different action.

Candidate cluster C, offline-material/baseline-exposure/criterion-first: acquiring readable content before losing network access, recording an unexposed baseline before exposure, and precommitting a changed test before feedback protect different required states. Offline possession does not establish a baseline; a baseline does not fix the later comparator; comparator precommitment does not provide a readable file.

Shared-resource is unique: logical independence can coexist with an unsafe common overwrite. No other cue supplies that resource constraint. Operational redundancy rate after those comparisons: 0/8 on the specified questions. Surface-word overlap is not counted as functional duplication.

LOW usage applies to four exact-key lookups; the other four are NEVER only within that finite four-query log. No actual human cue-use history exists. The strongest pruning argument is that the unqueried entries have not yet earned repeated use. It does not show that their action roles are redundant, and deleting them would remove explicit answers for four currently defined questions. Keeping eight short entries has unknown human review cost; no invented minutes are assigned.

CONSOLIDATE: none. PRUNE: none. KEEP AS-IS: all eight, with answer, exception and source intact. RESULT: 8 → 8, 0% reduction. The index remains unchanged. This does not rerun memy or claim delayed retention. SATR-01's narrower repeat list does not license pruning this different resource.''','The attempted reduction failed: no operationally redundant cue was found, so the conditions agent retained the eight-entry index.','The comparison protects distinct action conditions, but it repeats the already useful arrangement and earns no new useful-change credit.','REJECT','Question → answer → exception → source remains preferable to three broad labels (time, order, memory), because the latter cannot select the observed different operations.','Observe actual later cue use if available; test a cue whose answer fails on a changed access condition; distinguish deleting a cue from reducing repeated practice prompts.','No numerical 8x floor. All five stages cover all eight actual cues, three tested overlap clusters, the exact finite usage log and an explicit no-pruning decision.',later_use='uf-01 preserves separate release, dependency, access and resource switch conditions rather than merging them into one scheduling label.')
