from write_support import *
from itertools import combinations

def foht(name,intent,start,input_text,criteria,methods,synthesis,change,benefit,verdict,later):
 f=1; registry=[]
 def add(kind,txt):
  nonlocal f
  k=f'H{f}';f+=1;registry.append(f'{k} [{kind}] {txt}');return k
 for c in criteria:add('criterion/constraint',c)
 mapped=[]
 for m in methods:
  label,origin,pre,*rest=m
  mi=add('method',f'{label}; discovery source: {origin}.');pi=add('prerequisite',f'{mi}: {pre}.');mapped.append((mi,pi,label,rest))
 out=[]
 for mi,pi,label,rest in mapped:
  if len(rest)==1:
   vi=add('blocked finding',f'{mi}: {rest[0]}');out.append([mi,label,'BLOCKED',pi,vi]);continue
  ar,deep,fore,aw1,d1,aw2,d2,alt,edge,v=rest
  ids=[add(kind,f'{mi}: {txt}') for kind,txt in [('AR consequence',ar),('AR further implication',deep),('foreclosed',fore),('AW countercase',aw1),('AW consequence/bedrock',d1),('AW second countercase',aw2),('AW second consequence/bedrock',d2),('derived alternative',alt),('edge/cost',edge)]]
  vi=add('verdict',f'{mi} {v}; AR {ids[0]},{ids[1]}; AW {ids[3]}–{ids[6]}; prerequisite {pi}; alternative {ids[7]}; edge {ids[8]}.');out.append([mi,label,v,pi,vi])
 body=f'''Corruption check: no praise or audience agreement is used as evidence. Verdicts distinguish viable, conditional, eliminated and blocked; the user's desired program does not make every method effective. Findings are scoped to exact constructed records.

INPUT: {input_text}

{chr(10).join(registry)}

METHOD REGISTRY INDEX (all discovery, prerequisites, tests and edges are preserved above):

'''+table(['Method finding','Name','Verdict','Prerequisite','Verdict evidence'],out)+f'''

Totals: 15 methods found before testing; 15 prerequisites surfaced (12 met for symbolic testing, 3 absent); 12 methods tested, each with AR, further implication, foreclosure, two distinct AW countercases with consequences, an alternative derived from those countercases, and explicit edge/cost; {f-1} numbered findings. The registry contains every exploration product; it is not a substituted summary of absent analysis.

SYNTHESIS (only from registry and supplied input): {synthesis}

Actual later application: {later}
'''
 record(name,intent,start,body,change,benefit,verdict,'The exact input, result and conditional method index are the retrieval surface; the numbered registry retains countercases and provenance. No claim of universal optimal organization.', 'Apply the surviving method on a different input; test the explicit boundary; retain an unresolved result when prerequisites are absent.',depth=f'Original 8x floors met: 15 methods, 12 tested, 15 prerequisites, {f-1} numbered findings. All tests and surviving-method edges are actual products below.')

m2=[
('Word diff','direct','exact A/B labels available','Finds gather wording and moved power.','A reviewer can locate every supplied lexical edit.','Does not assign causal significance to word count.','Synonym-only gather edit changes text without changing action identity.','A large lexical edit need not violate check-before-start.','A single moved start in B2 violates the declared prerequisite.','Small edit size can be consequential.','Keep words, then test declared relations.','Long labels can dominate the visible diff although order is unchanged.','CONDITIONAL'),
('Position-by-position action comparison','direct','both six-action sequences available','B differs at positions 2–4.','It bounds where order changed in the exact sequence.','Does not tell whether connect/power has a physical dependency.','An inserted harmless annotation shifts every later position.','Position mismatch overstates action-order change when item alignment is lost.','Same positions can contain paraphrased actions with different semantics.','Index equality alone is not action identity.','Align action identities before comparing positions.','Repeated action names make alignment ambiguous.','CONDITIONAL'),
('Bag-of-actions comparison','direct','action names available','A and B contain the same actions.','No action was added or removed in this input.','Order information is discarded.','B2 has the same bag but starts before check.','The mandatory condition is violated despite bag equality.','Duplicating check changes multiplicity but may still omit a successful check.','A count does not establish event outcome.','Use bag only to detect inventory changes, then validate order/outcome.','Cannot answer sequencing or causality.','ELIMINATED'),
('Typed relation projection','category','lexical, precedence and declared-prerequisite classes available','B changes two precedence pairs while preserving check-before-start.','It produces a bounded answer without inventing device physics.','Undeclared physical validity remains unanswered.','If connect-before-power is later supplied as mandatory, B becomes invalid.','The result depends on the rule set; current unresolved status is not safe-device certification.','If a paraphrase changes action identity, retained identity mapping may be false.','The projection must preserve source wording to revisit mapping.','Store exact text plus typed relations and rule version.','At larger scale relation count grows quadratically; retain relevant predicate queries.','VIABLE'),
('Counterexample construction','inversion','one declared prerequisite available','B2 demonstrates start-before-check failure.','A validator accepting B2 is incomplete for the stated condition.','A counterexample rejects a claim; it does not certify every remaining instruction.','A physical cable/power failure cannot be constructed as fact from absent specifications.','A hypothetical device rule would change the supplied case.','Passing B2 detection alone can coexist with mishandling stale successful checks.','One test is not complete input-domain validation.','Use a declared-rule counterexample and preserve untested conditions.','Counterexamples cost additional distinct fixtures.','VIABLE'),
('Replay the original state-machine audit','adjacent success','SVS-02 exact transition table available','The original table exposes check PASS→start and FAIL→connect.','The same explicit event requirement can validate B2.','It does not prove a new sequence is physically valid.','Replaying an old successful setup after setup change uses a stale result.','A successful historical check is not a successful current check.','Unreadable input was absent from the old domain.','An old two-value validation cannot certify a new three-value process.','Replay only unchanged declared domains; invoke PV for new observations.','Version drift makes unqualified replay unreliable.','CONDITIONAL'),
('Treat comparison as a query family','reframe','three requested answer types separable','“What changed?” and “what violates a rule?” return different outputs.','The user can obtain both without collapsing one into the other.','No single scalar edit score is produced.','A shortest report dropping lexical changes cannot answer exact wording questions.','Compression changes the answer family if its contract is unstated.','A report listing all words may still omit the only violated dependency.','More text does not guarantee requested relation coverage.','Declare answer types, then include the required projection for each.','Several views require maintained links to a common source.','VIABLE'),
('Decompose inventory/order/outcome','decomposition','actions, ordering and check outcome rule supplied','Inventory equality, precedence change and PASS requirement are checked separately.','Each failed subclaim has a specific witness.','A single undifferentiated validity verdict is withheld.','Conjoining checks from different versions can validate a nonexistent combined state.','All checks must refer to the same exact version.','A check step’s presence is weaker than check success.','Output event must be inspected where the rule names its value.','Use same-version source plus actual outcome domain.','More granular checks need explicit join keys.','VIABLE'),
('Topological sorting of declared prerequisites','cross-domain','check-before-start edge available','Both A and B satisfy the one edge; B2 does not.','Every returned topological order satisfies that declared edge.','It makes no claim about unconstrained actions.','Treating every A precedence as mandatory rejects B by definition.','A descriptive original order was silently promoted to a requirement.','Dropping the successful-result condition treats any check as enough.','A plain action graph needs an event condition.','Use typed conditional prerequisite, not all observed edges.','A graph can be correct but too weak for device certification.','VIABLE'),
('Enumerate all six-action permutations','search','six distinct symbolic action names available','The order space has 720 permutations; half place check before start.','It can exhaust the single precedence predicate.','It cannot exhaust unspecified physical behaviors.','Calling all 360 order-valid permutations safe invents device semantics.','Formal coverage is relative to the declared rule.','Check fail still appears before start in some invalid outcome traces.','Permutation-only modeling omits outcomes.','Enumerate order and outcome separately if both matter.','720 cases are unnecessary for the three concrete comparisons.','CONDITIONAL'),
('Minimize edit count','optimization','A/B token sequence available','Counts a compact explanation of the reorder.','Can help a reader navigate the supplied difference.','Does not optimize validity or physical safety.','A one-action start move can violate a mandatory rule.','Minimum edit count is not minimum consequence.','A large benign wording rewrite has high distance.','Distance alone reverses meaningful priorities.','Use edit count only after consequence classes are preserved.','Metric choice changes rankings without changing dependencies.','ELIMINATED'),
('Replay outcome traces','simulation','symbolic pass/fail outcomes available','A successful check permits start; failure returns to connect in the original model.','B2 attempting start before an observed pass can be rejected.','No real setup behavior is learned.','A simulator that assumes all checks pass hides the failure branch.','It would certify a policy under a substituted observation distribution.','A simulator without unreadable omits the new PV input domain.','Trace completeness depends on declared event types.','Enumerate relevant outcomes including absence where supplied.','State explosion grows with repeated retries; use invariants for loops.','VIABLE'),
('Inspect device specification','external evidence','no device/manual supplied','The physical connect/power rule cannot be verified from this input; retain unresolved.'),
('Run a physical power-order trial','physical experiment','no device or experiment performed','No actual physical outcome is available; symbolic traces are not a substitute.'),
('Ask an expert to certify both versions','social evidence','no expert response available','A drafted request does not establish the missing dependency; continue formal checks only.')]
foht('foht-02','Find whether a broader method search adds a useful way to compare instruction versions.','MD-01 already distinguishes wording, observed precedence and declared prerequisites; this method map must add more than that established separation.','A gather→connect→select→power→check→start; B gather→power→connect→select→check→start, with gather wording changed; B2 gather→connect→select→power→start→check. Explicit rule: start requires a current successful check. No physical cable/power rule is supplied.',[
'MUST identify the exact A/B descriptive reorder.','MUST flag B2’s declared check-before-start violation.','MUST not infer unspecified device causality.','SHOULD retain wording changes for lexical queries.','CONSTRAINT actor is the local symbolic comparison.','CONSTRAINT preserve criterion and source version; no expert or human effects are observed.'],m2,
'Typed relation projection, decomposition and conditional dependency checking survive. Word/position/replay/permutation methods are conditional. Bag equality and minimum edit count fail as complete validators. Physical evidence paths are blocked. The surviving recommendation is the same MD-01 operation; no additional optimum or physical-safety claim follows. First action: reuse instruction-difference-observations.json; unresolved item: real device rules.',
'No new operation beyond MD-01 is warranted; the map confirms its scoped comparison and preserves unavailable physical evidence.',
'The larger search supplies explicit alternatives and countercases, but does not improve the earlier concrete A/B/B2 decisions. Additional benefit is rejected.', 'REJECT',
'On A2, only “Gather materials” becomes “Collect materials” and the action sequence stays A. The typed relation comparison returns a lexical edit and zero precedence changes. Both the ordinary MD-01 method and expanded search agree; no extra benefit credit.')

R='ABAB';O='AB'
def embeddings(r,o):
 return [{'kept_zero_based':list(ix),'deleted_zero_based':[i for i in range(len(r)) if i not in ix]} for ix in combinations(range(len(r)),len(o)) if ''.join(r[i] for i in ix)==o]
obs={'repeated_reference':{'reference':R,'observed':O,'all_deletion_only_explanations':embeddings(R,O)},'unique_boundary':{'reference':'ABAC','observed':'ABC','all_deletion_only_explanations':embeddings('ABAC','ABC')},'impossible_boundary':{'reference':'AB','observed':'BA','all_deletion_only_explanations':embeddings('AB','BA')}}
(D/'sequence-localization-results.json').write_text(json.dumps(obs,indent=2))
m3=[
('Greedy left-to-right alignment','direct','exact reference ABAB and observed AB available','Retains reference positions 0,1 and reports deleted 2,3.','It supplies one valid deletion-only reconstruction.','Alternative embeddings are not enumerated.','Keeping positions 0,3 also yields AB.','Its reported last-pair deletion is not uniquely identified.','Keeping positions 2,3 yields AB as well.','A second distinct explanation defeats a unique-location claim.','Label the greedy output one witness, then enumerate alternatives when localization matters.','Fast witness generation is weaker than uniqueness testing.','CONDITIONAL'),
('Greedy right-to-left alignment','direct','same exact symbols available','Retains positions 2,3 and reports deleted 0,1.','It confirms a different valid reconstruction.','It omits the middle-pair deletion.','Positions 0,3 form another embedding.','Right preference cannot establish original missing locations.','Agreement on another input does not prove both greedy methods cover all embeddings.','Two witnesses are not a complete alternative set.','Use opposing greedy outputs as ambiguity witnesses, then exact enumeration.','Tie-breaking chooses a presentation, not historical evidence.','CONDITIONAL'),
('Positionwise mismatch','direct','ordered strings available','Finds the common prefix AB and two absent suffix positions.','Describes a prefix-based difference compactly.','It assumes alignment rather than testing it.','Observed AB can come from positions 2,3.','The common prefix is not evidence those were retained.','ABAC→ABC shifts C after one deletion.','Indexwise mismatches exaggerate the number of removed events.','Align subsequences before locating missing positions.','Sensitive to insertions and deletions near the start.','ELIMINATED'),
('Enumerate subsequence embeddings','category','deletion-only model and finite strings available','Returns kept [0,1], [0,3], [2,3].','Their complements give all three two-deletion explanations.','No insertion or substitution is modeled.','If observation includes substitution, this search can return none despite a real edit history.','Failure then concerns the model, not impossibility of any history.','If timestamp identities distinguish repeated A events, three explanations overstate ambiguity.','Additional evidence can collapse equivalence.','Use the declared deletion model now and add identity evidence only if supplied.','Choose(n,k) grows rapidly; finite exact scope is four symbols here.','VIABLE'),
('Search for a second witness','inversion','one valid greedy embedding available','A different valid embedding refutes uniqueness.','Only two witnesses are needed to stop a unique-localization claim.','It does not enumerate all possible histories.','No second witness found by incomplete search does not prove uniqueness.','Search completeness matters for a negative result.','A second witness with changed symbol order is invalid.','Witnesses must satisfy the same deletion-only model.','Use exact finite enumeration for the no-second-witness branch.','Cheaper than full reporting when ambiguity alone answers the question.','VIABLE'),
('Replay adjacent unique case','adjacent success','ABAC→ABC computed in the same finite model','Only kept [0,1,3] reproduces ABC.','Deleted position 2 is uniquely localized in that case.','Uniqueness is not transferred to repeated ABAB.','Repeated motifs produce three witnesses in the main input.','A unique neighboring case does not certify a repeated one.','A new observation AC has multiple candidate A positions.','Changing observed length changes the explanation set.','Recompute witnesses for each exact pair.','A remembered successful example can conceal changed ambiguity.','CONDITIONAL'),
('Return an equivalence class of histories','reframe','goal permits honest uncertainty rather than one invented location','Reports three histories as observationally equivalent under the current record.','The next action can seek distinguishing evidence instead of repairing an arbitrary last pair.','No single missing location is announced.','If downstream only needs any valid compact diff, three histories add overhead.','The answer family determines whether the class is useful.','If timestamps make events unique, a class may be unnecessarily broad.','Do not preserve uncertainty after new distinguishing evidence.','Return one witness for reconstruction tasks, class/uniqueness for localization tasks.','The output must retain the criterion “localize,” not silently change it to “explain somehow.”','VIABLE'),
('Separate feasibility, multiplicity and identity','decomposition','reference, observation and event-identity domain explicit','First verify AB is a subsequence, then count three embeddings.','Feasible observation and unique cause become separate answers.','Physical missing-event cause remains unknown.','Zero embeddings under deletion-only does not establish bad data.','Insertions or reordered capture can be alternative models.','Three embeddings are not three equiprobable causes.','No probability distribution over histories is supplied.','Report count and candidates without uniform probabilities.','Extra structure is needed for causal attribution.','VIABLE'),
('Dynamic-programming embedding count','cross-domain counting','small string recurrence available','Counts three embeddings without choosing one by tie-break.','Count>1 establishes non-unique localization.','A count alone omits the actual candidate positions.','A report “3” cannot guide which external timestamp would distinguish candidates.','Witness extraction is needed for targeted follow-up.','Counting paths without handling repeated symbols can double-count representations.','The unit must be distinct kept-index subsets.','Cross-check the recurrence with explicit subsets in this finite case.','Useful for larger counts; less inspectable than three exact witnesses here.','VIABLE'),
('Match only symbol counts','abstraction','A/B counts available','Reference has two A/two B; observation one A/one B.','At least one A and one B are missing under deletion-only.','Location and order are discarded.','Observed BA has the same counts as AB but different embeddings.','Equal counts cannot identify the actual record.','Reference AB and observed BA have equal counts but no deletion-only explanation.','Inventory equality does not preserve order feasibility.','Use counts as a necessary filter, then ordered matching.','Compression is valid only for inventory questions.','ELIMINATED'),
('Attach fresh unique IDs retrospectively','representation intervention','positions can be labeled now','Labels 0–3 make candidate histories easy to name.','The three explanations become inspectably distinct.','Retrospective labels do not recover which event was actually observed.','Calling observed A “A0” without evidence chooses a history.','A label cannot create an old identity measurement.','Future IDs would solve a different data-collection problem.','Future capture design does not alter current evidence.','Use retrospective IDs only as coordinates; label future events prospectively if the task needs identity.','Naming ambiguity can be mistaken for resolving it.','CONDITIONAL'),
('Minimize number of deletions','optimization','both lengths and deletion-only model available','Every explanation removes two symbols.','All three candidates have equal edit cost.','No historical likelihood ranking follows.','Selecting the lexicographically first minimum is an arbitrary tie-break.','A deterministic output remains epistemically ambiguous.','Adding a “prefer suffix deletion” penalty imports an unstated prior.','A ranking objective is new evidence only if independently justified.','Retain all equal minima when localization is the criterion.','Optimization can hide non-identifiability behind one chosen answer.','VIABLE'),
('Read original timestamped event IDs','external evidence','no timestamp/identity log supplied','The distinguishing historical measurements are absent; do not invent them.'),
('Interview the observer about the missing interval','human evidence','no observer report supplied','A drafted question is not an observation; current localization stays set-valued.'),
('Re-run the historical recording','physical replay','no access to the original event process','A new similar stream cannot establish which earlier events were missing.')]
foht('foht-03','Change the next action when a plausible sequence reconstruction does not uniquely locate missing events.','A conventional alignment supplies a valid reconstruction of ABAB→AB; I do not yet know whether the missing positions are uniquely identifiable.',
'Reference ABAB, observed AB. The model permits deletions only and preserves order. Goal: determine whether missing reference positions can be uniquely localized, with an inspectable witness set if not. No timestamps, unique event IDs, insertion model or history probabilities are supplied.',[
'MUST determine existence of a deletion-only explanation.','MUST distinguish one reconstruction from unique localization.','MUST preserve exact order and symbol identity.','SHOULD provide distinct witnesses if ambiguity exists.','CONSTRAINT all observations are finite constructed strings; no human perception effect is measured.','CONSTRAINT no equal-probability assumption or fabricated historical IDs.'],m3,
'Exact embedding enumeration returns three witnesses; second-witness search can refute uniqueness quickly, while full enumeration supplies the requested inspectable set. Equivalence-class output and feasibility/multiplicity separation preserve the localization criterion. Counts and position mismatch are insufficient; historical evidence paths are blocked. First action: stop attributing the missing events to an arbitrary suffix and retain the three candidates. The cause remains unresolved.',
'The output now returns three possible deletion locations rather than treating a selected alignment as identified history. A later unique case returns one location; an impossible deletion-only case stays model-incompatible.',
'Actual sequence-localization-results.json changes the next operation: no arbitrary suffix repair is selected for ABAB→AB, while ABAC→ABC identifies deletion at zero-based position2. This is new within the finite localization case, not a human attention claim.', 'KEEP',
'The same enumeration on ABAC→ABC yields exactly one witness (kept0,1,3), so deletion2 is localizable. On AB→BA it yields none under deletion-only. This prevents the newly established uncertainty rule from becoming a universal refusal to localize; all three outputs are saved.')
