from write_support import *
# Concrete finite workspace planning task; data are a constructed model exercise.
rooms=[['Booth','yes','yes',1,'09:20–09:25'],['Shared table','yes','yes',4,'none'],['Garden','yes','no',2,'none'],['Alcove','no','yes',1,'none'],['Studio','yes','yes',2,'booked before 09:45']]
methods=[
('Enumerate room × start pairs','direct','five rooms and four starts; met','Every admissible pair appears in the table.','If each pair is checked, a feasible best-ranked pair is not omitted.','Unlisted start times are outside this declared exercise.','Testing only 09:00 falsely excludes the booth.','The booth becomes interruption-free at 09:30; location-only enumeration omits that candidate.','If interruption intervals are outdated, the table ranks a nonexistent opening.','Real-world availability remains unverified.','Use this finite table for the model decision and verify actual schedules before human use.','VIABLE'),
('Choose quietest room label','direct','noise ratings; met','Booth and alcove have the smallest stated rating.','If all other constraints were satisfied, no listed room would be quieter.','Time-varying feasibility is ignored.','Alcove is inaccessible.','Equal noise does not make the required access constraint true.','Booth at 09:00 intersects its interruption.','A room name alone fails to specify a usable interval.','Filter complete room-window pairs before noise ranking.','ELIMINATED'),
('Choose earliest feasible session','direct','time and access data; met','Shared table at 09:00 finishes at 09:30.','No allowed start is earlier than 09:00.','Waiting for a quieter room is rejected.','Quietness is the first stated preference after feasibility.','Booth 09:30 is quieter and meets the deadline.','A new immediate deadline would reverse this ranking.','The present input contains no immediate deadline.','Respect the declared quietness-then-start lexicographic order.','ELIMINATED'),
('Constraint satisfaction then preferences','category','binary constraints and ordered preferences; met','Only accessible online uninterrupted pairs survive.','Among survivors, minimum noise then earliest start selects Booth 09:30.','An inaccessible quiet space cannot win by compensation.','Omitting the network requirement admits Garden 09:00.','Its quiet score cannot repair the absent network.','Treating an interruption as a noise penalty admits Booth 09:00.','A hard interruption constraint is not a preference.','Keep feasibility separate from preferences.','VIABLE'),
('Remove one blocker at a time','inversion','blocker list; met','A identified blocker explains each rejected candidate.','Removing booth timing overlap creates Booth 09:30.','No evidence is created that stairs or connectivity can be changed.','Removing access requirement makes the task different.','A successful output for the revised task does not satisfy this input.','Removing every blocker invents resources.','The host cannot install a network or alter rooms.','Vary an available start time; retain physical constraints.','CONDITIONAL'),
('Replay adjacent feasible example','adjacent success','Shared table 09:00 is an observed model-feasible pair; met','Replaying it preserves access, network and no scheduled interruption.','It guarantees a feasible answer within these supplied rows.','Quieter feasible pairs are not searched.','A new row has Booth 09:30 noise 1.','Replay loses the stated preference comparison to that row.','If the replay were from a different building, access would not transfer.','The current adjacent example is valid only in this table.','Use the example as a feasibility witness rather than final optimum.','CONDITIONAL'),
('Treat time as a movable component','reframe','four permitted starts; met','The booth is not permanently disqualified by its 09:20 interruption.','Starting at 09:30 yields an uninterrupted half-hour.','Starts outside the specified four are not invented.','For a fixed 09:00 appointment the shift is inadmissible.','The method depends on actual schedule flexibility.','Moving to 09:15 still overlaps 09:20.','Not every later start resolves the blocker.','Select an allowed interval after checking overlap, not “delay” generically.','VIABLE'),
('Separate access/network/time tests','decomposition','three explicit constraints; met','Each infeasible pair has at least one identifiable failed test.','Passing all three makes a pair feasible by the declared definition.','Soft noise preferences cannot compensate for a failed test.','If independent tests use different versions of a schedule, their conjunction is not about one state.','The merged answer can be a pair that never coexisted.','For an unlisted duration, the time test changes.','Thirty-minute validity is not arbitrary-duration validity.','Use one snapshot and thirty-minute intervals throughout.','VIABLE'),
('Greedy noise-first search with backtracking','search','rooms ordered by noise; met','Check Booth starts before noisier rooms.','The first feasible Booth window has minimum stated noise.','Equal-noise ties still need earliest-start checking.','Stopping at Booth 09:00 returns an infeasible option.','Greedy choice requires backtracking when a hard constraint fails.','Ignoring Alcove access would create a false tie.','Noise ordering is not feasibility ordering.','Reject invalid pair then continue starts; do not stop at the first room.','VIABLE'),
('Random feasible sample','disruption','sampling over twenty pairs; met','Any retained sampled pair passes the hard constraints.','The sample can return a valid plan without a full ranking.','Completeness of the preference search is abandoned.','A sample containing only Shared 09:00 misses quieter Booth.','Feasibility is weaker than the requested preferred feasible pair.','A tiny sample can contain only invalid pairs.','No result does not establish no feasible room.','Use random sampling for unfamiliar larger spaces, not this twenty-pair exact task.','ELIMINATED'),
('Choose the predictably noisy room','negation-derived','Shared table interruption data; met','Shared 09:00 satisfies uninterrupted work despite noise 4.','It demonstrates that silence and interruption are separate variables.','The quietness preference is sacrificed.','Booth 09:30 satisfies both uninterrupted and quieter requirements.','Choosing noisy as a principle loses on the given preference.','Noise tolerance of a real person is unspecified.','The supplied numeric order is only this model task.','Retain Shared as fallback if waiting ceases to be allowed.','CONDITIONAL'),
('Use a calendar occupancy raster','representation','interval endpoints; met','Blocked intervals become marked cells.','A thirty-minute clear run identifies viable starts.','Times finer than the raster are discarded.','A fifteen-minute raster that rounds away 09:20–09:25 falsely clears Booth 09:15.','Rounding a blocked subinterval changes feasibility.','Rounding outward can reject a legal boundary start.','Coarse cells trade exactness for convenience.','Use exact endpoints or a five-minute grid for this table.','CONDITIONAL'),
('Observe the room live','physical verification','human or sensor access; absent',None,None,None,None,None,None,None,None,'BLOCKED'),
('Reserve every room then cancel','resource control','booking authority and cost rules; absent',None,None,None,None,None,None,None,None,'BLOCKED'),
('Install soundproofing and network','environment engineering','physical resources and authorization; absent',None,None,None,None,None,None,None,None,'BLOCKED')]
criteria=['H1 MUST: output one accessible, online, uninterrupted thirty-minute pair.','H2 MUST: start at 09:00, 09:15, 09:30 or 09:45.','H3 MUST: choose lowest stated noise among feasible pairs, then earliest start.','H4 SHOULD: preserve a fallback if a supplied condition changes.','H5 CONSTRAINT: all data are constructed exercise inputs; no human behavior or actual occupancy is observed.','H6 CONSTRAINT: actor is this model and its selected plan.']
body='INPUT: Select a thirty-minute reading workspace from the finite table. Allowed starts are 09:00, 09:15, 09:30 and 09:45. Hard constraints: access, online connection, no scheduled interruption during the interval. Among feasible pairs prefer quieter, then earlier.\n\n'+table(['Room','Accessible','Online','Noise order','Unavailability'],rooms)+'\n\nDONE: a selected pair, a demonstrated reason for excluding each better-looking invalid pair, and an explicit limit on real-world claims.\n\n'+ '\n'.join(criteria)+'\n\nBaseline ordinary calculation: Booth 09:00 and 09:15 overlap 09:20–09:25; Booth 09:30 and 09:45 are feasible; Alcove fails access; Garden fails online; Studio is unavailable until 09:45; Shared is feasible but noisier. The ordinary constraint check selects Booth 09:30. This baseline is already adequate; it is not weakened to make the skill win.\n\nFINDING REGISTRY (each product below is both the exploration output and the retained entry; synthesis appears only afterward):\n\n'
findings=[];f=7
for i,m in enumerate(methods,1):
 name,source,pre,ar1,ar2,fore,aw1,awdeep1,aw2,awdeep2,alt,verdict=m
 body+=f'\nMethod M{i}: {name} [source: {source}]. H{f}: prerequisite {pre}.\n';f+=1
 if ar1 is None:
  body+=f'H{f}: BLOCKED because the named capability is absent; no actual physical effect is available.\n';f+=1;continue
 ids=[]
 for label,txt in [('AR necessary',ar1),('AR consequence',ar2),('Foreclosed',fore),('AW state/countercase',aw1),('AW consequence',awdeep1),('AW second state',aw2),('AW second consequence',awdeep2),('Alternative derived from preceding AW',alt)]:
  ids.append(f'H{f}');body+=f'H{f} — {label}: {txt}\n';f+=1
 body+=f'M{i} verdict: {verdict}; AR {ids[0:2]}; decisive AW and alternative {ids[3:]}. Costs/edges are {ids[2]}, {ids[5]}, {ids[6]}. These are conditional model-task claims, not established treatment effects.\n'
body+=f'\nTotals: fifteen methods found; twelve tested with AR/AW; fifteen prerequisites, twelve met and three unmet; {f-1} numbered products including six criteria/constraints, ninety-six substantive AR/AW/alternative products, and three blocked-capability findings. All findings are retained above.\n\nSYNTHESIS: M1/M4/M7/M8/M9 provide valid routes for this finite input; M5/M6/M11/M12 are conditional; M2/M3/M10 fail the declared preference or feasibility requirements; M13–M15 are blocked. The ordinary M4 baseline already selected Booth 09:30. The expensive map does not improve that answer.\n\nLater application: impose the boundary “start must be 09:00” without altering access/network/interruption requirements. Ordinary constraint checking and the expanded method map both select Shared table 09:00. Reframe M7 is now inadmissible; the supposedly counterintuitive noisy fallback is simply the only feasible 09:00 option. Actual changed operation: none beyond the baseline’s existing constraint treatment. No new KEEP credit is earned for discovering that feasibility precedes preferences.'
record('foht-01','Expand location choice into feasible room-and-time operations, if that changes the best working plan.','I would already check room availability against the permitted start windows and choose the quietest feasible pair; a more elaborate method search must beat that ordinary calculation.',body,'The exact plan remained Booth 09:30, and the fixed-start boundary still selected Shared 09:00. The method map added alternatives but did not improve either decision.','Useful distinctions were displayed, but they were already in the baseline. No additional benefit is established; a claim of transformation would be performative.','REJECT','The finite input table and two decisions are easier to reuse than the full fifteen-method registry. The full registry is retained for fidelity and audit, not prescribed as the efficient default.','Try an attention task with hidden interactions; vary representation of uncertainty; find a capability change that enables a previously unavailable operation.',depth='Original 8x floors met: fifteen methods found, twelve tested, fifteen prerequisites, over eighty numbered findings. All twelve tests include AR, further consequence, foreclosure, two AW countercases/consequences and a derived alternative.')
