from gg_support import *
s=Search(1)
s.add('Morphological AGENT','Whose interpretation should the representation expose?','present model as endorser;present model as source transcriber;present model as counterexample constructor;later model as retriever;user as proposition author;original graph author as route proposer;reviewing model as scope checker;tool host as segment provider')
s.add('Morphological ACTION','Which operation should become directly available?','retrieve the exact reason;expand the target definition;compare two proposition operands;mark a time mismatch;instantiate a same-scope countercase;separate association from entailment;preserve an unresolved reason;follow a medium-weight threshold edge;inspect incoming routes;hold the raw L2 question beside the L4 node;test subjective certainty without truth;keep a creative association after rejecting its logic')
s.add('Morphological OBJECT','What should a comparison operate on?','the sure→hope reason;the sure→true prerequisite;the sure→enough expansion;the threatening definition;the maybe→if composition;the actual action under consideration;the actor who is certain;the proposition with its time index;the entire eight-edge sure neighborhood;the exact two-hop path')
s.add('Morphological REASON','What immediate purpose can justify a representation change?','avoid a false contradiction;preserve a useful association;retain source authorship;find an omitted operand;reduce repeated export reads;expose a change of abstraction;identify a false factive reading;distinguish confidence from action threshold;show a foreclosure of a route;keep a disputed reason open;make a low-weight path visible;enable exact copying of a claim;detect duplicated justifications;make a boundary countercase available;separate evidence for source identity from endorsement')
s.add('Morphological METHOD','Which representation could do that work?','four-column source/relation/target/reason table;paired P-at-t and Q-at-u cards;literal quote with adjacent countercase;edge record keyed by source/type/target;scope-check field left blank until filled;two panes for original and endorsed statements;list of only changed endorsements;equivalence class for repeated reasons;small path matrix with definitions;claim-specific timeline;typed proposition slots;conditional route dispatch;negative-space list of absent premises;source-weight display separate from truth status;source-byte receipt linked at edge level')
s.add('Morphological TIME','When should the representation intervene?','before endorsing a route reason;after reading an unexpected target definition;when a source route changes the action;at the first reuse in another proposition;after discovering mismatched times;before compressing a graph path;when a route loops back to sure;at a later resumption with the raw question restored')
s.add('Morphological LOCATION','Where should the decisive operand be visible?','adjacent to the route reason;in the same row as the target definition;in a reusable local edge object;at the top of the selected path;inside the next application input;beside the claim verdict')
s.add('Morphological DEGREE','How much of the graph should the operation expose?','one exact route;two routes sharing a reason;all five generic contradiction routes;all eight outgoing sure routes;one second-hop comparison;the full nineteen-edge second hop;one incoming neighbor;one applicable chain;one raw question and its nearest node;one contrastive pair from a different scope')
s.add('Morphological CERTAINTY','What warrant state should remain representable?','authentic text with untested reason;authentic text with rejected reason;conditional inference with explicit operands;valid association without entailment;unresolved target interpretation;countercase established in a stipulated world;source weight without truth estimate;current local endorsement with no human-transfer claim')
s.add('Morphological SCOPE','Which boundary should the representation preserve?','same person and proposition;different person with same words;same proposition at different times;different propositions at one time;subjective sureness versus factive warrant;action sufficiency versus truth certainty')
s.add('Morphological CONSTRAINTS','Which constraint must a candidate respect?','do not edit the original export;retain the exact reason string;preserve the raw question;do not infer human feelings;do not treat weight as probability;do not replace hope with uncertainty by definition;keep low-weight routes accessible;do not assert truth from filename;keep a failed counterargument visible;do not count repeated source reasons as independent evidence;do not drop target definitions;do not claim global graph validity from eight edges;do not hide missing premise slots;do not conflate tool access with attention benefit;do not turn a suggested route into a required conclusion')
for op,q,vals in [
('Substitute','What source-display component could be substituted?','replace weight-first ordering with operand-mismatch ordering;replace a node title with its full definition;replace generic certainty label with certainty-about-P-at-t;replace a single endorsed sentence with original/endorsed pair'),
('Combine','What could be combined without conflating warrants?','attach a source receipt to an edge object;attach a countercase to the exact reason it defeats;join a path with the original L2 question;join a retained association with a rejected-entailment label'),
('Adapt','What structure could be imported as a design analogy?','use a compiler type check for proposition identity;use an editorial margin for disputed wording;use a museum catalog distinction between object and interpretation;use a version diff for changed endorsements'),
('Modify','What scale or salience change could help?','enlarge the absent-time field;collapse repeated reason text while exposing all five targets;expand only the definition responsible for a conflict;reduce visual weight of high source weight after scope mismatch'),
('Put to other use','What additional use could the preserved route serve?','generate a creative continuation despite invalid logic;build a retrieval cue for a later threshold question;construct a semantic regression case;record why a tempting route was not followed'),
('Eliminate','What could be removed without losing the required object?','remove inferred probability from weight;remove duplicated display of the same generic reason;remove decorative arrows that imply entailment;remove a premature endorsed status before scope is instantiated'),
('Reverse','What order could be reversed?','read target definition before route reason;construct a countercase before importing source justification;show medium-weight enough before high-weight true for the action task;start from a failed boundary and recover the valid narrower relation')]:s.add('SCAMPER '+op,q,vals)
s.add('Stakeholder perspectives','Which stakeholder concern could reveal a missing representation field?','user needs the exact claim preserved;source author needs attribution without endorsement;current model needs a concrete next query;future reader needs a scope cue;skeptical reviewer needs the strongest same-scope countercase;creative reader needs a surviving association;maintainer needs stable edge identity;tool operator needs an exact fetch target;novice reader needs node definitions;expert reader needs fewer repeated glosses;person with low reading time needs the selected action first;archivist needs old and revised endorsements both retained',direction='DIAGNOSTIC',orientation='NEUTRAL')
s.add('Time horizons','At which horizon can a different failure become visible?','this route endorsement;the next model paragraph;the next different proposition;the next file in this run;the first consolidation;the fourth reuse of the same reason;the end-of-run audit;the next explicitly resumed session;the next source graph version;after an expired action opportunity;after a user changes the intended meaning;historically before the graph was imported',direction='DIAGNOSTIC',orientation='NEUTRAL')
for typ,q,vals in [
('Factual','What factual possibility deserves verification?','the sure export has eight outgoing edges;the five contradiction reasons share one string;the target definition mentions psychological threat;the source weight fields are categorical'),
('Causal','What alternative could cause an apparent improvement?','a target definition supplied new information rather than the layout;the second pass benefited from repetition rather than annotation;the verdict changed because the criterion changed;the focused route was easier because its proposition was more concrete'),
('Predictive','What later result could discriminate representations?','a new-scope query retrieves the time condition;an exact edge lookup returns the original reason unchanged;a hidden-mismatch case prevents endorsement;an already explicit proposition gets no benefit from extra fields'),
('Normative','Which value could choose between valid displays?','fidelity favors literal quote preservation;inspection favors nearby operand slots;exploration favors retaining non-entailing associations;efficiency favors suppressing repeated display not deleting source text'),
('Modal','What could be possible despite a rejected inference?','a route can be useful without entailing its target;a source can be authentic and its reason false;a reader can be certain about P and hope about Q;a low-weight edge can answer the concrete action question better'),
('Relational','Which relation might need a different operand structure?','contradiction needs incompatible claims about matching scope;prerequisite for warranted certainty differs from prerequisite for feeling sure;sufficiency for action depends on the action;analogy between maybe and perhaps does not make them identical'),
('Intentional','What intent is supported or unsupported?','the current user requests genuine beneficial exploration;the original graph offers routes rather than direct answers;the current model seeks a warrant for its exact proposition;the future reader’s preference for a table is unknown'),
('Meta','What assessment claim needs its own boundary?','source authenticity does not certify executed inference;an annotation count does not measure benefit;a rejected generic reason can retain a narrower valid reading;a passing finite example does not certify every graph edge')]:s.add('Claim type '+typ,q,vals,direction='DIAGNOSTIC' if typ in ['Factual','Causal','Intentional','Meta'] else 'CONSTRUCTIVE',orientation='NEUTRAL',impact='HIGH')
for domain,vals in [
('Biology','label parentage separately from current function;track one mutation in an endorsement lineage;keep neutral variants instead of discarding every non-optimal association;compare two environments for the same retained interpretation'),
('Physics','declare a reference frame for the proposition;retain time coordinates on certainty and hope;separate a measurement reading from its interpretation;compare invariants when the display changes'),
('Economics','treat attention as a scarce allocation;distinguish an asking price from demonstrated value;retain option value of an unexplored association;avoid aggregating five copied reasons as five independent investments'),
('Psychology','distinguish reported certainty from evidential warrant;keep observer and subject separate;construct a contrast in which mood remains unknown;avoid inferring attention improvement from a cleaner page'),
('Engineering','type-check exact proposition operands;preserve immutable source with mutable annotation;write a minimal reproducible countercase;fail open to uncertainty when a required operand is absent'),
('Military','separate an intelligence report from an order;display confidence source beside recommendation;retain a reserve route after a main path fails;use an explicit abort condition for an unsupported endorsement'),
('Nature','make branch divergence visible before reconvergence;keep provenance like an identifiable upstream source;mark a boundary where two territories overlap;preserve a dormant candidate without calling it active'),
('Games','declare the rules before scoring an inference;change one rule and observe the verdict boundary;keep a legal move even when it is not optimal;distinguish a map hint from a forced move'),
('History','preserve the original wording and later interpretation separately;date each claim rather than flattening a timeline;compare rival readings of the same event;record a correction without rewriting the prior record'),
('Medicine','separate a reported symptom from a proposed cause as an analogy only;keep a differential list until a discriminator is supplied;record a test’s exact indication rather than universalizing it;avoid treating a negative test for one condition as exclusion of all conditions')]:s.add('Analogy '+domain,'What structural design transfer could this domain suggest?',vals)
errors=[('Perception','overlook the word underlying in sure→true;miss threatening’s full definition'),('Memory','remember hope as identical to uncertainty;recall a high weight as established evidence'),('Interpretation','read subjective sure as factive;read enough as certainty rather than sufficiency'),('Source','copy the target title but not its definition;attribute an annotation to the original graph'),('Selection','choose only high-weight routes;ignore incoming neighbors because the display hides them'),('Confirmation','find only examples where certainty and hope conflict;discard a valid association because its reason fails'),('Availability','reuse the last successful scope warning on every edge;select truth because it is a familiar endpoint'),('Anchoring','freeze the first L4 match despite the L2 input;let the first table layout define relevant variables'),('Motivated reasoning','call every annotation a beneficial mind change;reject harmless source errors to appear rigorous'),('Social pressure','endorse the source because it belongs to the requested system;perform disagreement merely to appear independent'),('False dichotomy','treat source reason as either valid entailment or useless;force certainty into true or false without actor/time scope'),('Scope','contradict P using uncertainty about Q;claim graph-wide improvement from sure-only work'),('Timing','reuse a past certainty statement as present;apply an expired action threshold to a current decision'),('Causation','attribute a changed verdict solely to layout despite added definition;attribute later correct retrieval to a rule never read'),('Definition','define hope as uncertainty to make contradiction automatic;define useful as source-conforming to guarantee success')]
for err,vals in errors:s.add('Pre-mortem '+err,'What specific failure could invalidate this attempted change?',vals,direction='SKEPTICAL',use='THINKING',orientation='REDIRECT',impact='HIGH')
s.add('Deep unbundling I inspect','What could the first-person inspection operation conceal?','the model chooses which edge to open;the model retains a raw proposition;the model supplies a scope interpretation;the model selects a source version;the model decides a reason’s status;the model later acts on that status',direction='DIAGNOSTIC',orientation='NEUTRAL')
s.add('Deep unbundling warranted is good','What distinct criterion could warranted conceal?','logical validity for an instantiated claim;factive certainty about a true proposition;subjective confidence accurately reported;usefulness of an inquiry direction;faithful quotation of a source;absence of a known same-scope countercase;fitness for a reversible action',direction='DIAGNOSTIC',orientation='NEUTRAL')
s.add('Deep unbundling because reason','What dependency could a source because-clause conceal?','the proposition is the same on both sides;the relevant time has not changed;the actor is the same;the meaning of sure is factive;the meaning of hope includes uncertainty about that proposition;the relation is logical rather than conversational;the action criterion is supplied',direction='DIAGNOSTIC',orientation='NEUTRAL')
s.add('Deep unbundling need','What separate need could the inspection serve?','preserve attribution;choose the next action;find a neglected route;avoid a false claim;retain useful ambiguity;make a future query executable;enable correction without source destruction')
s.add('Deep unbundling system','What component of the working system could change?','the edge display;the lookup key;the claim template;the endorsement registry;the selected-path note;the countercase collection;the evidence link')
claims=[
('Representation can help this model inspect route reasons','H/L/DEEP','A later judgment can use a visible operand.','A fully explicit tiny claim already exposes it: no added benefit.'),('Attention can be redirected to a missing scope condition','H/L/DEEP','A medium-weight route can receive inspection before a high-weight one.','If all relevant scope is explicit, the shift supplies no new input.'),('Exact source reasons are available','H/H/MEDIUM','Literal attribution is possible.','A missing export would require a fetch, not reconstructed quotation.'),('A route weight influences visibility','M/M/DEEP','Weight-first order favors true/really.','A reason-first display can ignore weight and choose enough.'),('A source reason is not automatically an endorsed inference','H/H/MEDIUM','An authentic reason can be tested and rejected.','Under a task of literal quotation only, endorsement is not being attempted.'),('The raw question has concrete action scope','H/H/MEDIUM','The enough branch remains relevant.','Replacing it with generic certainty would be a different input.'),('Target definitions can alter scope interpretation','H/L/DEEP','Threatening exposes psychological content.','A definition identical to the title supplies no new distinction.'),('A human attention effect is not observed','H/H/MEDIUM','Model-artifact outcomes remain the only current evidence.','A future actual human task could supply a separate observation.'),('A useful association need not be entailment','M/M/DEEP','A rejected reason can leave a creative path available.','A requested formal proof cannot use association as a premise.'),('More fields can impose access cost','M/M/SHALLOW','A small direct question may deserve the plain source line.','A decisive hidden operand can justify the extra field.'),('Repeated reasons need not be independent evidence','M/H/MEDIUM','Five copies cannot establish five independent warrants.','Different instantiated operands can still need five distinct tests.'),('A local display result need not transfer','M/H/MEDIUM','The next unseen case remains a real test.','A separately performed recurrence can support a scoped transfer claim.')]
sel=['G010','G014','G019','G026','G028','G037','G046','G047','G054','G062','G065','G077','G089','G107','G125','G127','G140','G166','G178','G249']
s.output('Find changes of representation, attention, and access that help the present model inspect which QuestionRoute source reasons are warranted for the exact propositions under discussion. The concrete input is the sure-root neighborhood in 06-qr-sure.md and its exact original exports; no human attention effect is assumed.','../inquiry/08-spd-representation.md',claims,sel,'Distinct candidate intended for later use: an edge-specific view that binds exact source reason, target definition and instantiated scope without changing the source export. Prior parent distinctions about source versus endorsement are imported, not a new KEEP. The source neighborhood supplies real operands for tests; constructed countercases supply logical possibilities, not psychological observations.')
