from gg_support import *
s=Search(2)
s.add('Morphological AGENT','Which actor could own the next performed step?','current model using an active tool;current model producing a new inference;later explicitly resumed model;user choosing to reopen the task;authorized scheduler invoking a supported task;source provider making a needed file available;human performing a proposed setting change;reviewer detecting an expired opportunity')
s.add('Morphological ACTION','What distinct continuation operation could be performed?','read the next original now;complete the current open branch;write an exact resumption capsule;restore the capsule in this active session;recheck a source version before reuse;select the next ready independent target;record a genuinely blocked dependency;prepare a reversible artifact before a later decision;classify a proposed act as unperformed;inspect actual scheduler availability;record a successful scheduling acknowledgment if one occurs;discard a stale next-step recommendation')
s.add('Morphological OBJECT','What state object should continuation preserve?','the exact unresolved claim;the current actor and capabilities;the source path and version;the next requested operation;the original depth requirement;the strongest live alternative;the unfinished subordinate invocation;the opportunity expiration condition;the user’s preserved scope;the most recent observed result')
s.add('Morphological REASON','What purpose could justify a timing change?','avoid repeating an already completed branch;use a currently available source;wait for evidence that distinguishes outcomes;preserve a disappearing access window;avoid interrupting a productive operation;give the next actor a definite input;keep optional exploration available;separate preparation from commitment;reduce context reconstruction;avoid claiming idle autonomous work;respect a changed user direction;notice a revoked capability;prevent a blocked task from stopping independent work;retain an unresolved result without closure pressure;match effort to a newly consequential branch')
s.add('Morphological METHOD','Which concrete continuation structure could be tried?','active next-action queue;single-claim resumption capsule;state transition table;event-trigger plus payload record;ready/blocked partition;dependency-complete work packet;source-version checkpoint;expiry-aware next-action card;artifact diff before resume;clock-based task only with actual service acknowledgment;user-driven reopen link;structured failed-attempt log;bounded-batch continuation;two-stage prepare/commit arrangement;unresolved decision with exact discriminator')
s.add('Morphological TIME','At what time relation could the next operation occur?','immediately after this tool result;after a missing source arrives;before a current permission expires;at the next explicit user turn;after an acknowledged clock trigger;after four distinct useful findings;before a high-cost branch;after a changed goal invalidates the old queue')
s.add('Morphological LOCATION','Where could the next step obtain its state?','active conversation context;locally saved capsule;durable saved artifact supplied by root;original source archive;current tool result;the human setting named in a proposal')
s.add('Morphological DEGREE','What extent of continuation could be selected?','one actual operation;one complete source procedure;one unresolved claim branch;one dependent procedure chain;four useful findings and consolidation;one original-depth batch;all remaining allocated exposures;one held-out recurrence;one verification of a stale input;one reversible preparation step')
s.add('Morphological CERTAINTY','What continuation status could a record honestly express?','performed in this run;saved but not resumed;ready when a session is active;blocked on a named input;scheduled with actual acknowledgment;proposed to a human;expired under a changed condition;unknown whether later retrieval will occur')
s.add('Morphological SCOPE','What scope should a timing claim cover?','this exact active run;a later explicitly resumed run;the selected tool operation;the saved artifact’s persistence;the human’s own action;the whole research program over successive continuations')
s.add('Morphological CONSTRAINTS','What constraint should the continuation respect?','do not infer a scheduler from future-tense prose;do not call a saved file a future action;retain the full 300 exposures;do not invent human compliance;preserve original 8x floors;do not claim context retention without available state;do not resend a person-directed message without authorization;keep active work moving when independent slots are ready;do not declare a blocked gate complete;retain source identity during resumption;distinguish current restoration from a later-session test;do not count a duplicate attempt as novel benefit;retain user redirection authority;do not use a wait longer than needed for a result;do not hide opportunity expiry')
for op,q,vals in [
('Substitute','Which continuation component could be replaced?','replace a broad topic note with the exact next input;replace an invented future promise with current execution;replace calendar time with a source-arrival event;replace a blocked task with a ready independent task'),
('Combine','What could be joined while retaining distinct states?','combine payload with source version;combine a trigger proposal with an explicit unacknowledged status;combine a saved checkpoint with an active queue;combine a next action with its invalidation condition'),
('Adapt','What structural pattern could be transferred?','use a transaction log to distinguish prepared from committed;use a laboratory sample label to retain provenance;use a theater cue sheet to pair event and action;use a cache invalidation rule for source changes'),
('Modify','What pace or size could be changed?','shorten a batch when a user steers;lengthen a branch with a new high-value uncertainty;reduce handoff text to unresolved operands;increase explicit context when the next actor differs'),
('Put to other use','What additional role could preserved state serve?','reproduce a current model decision;locate the first incomplete dependency;show that an action was never scheduled;recover an abandoned alternative without re-deriving it'),
('Eliminate','What continuation burden could be removed?','remove repeated original reads when exact bytes are already preserved;remove a completed branch from the active queue;remove vague later language from an execution claim;remove a waiting step when the next input is already available'),
('Reverse','What sequence could change?','perform an independent concrete task before polishing the handoff;test capsule restoration before ending the active run;prepare a reversible artifact before a later irreversible choice;recheck capability before replaying a saved command')]:s.add('SCAMPER '+op,q,vals)
s.add('Stakeholder perspectives','Whose distinct continuation concern should be represented?','current model needs one executable next operation;later model needs source and scope;user needs freedom to redirect;human recipient needs an unperformed action labeled honestly;scheduler service needs supported input;source provider controls availability;reviewer needs evidence of actual execution;maintainer needs stale-state warnings;collaborating line needs dependency completion status;artifact consumer needs a recoverable output;future user needs unresolved questions rather than false closure;present user needs ongoing substantive work',direction='DIAGNOSTIC',orientation='NEUTRAL')
s.add('Time horizons','Which horizon exposes a different continuation condition?','the next tool call;the next sampled inference;the next completed application;the next four-keep consolidation;the current batch ending;the next explicit user message;the next resumed session;the next source update;the next capability change;the next opportunity deadline;the historical point before preparation;the later audit of whether a scheduled task actually ran',direction='DIAGNOSTIC',orientation='NEUTRAL')
for typ,q,vals in [
('Factual','What present fact could be verified directly?','a next-action queue exists;a source file is readable;the active tool call returns a completion;a particular scheduler acknowledgment is absent'),
('Causal','What alternative could explain later successful continuation?','the user supplied fresh context rather than the old capsule;the next model reconstructed the task from files;an independent source update resolved the block;the task was simpler on the second attempt'),
('Predictive','What later observation would discriminate a continuation design?','an explicitly resumed run restores the exact input;a stale source version causes a recheck before use;a missing capability prevents command replay;a next action occurs after an acknowledged event'),
('Normative','Which supported value governs timing?','the stated sustained program favors current execution;revisability favors preserving alternate next steps;fidelity favors carrying original depth;honesty favors labeling a proposal as unperformed'),
('Modal','What state combination is possible?','a payload exists with no trigger;a trigger fires before a dependency is ready;a source is available before the right opportunity;a human proposal exists without human action'),
('Relational','Which temporal relation needs explicit operands?','preparation precedes later commitment;readiness can precede opportunity;authorization can outlast usefulness;retrieval can occur without execution'),
('Intentional','What intention is supported or unknown?','the user requests continuous work;the current agent intends the next active operation;the later user’s willingness to reopen is unknown;the host does not promise idle spontaneous execution'),
('Meta','What claim about progress needs qualification?','a queue entry is not a performed application;a completed preparation is not a failed scheduling attempt;a current restoration test is not longitudinal transfer;a source receipt is not a continuation acknowledgment')]:s.add('Claim type '+typ,q,vals,direction='DIAGNOSTIC' if typ in ['Factual','Causal','Intentional','Meta'] else 'CONSTRUCTIVE',orientation='NEUTRAL',impact='HIGH')
for domain,vals in [
('Biology','preserve dormant state without calling it active;distinguish a cue from the capacity to respond;retain a recovery path when an opportunity disappears;track changes in the surrounding conditions'),
('Physics','carry an explicit time coordinate on every act;distinguish stored potential from released motion as a structural analogy;define the event that begins a state transition;avoid inferring motion from a static snapshot'),
('Economics','preserve an option without exercising it;count the opportunity cost of waiting;separate sunk preparation from future choice;retain an expiry condition on an option'),
('Psychology','distinguish an intention from reported behavior;preserve an implementation cue without claiming habit formation;separate current engagement from predicted future motivation;avoid treating a readable note as demonstrated memory'),
('Engineering','checkpoint state before process termination;verify preconditions before command replay;record acknowledgment separately from request;resume from the first incomplete operation'),
('Military','separate an order from confirmed execution;carry a contingency if the primary channel is unavailable;update plans when terrain information changes;retain command authority checks at the action'),
('Nature','model a seed that persists without germination;separate seasonal opportunity from stored resources;retain alternate paths when one channel dries;mark a threshold crossing as an event not a description'),
('Games','save the game state without claiming a move was played;restore whose turn it is before action;check whether the old legal move remains legal;keep an unchosen move available without counting it as taken'),
('History','date the preparation and execution separately;retain a canceled plan in the record;distinguish an announced campaign from its occurrence;preserve context that made an earlier choice reasonable'),
('Medicine','distinguish a written prescription from administration as an analogy only;retain the conditions under which a plan was indicated;reassess before repeating an old intervention;track whether a follow-up actually occurred')]:s.add('Analogy '+domain,'What structural continuation design could this domain suggest?',vals)
errors=[('Perception','miss a tool result marked still running;mistake a file link for an execution trigger'),('Memory','forget an unfinished subordinate invocation;recall an old source version as current'),('Interpretation','read continuous as idle autonomous operation;read later as an actual time commitment'),('Source','resume from a paraphrase that dropped scope;link a capsule to the wrong original skill'),('Selection','work only on easy ready tasks while never preserving the blocker;keep selecting handoff polish instead of the next application'),('Confirmation','count a restored file as successful transfer;count a proposed schedule as sustained behavior'),('Availability','reuse the last scheduler-shaped solution on an active task;assume the familiar tool remains connected'),('Anchoring','retain yesterday’s next action after the goal changes;keep the original batch size after a user interruption'),('Motivated reasoning','call an unfinished gate completed to hit a count;call future work inevitable to appear persistent'),('Social pressure','promise continuous external action because the user wants ambition;ask unnecessary permission to avoid difficult work'),('False dichotomy','treat work as either autonomous forever or impossible;equate waiting with abandonment'),('Scope','claim a human setting changed because a proposal was written;claim later-session reliability from an in-session restore'),('Timing','wait for a date when the dependency has already arrived;execute an old opportunity after expiry'),('Causation','credit the capsule when a new user message supplied all inputs;credit the clock when manual resumption caused the action'),('Definition','define saved as scheduled;define completion as having described every step')]
for err,vals in errors:s.add('Pre-mortem '+err,'What specific continuation failure could invalidate the result?',vals,direction='SKEPTICAL',use='THINKING',orientation='REDIRECT',impact='HIGH')
s.add('Deep unbundling I continue','What operation could first-person continuation conceal?','the model still has an active turn;the model selects an executable target;the model obtains required inputs;the model performs the selected step;the model observes its result;the model updates the next-action state',direction='DIAGNOSTIC',orientation='NEUTRAL')
s.add('Deep unbundling saved is useful','What distinct use could a saved state support?','recover the exact claim;recover the actor;recover the source version;recover the unresolved alternative;recover the depth floor;recover the next dependency;recover the criterion for revision')
s.add('Deep unbundling because trigger','What dependency could a trigger claim conceal?','the triggering event is defined;the event is detectable;the channel is available;the payload is accepted;the actor can execute it;the task remains authorized;the opportunity has not expired',direction='DIAGNOSTIC',orientation='NEUTRAL')
s.add('Deep unbundling need','What need could a deferred attempt serve?','wait for discriminating evidence;avoid an unnecessary interruption;use a newly available tool;allow a person to perform a step;preserve a future exploration option;complete an already authorized dependency;retest a condition that genuinely changes over time')
s.add('Deep unbundling system','What part of the continuation system could change?','the active queue;the saved payload;the event detector;the scheduler channel;the access path;the precondition check;the historical progress record')
claims=[
('The active model can continue now','H/H/MEDIUM','A next source operation can be performed in this turn.','An ended or blocked turn lacks that active channel.'),('A saved payload can preserve exact state','H/M/DEEP','A later reader can recover the unresolved input.','A vague note omits the operands needed for the next operation.'),('A saved payload does not initiate itself','H/H/MEDIUM','An initiating actor/channel remains a separate dependency.','A host with an actual configured file watcher could provide that trigger.'),('A scheduled act requires a supported channel','H/H/MEDIUM','A request and acknowledgment can be distinguished.','A failed or unsupported request is not a scheduled act.'),('A human proposal differs from human performance','H/H/MEDIUM','The current record can preserve a plan without an observed effect.','An actual human report later could supply a separate performance claim.'),('Ready work can proceed beside a block','H/M/DEEP','An absent rating need not stop an independent original.','A shared missing prerequisite blocks both tasks.'),('A source version matters on resume','M/M/DEEP','Changed originals can require a new read.','Stable bytes need no repeated read solely because time elapsed.'),('A trigger can fire before readiness','H/M/DEEP','The execution needs a precondition check.','When event and readiness are the same defined condition, the mismatch disappears.'),('An opportunity can expire','M/M/DEEP','An old next action may become inappropriate.','A stable theoretical question has no such external expiry.'),('Current restoration can test payload completeness','M/M/SHALLOW','The exact input can be recovered now.','That test does not establish future automatic retrieval.'),('User steering can revise the queue','H/H/MEDIUM','The new instruction can change the next target.','An unrelated status question need not cancel the original goal.'),('More handoff detail can increase cost','M/M/SHALLOW','An already explicit next input may not need a large narrative.','A changed actor or missing source can justify added context.')]
sel=['G001','G004','G009','G013','G016','G021','G023','G028','G041','G047','G052','G060','G067','G085','G098','G121','G141','G166','G179','G255']
s.output('Find changes of timing, pace, control channel, and preserved state that can make the next mind-change attempt occur under the actual capabilities of this active model session and a later resumed session. The concrete input is 05-dd-timing-control.md and 07-qr-when.md. Separate performed current continuation, a saved resumption state, a scheduled act, and a human proposal.','../inquiry/09-spd-timing.md',claims,sel,'Distinct candidate intended for later use: a resumption capsule that carries exact input, original requirement, unresolved dependency, source version and an invalidation condition. Parent distinctions among saved/performed/scheduled/proposed are imported, not new findings. Actual future scheduling or human behavior will not be inferred from the capsule.')
