from write_support import *
def router(name,prompt,intent,state,rows,best,runner,fallback,paths,why,follow):
 body=f'''Exact input: {prompt}

[W1] SURFACE_REQUEST: {prompt}
[W2] INTENT_TYPE: {intent}. [W3] SPECIFICITY: specific. [W4] URGENCY: ready to act. [W5] PRIOR_STATE: {state}. [W6] IMPLICIT_NEED: preserve the input’s stated limits while producing an executable next operation.

Prior-state deep check: {follow}

Ten candidates scored on a 1–5 qualitative fit scale. Total = 3×intent + 2×state + completeness + specificity. Scores describe this exact current task, not user ratings, skill superiority or observed benefit.

'''+table(['Candidate','Intent×3','State×2','Completeness','Specificity','Total','Fit and weakness'],[[sk,a,b,c,d,3*a+2*b+c+d,note] for sk,a,b,c,d,note in rows])+f'''

[W10] BEST_NOW: /{best}. [W11] CONFIDENCE: MEDIUM. [W12] WHY_BEST: {why}
[W13] RUNNER_UP: /{runner}. [W14] WHY_NOT_RUNNER_UP: it addresses a nearby need but is less direct at this present stage. [W15] DISTANCE: CLOSE. [W16] FALLBACK_IF_FAILS: /{fallback}. [W17] FALLBACK_TRIGGER: the chosen procedure cannot produce a concrete result from the supplied input. Fallback is a recovery operation, not the second-ranked candidate.

Multi-path recommendation: {paths} These are conditional branches, not three simultaneous recommendations. The present state selects one skill.

Original required invocation: /{best} executed on this exact input in {best}-02.md. The selected output is retained separately so routing and output benefit are not conflated.'''
 record(name,'Choose one operation appropriate to the changed current input.','The concrete task already suggests a close method family; explicit routing should not earn benefit merely for naming it.',body,f'The current operation is /{best}, with a different recovery route if it fails.','The selected original is actually invoked. No independent additional benefit is established for this ranking over an ordinary direct choice.','REJECT','Keep one selected operation prominent; retain full scores and conditional branches as the source-required audit.','Use the actual selected result; revisit choice if inputs change; preserve a failed route if recovery is triggered.',depth='Original 8x floors met: ten candidates, all four weighted criteria, prior-state deep check, multi-path recommendation, one selected skill, calibrated confidence and distinct fallback; selected original actually executed.')
router('wsib-02','Review the six-state single-step interface when the check observation can be PASS, FAIL or UNREADABLE, and preserve the rule that start requires a successful check.','task/procedure validation','existing SVS-02 process with a new observation value',[
('pv',5,5,5,5,'Covers completeness, inputs, ordering and actual repair; device physics remain unobserved.'),('md',4,5,4,5,'Can derive a method but direct validation is already identified.'),('svs',4,4,4,4,'Generates variants; may overgenerate before naming the missing branch.'),('foht',4,3,4,4,'Searches methods; this exact finite transition gap needs a direct check.'),('pcd',3,3,3,4,'Can add a missing operation after validation establishes the gap.'),('pci',3,3,3,3,'Schema improvements do not alone determine unreadable-observation behavior.'),('iterate',4,3,4,3,'Can improve the design but needs the failure criterion pinned first.'),('unx',2,3,3,3,'Unexpected design is optional; correctness is the present need.'),('crtv',2,2,3,2,'Creative possibilities do not establish the mandatory start condition.'),('la',4,4,4,4,'Can identify limitations but is less direct for complete transition validation.')], 'pv','md','pcd','Existing procedure plus new observation → PV now. No specified success prerequisite → MD to characterize. If no operation can express the repair → PCD recovery.','A concrete existing procedure and missing input branch make full validation directly applicable.','The old interface contains pass→start and fail→connect; unknown_state handles missing state, not an unreadable check value. The archived source and mutable authored interface are distinct. No physical device reading is claimed.')
old=json.loads((D/'single-step-interface.json').read_text());new=json.loads(json.dumps(old))
new['instructions']['paused']='Indicator unreadable. Wait for a readable observation.'
new['transitions']['check']['unreadable']='paused';new['transitions']['paused']={'pass':'start','fail':'connect','unreadable':'paused'}
new['observation_contract']={'pass':'successful check at the current setup','fail':'failed check at the current setup','unreadable':'no result; neither pass nor fail','setup_changed':'return to connect and obtain a new check; old observation invalid'}
new['transitions']['paused']['setup_changed']='connect'
(D/'single-step-interface-v2.json').write_text(json.dumps(new,indent=2))
def run(events):
 state='check';trace=[]
 for ev in events:
  nxt=new['transitions'].get(state,{}).get(ev)
  trace.append({'state':state,'event':ev,'next':nxt,'instruction':new['instructions'].get(nxt)})
  if nxt is None:break
  state=nxt
 return trace
traces={name:run(events) for name,events in {'unreadable_pass':['unreadable','pass'],'unreadable_fail':['unreadable','fail'],'twice_unreadable':['unreadable','unreadable'],'setup_changes':['unreadable','setup_changed'],'invalid_input':['maybe']}.items()}
(D/'single-step-unreadable-traces.json').write_text(json.dumps(traces,indent=2))
checks=[['Completeness','NEEDS REVISION → VALID for declared domain','UNREADABLE had no transition; paused state now covers absence without converting it to failure.'],['Dependencies','VALID with explicit recovery cycle','start requires current successful check; paused→start consumes PASS. Setup change returns to connect. Runtime fail/retry loops are intentional; no prerequisite depends circularly on its own future completion.'],['Feasibility','MODEL VALID; physical use unobserved','All state transitions execute in this local model. Getting a real readable observation is conditional; the procedure may remain paused.'],['Inputs','DECLARED','Known current state, event in {pass,fail,unreadable,setup_changed}, current setup identity. Unknown event returns no transition and is retained as invalid input.'],['Outputs','PARTIAL completion allowed','A successful observation yields start; unreadable yields a truthful paused instruction. Guaranteed completion is not asserted.'],['Consistency','VALID after repair','Single current instruction remains; no unreadable result is equated to failed setup or successful check. Old results cannot bypass a setup change.']]
body='''Interpretation 2: review the authored process for weaknesses. Exact procedure: gather→connect→select→power→check; PASS→start, FAIL→connect. New input domain adds UNREADABLE. Goal: display one current instruction, allow recovery, and never reach start without a current successful check. External inputs are a known current state and actual observation; this task supplies symbolic event fixtures, not hardware readings.

State/dependency inventory: gather requires available symbolic materials; connect follows gather; select follows connect; power follows select; check follows power; start requires check PASS. The sequence is the authored process order, not a proved physical law. Recovery FAIL revisits connect. Complete setup and a readable result are distinct subgoals: the old process covered setup but had no result-preserving action when observation was unreadable.

Six-dimension validation and report:

'''+table(['Dimension','Status','Concrete finding and resolution'],checks)+'''

Applied repair, not a proposal: single-step-interface-v2.json adds paused, UNREADABLE→paused and re-observation transitions. Paused→PASS reaches start; paused→FAIL reaches connect; paused→UNREADABLE remains paused. A setup_changed event invalidates the previous observation context and returns to connect. The artifact states that physical or human success has not been observed.

Output trace: gathering produces a setup-start state, connecting/selecting/powering produce the authored pre-check state, reading produces either a value or its absence, PASS produces start, absent information produces a pause. Therefore the goal of truthful current instruction is met in the symbolic domain; eventual setup completion is conditional on a readable successful check.

Revalidation actually executed in single-step-unreadable-traces.json: UNREADABLE then PASS yields check→paused→start; UNREADABLE then FAIL yields check→paused→connect; repeated UNREADABLE stays paused; setup change returns to connect; an out-of-domain “maybe” event has no transition. Unlike mapping every non-PASS event to FAIL, the first unreadable event no longer causes an unnecessary reconnection within this stated model. Unlike mapping it to PASS, it cannot start. This is a five-trace check of the repaired input domain, not a psychological experiment.

Overall report: VALID for declared finite transition behavior, with physical input acquisition and eventual termination conditional. Major gap resolved: no action for absent observation. Boundary retained: if absence itself is evidence of a failed component in a different device, that must be a supplied rule; this model does not infer it. No extra approval gate is invented.'''
record('pv-02','Make a missing observation change the available action without turning uncertainty into success or failure.','The existing PASS/FAIL interface is correct for its original two-value domain; UNREADABLE is a new input that has no declared transition.',body,'The actual interface now pauses and re-observes on unreadable input; its later PASS, FAIL and setup-change traces differ appropriately.','In the performed finite traces, absence no longer triggers invented failure recovery or unsupported start. This is a new implemented operation for the model interface, with no claim of human usability.','KEEP','Current-state view remains compact; the full transition table preserves recovery and observation-context dependencies for audit.','Use a delayed readable result; test a missing state separately from missing observation; supply device-specific semantics before treating unreadable as failure.')
router('wsib-03','Choose whether to read a bridge sign costing 1 minute: North costs 8 if open, East costs 12 always; sign is reliable; open probability is unknown. Distinguish expected-time from worst-time criteria.','method/decision characterization','route branches already built; observation cost boundary still unresolved',[
('md',5,5,5,5,'Derives method from the criterion and unknown prior; does not fabricate probability.'),('benf',4,5,4,5,'Calculates benefit once criterion and probability domain are explicit.'),('foht',4,4,4,4,'Tests a wider method space but direct finite comparison is enough now.'),('pv',3,4,4,4,'Checks decision procedure but cannot supply missing probability.'),('svs',3,3,3,3,'Can vary the route display; display does not resolve observation value.'),('unx',3,3,3,3,'Might reframe routes, but extra routes would alter the given task.'),('given',3,3,3,3,'A full portfolio rank delays the present criterion comparison.'),('wsib',2,2,2,2,'Another router repeats this decision.'),('crtv',2,2,2,2,'Invented bridge states would not establish value under supplied costs.'),('la',4,4,4,4,'Can expose missing prior; less direct at deriving the conditional threshold.')], 'md','benf','foht','Specified prior + expected time → calculate. Unknown prior + expected time → derive conditional threshold. Worst-time criterion → compare scenario maxima. If the simple comparison omits another action → FOHT recovery.','The unresolved item is which method follows from the criterion and available knowledge, so MD directly protects that distinction.','SVS-01 already gave the correct state branches. Total sign costs are 9 if open and 13 if closed; East remains 12. No measured open frequency or user risk preference was provided.')
rows=[['Expected-time comparison (obvious)','A probability p is available or retained symbolically.','Symbolic comparison is valid; no measured p is supplied.','Read sign iff 13−4p<12, namely p>1/4; tie at 1/4.','Assigning p=1/2 as ignorance fabricates a decision premise.'],['Minimize worst time (opposite)','The chosen criterion is worst-case duration.','Valid as a distinct stated criterion, not inferred user preference.','Sign max=13; East max=12; East wins.','This does not establish expected-time superiority when p is high.'],['Dominance frontier (cross-domain from payoff vectors)','Compare both states without averaging.','Both outcomes are supplied.','Sign=(9,13), East=(12,12); neither dominates.','A claim that information always helps fails in the closed state once its cost is included.'],['Seek a prior before choosing','A relevant observation source is available and worth its cost.','None is supplied in this finite task.','Remain conditional; an arbitrary extra survey is not executed.','A prior acquired after travel cannot improve the earlier decision.']]
obs={'sign_by_state':{'open':9,'closed':13},'east_by_state':{'open':12,'closed':12},'probability_cases':[{ 'p':p,'sign_expected':13-4*p,'east_expected':12,'expected_choice':'sign' if p>.25 else ('tie' if p==.25 else 'east')} for p in [0,.1,.25,.5,1]],'worst_case_choice':'east','unknown_p_expected_choice':'unresolved'}
(D/'route-criterion-results.json').write_text(json.dumps(obs,indent=2))
body='''Step 1 — Situation: a two-state, two-policy symbolic choice. The existing route dispatcher already chooses North when open and East when closed after reading. The unresolved question is whether reading is worth its one-minute cost before state is known. Success means preserve the declared decision criterion and unknown probability, not select a route by invented preference. Resources: exact four policy-state durations; no empirical bridge data or human preference report.

Step 2–3 — Methods, assumptions and falsifiers:

'''+table(['Method','Assumption','Fit','Executed implication','What would show misuse'],rows)+'''

Step 4 — Derived method: use a two-coordinate payoff comparison first. Because neither vector dominates, criterion matters. For expected duration leave p symbolic and derive the threshold; for worst duration compare maxima. This follows from the actual unknown p and explicit alternative criteria rather than defaulting to “information helps” or “always take the safe route.”

Step 5 — Question derivation: worst-time and expectation are genuinely different answer families; no user preference says which governs real travel. A branch implementation being correct does not settle whether paying to reveal its branch is worthwhile. The sign cost is current total travel cost, not moved outside the accounting horizon.

Actual further applications in route-criterion-results.json: with constructed p=.10, sign expected 12.6 exceeds East12; with p=.50, sign expected11 beats East12; p=.25 ties; p=0 and p=1 reproduce exact endpoints. These are declared hypothetical probabilities, not estimates. The actual output now gives a conditional threshold under expectation and a separate worst-time answer. For unknown p, expected-time choice remains unresolved. A later selection query “p=.10, minimize expected duration” now returns East; the same input p=.50 returns sign. No first-pass prediction or human travel benefit is asserted.'''
record('md-02','Let the decision criterion and probability knowledge determine the method for valuing an observation.','The route branches are already correct; reading the sign has state-dependent net value and no prior or risk preference has been supplied.',body,'The formerly unresolved observation-value question now has a symbolic p>1/4 threshold and a separate worst-time result; actual later p=.10 and p=.50 queries select different policies.','A concrete conditional calculation makes the current branch rule usable without fabricating a prior or switching criteria. New within this route-cost case; no measured real-world travel improvement.','KEEP','Payoff vector + criterion-specific result preserves more useful content than a single “read the sign” instruction. Retain the unresolved unknown-p branch.','Add a known prior only with a source; change observation cost and recompute; test a third route without silently preserving the two-policy optimum.')
