from pathlib import Path
import json
R=Path('/workspace/scratch/78b838bd97fc/mind-change-research/inquiry')
findings=[
{'id':'K1','source':'03-dd-uncertainty.md','cue':'uncertainty kind','finding':'Missing access, ambiguous meaning, conflicting evidence, and a threshold-crossing interval require different resolving observations.','scope':'current model classifications on the declared cases','exception':'No further resolution is needed merely to choose an action already invariant across the live interval.'},
{'id':'K2','source':'04-dd-attention-access.md','cue':'source segment','finding':'On-disk existence and inclusion in a combined read do not establish that the full source was emitted; instruction force differs from screen position.','scope':'observed truncation and separate source reads in this run','exception':'A complete short response needs no segmentation.'},
{'id':'K3','source':'12-fctl-sure.md','cue':'confidence entailment','finding':'Factive certainty includes truth; a confidence-expressing output does not entail truth. The source reason remains conditional on its sense.','scope':'the sure→true source reason and the stated false-string countercase','exception':'The countercase does not defeat factive certainty, and no private confidence state is inferred.'},
{'id':'K4','source':'13-fctl-fault-gates.md','cue':'causal gate','finding':'Under the declared present-event Boolean semantics, breaking one conjunct stops an AND event; every active sufficient OR branch must be disabled.','scope':'declared two-input gates and the local-copy/connector access model','exception':'Comprehensive future hazard removal is a different objective and can require more fixes.'}]
queries=[('Q1','An original source segment was omitted by truncation. Which finding controls the next operation?',['K2']),('Q2','A route is phrased confidently; the action interval still crosses its threshold. Which distinctions apply?',['K1','K3']),('Q3','The original local path is absent, but connector retrieval succeeds. Must the original path also be rebuilt?',['K1','K4'])]
chron=[x['id'] for x in findings]
index={'source segment':['K2'],'confidence entailment':['K3','K1'],'causal gate':['K4','K1']}
keys=['source segment','confidence entailment','causal gate']
trials=[]
for (qid,q,want),key in zip(queries,keys):
 # The unindexed representation requires checking all four retained entries for relevant exceptions.
 gotA=[x for x in chron if x in want];gotB=index[key]
 trials.append({'query':qid,'question':q,'expected':want,'chronological_output':gotA,'decision_index_output':gotB,'same_scoped_findings':set(gotA)==set(gotB),'chronological_entries_considered':4,'indexed_entries_considered':len(gotB)})
(R/'consolidation-01-index.json').write_text(json.dumps({'findings':findings,'index':index,'trials':trials},indent=2)+'\n')
lines=['Intended mind change: Replace the first four scoped keeps’ purely chronological access with a decision index that retains their exceptions and changes the next source-relation analysis.','','# Consolidation 01 — what kind of obstacle controls the next use?','','Inputs are only K1–K4 below. No new substantive finding enters this consolidation. The starting arrangement is the existing chronological four-record list; it is credible and preserves all evidence. The proposed alternative indexes the same findings by the concrete obstacle in the next use. Actor: the current model’s lookup/selection operation, not human reading performance.','','| Keep | Retained finding | Scope | Exception | Provenance |','|---|---|---|---|---|']
for x in findings:lines.append('| '+' | '.join([x['id'],x['finding'],x['scope'],x['exception'],x['source']])+' |')
lines+=['','Organization A: chronological records, each containing all content and exceptions. Organization B: obstacle index—source segment→K2; confidence entailment→K3 with K1; causal gate→K4 with K1. B uses multiple references instead of forcing one keep into a single exclusive category. Both retain the full source record and all exceptions.','','| Query | A result | B result | Entries inspected in the declared lookup | Outcome |','|---|---|---|---|---|']
for t in trials:lines.append(f"| {t['query']}: {t['question']} | {', '.join(t['chronological_output'])} | {', '.join(t['decision_index_output'])} | A=4; B={t['indexed_entries_considered']} | Same scoped findings |")
lines+=['','The counts are operation counts in this declared lookup, not measured reading time or a claim about model internals. A needs no new indexing work and remains useful for chronological review. B is chosen for these repeated obstacle-based queries because it supplies the same scoped findings while presenting fewer irrelevant candidates in each tested lookup. The decision does not establish an optimal organization for unknown future queries.','','Actual use: the next RLCL input is the source’s “certainty contradicts hope” relation. The confidence-entailment entry returns K3 plus K1. The model carries forward two explicit checks: identify whether certainty is factive or a confidence expression, and identify the exact proposition/time whose uncertainty is at issue. The next record therefore tests C(P,t) against H(Q,u), preserving the P=Q/t=u and P≠Q/t≠u cases separately. This is a performed input classification and is used in 14-rlcl-certainty-hope.md.','','Review: Content comparison finds no lost scope, exception, or provenance among K1–K4. Organization comparison reveals an unresolved trade-off: B’s obstacle terms must be recognized; A remains easier when the user names an application number. The repair is to retain both entry points, with B as the default for the tested obstacle queries. No additional useful distinction was found in these comparisons; no claim is made that none exists.','','Actual mind change: The next source-relation analysis uses the obstacle index and receives the factivity/operand conditions before assigning a relation verdict.','Benefit: The tested lookups return all and only their retained relevant findings with fewer candidate records presented; the following RLCL operation consumes the selected conditions. This is local organization benefit, not another independent substantive keep.','Verdict: KEEP — consolidation organization only; substantive keep count remains four.','Organization: Obstacle-indexed access plus chronological fallback, original records linked, exceptions preserved, multi-entry membership allowed. The next consolidation is due after four more distinct substantive keeps.','Next attempts: Apply the index to the certainty/hope relation; test a query naming an application number; add the next four eligible findings without erasing incompatible scopes; compare a condition-first organization if obstacle recognition fails.']
(R/'consolidation-01.md').write_text('\n'.join(lines)+'\n')
