from pathlib import Path
import json, hashlib
R=Path('/workspace/scratch/78b838bd97fc/mind-change-research/inquiry')
def put(name,text):(R/name).write_text(text.strip()+'\n')
def end(c,b,v,o,n):return f'\n\nActual mind change: {c}\nBenefit: {b}\nVerdict: {v}\nOrganization: {o}\nNext attempts: {n}\n'
put('28-rci-repeated-reason.md','''Intended mind change: Trace what produced the recurring certainty/uncertainty reason without converting a backward causal question into another recommendation about graph use.

Starting working judgment: CSCL27 established that one isolated current rule emits these tuples from tags. Historical execution of that file is unobserved. The compressed statement to interrogate is “the generator caused the original fifteen edges.” Original: ../sources/inquiry-rci.original.md and separate receipt. Interpretation 2. No numerical 8x floor exists; the questioning below traces code, data, history, copying, selection and the inquiry’s own attribution, stopping at actual observations or specifically unavailable history. User evaluation fields are outside the question-only operation.

What produced the phrase “the generator caused the original fifteen edges”? Was that a historical observation or an inference from matching output? What produced the matching-output inference? Did a test run the entire historical program, or an isolated transcription of one current rule? What caused me to use “the generator” as if those were identical objects? Is the compression hiding the version, dependencies or execution date?

What produced the fifteen tuples in the isolated execution? Which exact loops visited the certainty and uncertainty cohorts? What produced those cohorts? Were the tags read from the recovered exports? What produced the tags in those exports? Does the export receipt contain the original author’s tag-selection history? If it does not, what evidence could distinguish manual annotation from a prior generator? Is the exact current tag string the solid observation here, with its historical origin still unknown?

What produced the same reason text in each isolated result? Is the reason a literal in the source rule? What caused that literal to be chosen by the original author? Would the author’s intention be inferable uniquely from the literal? Could shorthand, deliberate broad association, a mistaken logical generalization, or an unreviewed default all produce it? What historical statement or edit history would discriminate those causes? Is any of that history present in the exact receipts? Why would present code alone answer a question about an unrecorded intention?

What else could have produced the fifteen exported tuples? Could the current rule have run? Could an earlier equivalent rule have run? Could its output have been copied? Could the tuples have been entered manually from the same rule? Could later editing preserve the same pattern? Do the matching tuples distinguish those causes? What caused me to favor the first branch? Is a simple generating account the same as a uniquely identified historical account?

What produced the absence of a duplicate sure→hope edge when a preexisting contradiction was injected? Which condition compares target and relation? Does it compare reason text? What produced preservation of the injected reason? Was the earlier row retained because the append condition failed? Where does this causal branch end: at a visible Boolean condition and observed fixture output? What remains unknown about whether that state ever occurred in the repository?

What produced the temptation to stop after exact reproduction? Was the current question already answered at the algorithmic level while the historical question remained open? Why did the word “exact” seem to cover both? What caused that appearance in the written record: equality of tuples, equality of code, or a missing event receipt? Are those three observations actually present? Does asking again for the same fifteen tuples create new historical evidence, or loop back to the existing test?

What produced the need for this interrogation now? Did the previous consolidation explicitly retain the historical boundary? Is this questioning discovering a new cause, or checking whether that boundary survived compression? What causes the stopping decision here? Are the current code/fixture branches at direct observations, the repeated reproduction branch at a loop, and the historical authorship branches at a genuine unknown? What further backward question could the available documents answer without fabricating an event?
'''+end('The historical-cause sentence remains a qualified explanation, not a verified event. Current rule behavior is still established in the isolated fixture.','The later RCA48 input now states “isolated tag-rule output” as its observed system and retains historical generation as unknown. This preserves an already established boundary; no independent new keep.','UNRESOLVED','The causal interrogation is predominantly questions with no forward recommendations inside its body; retrospective evaluation is outside it.','Inspect a real historical execution receipt if obtained; test the duplicate-edge branch separately; question another compressed cause in the timing case.'))
put('29-rci-waiting.md','''Intended mind change: Trace why information gathering acquires priority in a timing proposal, without pretending to know a human’s motives or the model’s hidden internal cause.

Starting working judgment: The live uncertainty example permits different actions in different states. I have not established that waiting is best. The reaction under examination is the concrete next-question choice “should we wait for better information?” The timing map and methods’ exact resumption capsule are the inputs. Original: ../sources/inquiry-rci.original.md and receipt; interpretation 2, no numerical 8x floor. The scope is document and decision-model causes, not inferred private emotions.

What produced the question about waiting? Was it the interval spanning a decision threshold? What produced that interval? Is it measured uncertainty about a person or a declared finite decision fixture? If it is a fixture, what caused its endpoints to be selected? Were they chosen to straddle six in DD03/IFSS25? Does that design history explain the example without explaining anyone’s anxiety?

What produced the apparent need for more information? Was there a difference between allowed actions at the interval endpoints? What produced that difference? Which comparison operator and threshold were declared? Would the same interval produce that difference with a threshold outside it? What caused the threshold to enter the description? Is it a stated decision rule, an inferred preference, or an unknown human value? Which of those actually appears in the file?

What produced the candidate “wait”? Was it imported from the when/ready route? Did the source say waiting is always optimal? What produced “ready” in that route? Does ready’s definition specify a loss function or only sufficiency? Could a semantic relation produce a useful question without determining its answer? What made me ask for a causal origin rather than a new recommendation here?

What other causes could give information gathering priority in the written proposal? A free-observation assumption? An absent deadline? An omitted cost? A requirement to explain uncertainty? A current tool that can provide evidence immediately? Are these observed reasons for a past action or candidate omitted premises? What would an actual contemporaneous decision record look like? Does the present input contain one?

What produced the assumption that a later observation can be used? Is there an initiating channel? Is the capsule a source of execution or only a source of preserved input? What produced the present capsule? Does its saved JSON identify a current next operation? What caused the exact-input repair? Was a failed string comparison observed? What caused the comparison failure: missing sentences in v1 or invalid JSON? Which observation rules out the latter? Does that repair say anything about next week’s user behavior?

What produced the cost omission in the simple interval example? Was the example meant to establish action-set invariance rather than optimal information purchase? Does reusing it for a timing decision change the problem being asked? What caused that change of problem? Does the new question require a value model that the earlier one did not contain? Can the absence of values be inferred from the actual fields rather than a theory about hidden motives?

What produced the urge to end this branch with “therefore act now”? Would that be tracing backward or moving forward? Does the causal history of an information request settle its value? What supports the stopping point instead? Are the interval and comparator declared facts, the capsule repair a observed artifact event, and any human reluctance a genuine unknown? Is repeating “why seek certainty?” merely returning to an invented motive? What question remains answerable now about the source of the written proposal?
'''+end('The next timing investigation is explicitly a decision-model extension requiring costs and opportunity conditions, not an explanation of anyone’s reluctance.','AEX34 receives the omitted-cost question with no attributed human motive. This is a prepared input change; whether it improves selection is tested there, not presumed here.','UNRESOLVED','Artifact origins, model premises, proposed omitted causes and unknowable motives remain separate in the later input.','Run the declared cost comparison; test a zero-cost boundary; inspect the capsule’s real source condition before any replay; obtain a contemporaneous human account only if such an intervention is performed.'))
put('30-src-questionroute.md','''Intended mind change: Calibrate how the recovered QuestionRoute source may support a claim, without using an overall reputation score as a probability that every edge is true.

Starting working judgment: Exact source authenticity is strong and individual edge validity is mixed. I do not expect lateral reputation evidence automatically to overturn a demonstrated counterexample. Concrete source: repository benjam3n/questionroute at 17dbbe3fea812c0cf3ed065be413ec18e6ea7ffd, 438 exact compare-data exports, generator receipts and the sure neighborhood. Assessment date: 2026-09-08. Original: ../sources/inquiry-src.original.md and receipt. No numerical 8x floor; all seven stages, five weighted dimensions, type-specific checks and multiple claim-verification routes below are applied.

Source type: author-maintained software/conceptual website and expert-style conceptual assertions, not a peer-reviewed empirical study. Lateral reading: searches for “benjam3n questionroute” and “Ben Ward reasoningtool independent review” returned no relevant independent assessment in the inspected results. This search failure is not proof that none exists. The [GitHub profile](https://github.com/benjam3n) identifies the account as Ben Ward and pins reasoningtool; it does not establish specialist credentials for every psychological or logical claim. No credential, funding or accuracy track record is invented. The available source is a GitHub repository, so an unrelated domain WHOIS check would not establish ownership of its content. The account/repository attribution is the relevant observable; an independent offline-identity confirmation is absent.

| Dimension | Score /10 | Rationale for this intended use |
|---|---:|---|
| Authority | 5 | Attributed creator of this artifact; no independently verified general expertise shown. |
| Accuracy | 5 | Exact strings and rule predictions are checkable; broad sure→truth and certainty/uncertainty reasons need semantic conditions. |
| Objectivity | 7 | Many neighboring question types are offered; source is constructing a navigation framework, not reporting a controlled neutral study. No undisclosed conflict is alleged. |
| Currency | 7 | Exact current revision retrieved; concepts need less frequent updates than service capabilities. This does not date every underlying definition. |
| Coverage | 7 | 438 distinct questions and broad links; missing scope and historical-generation evidence limit particular inferences. |

Weighted score = 5×.25 + 5×.25 + 7×.20 + 7×.15 + 7×.15 = 6.00/10. Under the original rubric this is the low end of moderate, use with verification. The number is a documented ordinal judgment, not a posterior or a validated measurement. Raising or lowering Authority by two changes the total by .5; it does not change the arithmetic countercase. Suitability differs by claim type.

| Key claim | Upstream check | Other check / independence | Status |
|---|---|---|---|
| The exports contain 438 distinct question IDs | Exact receipts and source index | Parent independently recomputed Git blob hashes for every content string and unique IDs | Verified artifact count; independent computation on same corpus, not an independent corpus |
| sure has the recorded outgoing reason | Exact sure export | Original compare generation code preserves routes | Verified attribution, not endorsement |
| every sure judgment implies truth | FCTL12 separates factive and confidence senses | Constructed false-certainty statement refutes the universal confidence-expression version | Conditional/refuted by sense; not resolved by reputation |
| sure contradicts maybe | Exact two definitions and tags | AEX33 predicate intersection at p=1 | Conditional; source intended sense unverified |
| current tag rule can produce all fifteen reason tuples | Exact generator receipt | MSS22 reproduction and CSCL27 controlled mutations | Verified isolated rule behavior; historical execution remains unverified |
| these routes improve human thinking | No outcome record supplied | No relevant independent study found in the bounded lateral search | Unverified, not refuted |

Cross-reference request: two to three genuinely independent publications on these exact private artifact claims were not found. Multiple same-repository files are upstream corroboration, not independent authorities. Formal counterexamples do not require a vote from three publications, but they also do not verify psychological generalizations. No images require reverse searching. The red flags are broad semantic reasons without operand conditions and absent outcome evidence; no personal allegation follows from them.

Distinct later application: in QAF46 the question “what does the export say?” is resolved from its primary receipt, while “did a person benefit?” stays unresolved. The 6.00 score does not block the former or answer the latter. The score is not used to reverse FCTL12 or AEX33. The prior scoped trust judgment survives this assessment.
'''+end('Source use remains claim-specific: strong for its own recorded content, conditional for reasons, untested for human benefit.','The actual later question classification preserves provenance and countercases. No independent new useful change beyond prior source/effect distinctions is shown.','UNRESOLVED','The source score is adjacent to its intended use and sensitivity, with per-claim verification available separately.','Search targeted independent assessments if a substantive human claim becomes decision-relevant; inspect a distinct graph neighborhood; retain exact source versions during future comparisons.'))
checksA=[('Bodily reaction','UNPERFORMED: no body/sensation report; do not substitute a generated feeling.'),('Felt certainty before evidence','UNPERFORMED for a person; text only reports working judgments.'),('Evidence for AR benefit','Observed: first AR KEEP was withdrawn after redundancy review.'),('Evidence against AR benefit','Observed: brief already contained its claimed distinction.'),('Written strongest countercase','Observed: CSCL26 states ordinary instruction following as a confounder.'),('Inversion of favorable claim','Observed: a successful file can contain an invalid causal edge.'),('Symmetric evidence standard','Checked: FCTL source error retained despite source-fidelity requirement.'),('Read aloud and reaction','UNPERFORMED: no human read-aloud or report.'),('External factual check','Checked: exact exports and generator receipts, not memory alone.'),('Changed decision after check','Observed: ledger keeps reflect repaired verdicts rather than first-pass success.')]
checksB=[('Specific decision','Audit decision is whether AEX33 merits K9, not whether the whole program is good.'),('Decision timeline','AEX33 follows completed dependency and source maybe definition, then finite witness.'),('Reasons before decision','Frozen issue was operand/sense compatibility; prior row did not settle p=1.'),('Emotional motive','UNPERFORMED: no human motive report; model latent cause not observed.'),('Alternative stated reason','Simpler ordinary logic could produce same witness; skill marginal causation unresolved.'),('Substitution test','If an outside author supplied p>0 and p=1, same intersection remains nonempty.'),('Costly admission','Observed: source intent still unresolved although a firmer answer would look cleaner.'),('Update condition','A source context explicitly stipulating 0<p<1 would change source interpretation, not algebra.'),('Commitment','Current SE35 input retains the overlap at p=1.'),('Human challenge response','UNPERFORMED: no person’s challenged-decision response observed.')]
checksC=[('Repeated favorable conclusion','Review K1–K9 for double counting; K9 is positive-possibility endpoint, not generic scope.'),('Recurrence of language','Repeated “scope” words do not by themselves establish repeated findings.'),('Payoff of declaring success','Possible incentive is meeting quota; it is a candidate explanation, not an observed inner motive.'),('Payoff of declaring uncertainty','Possible easier defense of a claim; countercheck still retain demonstrated finite witness.'),('Avoided counterevidence','No source intent inferred from tag alone; contrary strict-uncertainty case retained.'),('Audience substitution','Same predicate witness applies regardless of whether source is favored.'),('Read-aloud recurring pattern','UNPERFORMED: human auditory/affective observation absent.'),('Actual behavioral reversal','No human reversal claimed; model enumeration input is recorded.'),('Longitudinal recurrence','Only current-run documents exist; no repeated-life pattern inference.'),('Next independent verification','SE35 and AV50 consume exact cases; their results cannot be claimed before execution.')]
s='''Intended mind change: Detect whether quota pressure or attachment to the program has made the written record rationalize success, while preserving all original human-observation gates as unperformed.

Starting working judgment: Some early favorable verdicts were already corrected after parent review. That establishes a record defect and repair; it does not establish a human motive or subjective sensation. The concrete input is AR01, AEX02, FCTL13, CSCL26 and AEX33. Original: ../sources/inquiry-sdc.original.md and receipt. The full original was read, including body/emotion, written evidence, inversion, substitution, recurring-pattern and third-party checks. Sections A, B and C are attempted below. The source’s 8x floor is three sections, ten tests each, five lookbacks and four verifiers. Thirty text-oriented audits do not substitute for human body/read-aloud/feeling gates.

Depth status: PARTIAL — human bodily response, emotional observation, read-aloud reactions and recurring personal-pattern evidence are unavailable. Parent confirmed no existing human record can supply these. No user interruption is needed for the remaining model-output work.

'''
for name,rows in [('A — belief/evidence',checksA),('B — challenged decision',checksB),('C — recurring pattern',checksC)]:
 s+=name+'\n\n| Test | Actual operation/result |\n|---|---|\n'+'\n'.join('| '+a+' | '+b+' |' for a,b in rows)+'\n\n'
s+='''Five lookbacks: AR01 invalid necessity edges were repaired; AEX02 early benefit was demoted; FCTL13 rejected an authentic source’s gate guidance under exact semantics; CSCL26 rejected unisolated AR causal attribution; AEX33 retains source-intent uncertainty. Four distinct verifiers: original instruction comparison, exact receipt comparison, Boolean/predicate calculation, and parent semantic review. These are independent verification modes to differing degrees, not four people and not four independent causal experiments.

Third-party check on the model output (Section E, available written operations): 1 identify precise claim K9; 2 compare action/input before and after; 3 inspect adverse p=0 and p=1/2 cases; 4 separate source intent from stipulated meaning; 5 apply the same condition to an unfavored source; 6 retain simpler-logic explanation; 7 identify what would change the verdict. Steelman: a reader might already know possibility includes certainty, and thus gain nothing. Current-case evidence supports only this model’s explicit next-input change; general novelty and human gain remain unknown.

Distinct later operation: the ledger marks this record partial despite all thirty available checks being written. SE35’s benefit will not be credited merely because it repeats AEX33. No subjective experience is filled in to satisfy a source checklist.
'''+end('The model-output audit preserves the prior corrections and retains the new endpoint finding within its narrow scope. Human deception or self-knowledge remains unassessed.','The completion ledger now represents a real procedural gap rather than treating a full-length document as completed SDC. This preserves the user’s existing standard; no new keep.','UNRESOLVED','Performed written checks and unavailable human observations are individually visible; the record is partial.','Use SE35 as an actual later discriminator; review quota-driven duplicate credit; perform human gates only with real observations; revisit any newly challenged verdict.');put('31-sdc-output-audit.md',s)
put('32-dvs-search-portfolio.md','''Intended mind change: Broaden the next substantive targets without treating novelty itself as proof of benefit.

Starting working judgment: The current line has concentrated on sure/uncertainty semantics and source control. It has considered timing/access, but could converge on another variant of source-versus-endorsement. Concrete candidates for the remaining applications are below. Original: ../sources/inquiry-dvs.original.md and receipt; no numerical 8x floor. All four ordering rules and the three application steps are performed.

Solution space and distance: each candidate is coded by target (semantic, timing, access, attention, causal), object (edge, decision, file, view, event), operation (interpret, compute, retrieve, render, intervene), and evidence (formal, artifact, historical, human). Distance is the number of unequal coordinates, 0–4; it measures declared coverage, not intellectual worth. The existing reference is semantic/edge/interpret/formal.

| Candidate | Coordinates | Distance | Niche / concrete attempt |
|---|---|---:|---|
| A | semantic/edge/interpret/formal | 0 | maybe endpoint; already AEX33 |
| B | timing/decision/compute/formal | 3 | value of perfect information with delay cost |
| C | access/file/retrieve/artifact | 4 | source hash change versus semantic source change |
| D | attention/view/render/artifact | 4 | visible critical clause versus total word count |
| E | causal/event/intervene/historical | 4 | historical generator run; absent event receipt |
| F | semantic/decision/compute/formal | 2 | action tie and open endpoint |
| G | timing/event/interpret/human | 3 | subjective urgency; no human observation |
| H | causal/edge/intervene/artifact | 3 | duplicate-edge collision in isolated generator |

Novelty-first sequence begins C or D (distance four), then selects B to avoid filling only artifact-access niches, then H for a different intervention object. Niche filling retains A as best supported local semantic candidate and B/C/D/H as separate attempts; it does not discard A because it is less novel. Curiosity ordering uses actual prediction errors: definition-only edit failed to alter tags, and methods’ valid JSON v1 failed input preservation; these prioritize H and C. No numerical prediction error is invented for unperformed human G. Anti-convergence explicitly keeps E/G as unresolved distinct targets rather than forcing them into evidence available from a text file.

Actual three attempts under the selected portfolio: (1) inspected methods’ v2 capsule and compared origin-map hash with current SPD09 bytes; this source-specific difference will be rechecked after the record is amended, rather than equated with semantic change. (2) prepared the cost-bearing B comparison for AEX34, with state payoffs +6/−4, perfect information price 1. (3) selected the duplicate-edge H fixture from CSCL27 for RCA48, distinguishing target/relation collision from semantics. These are concrete input selections; only subsequent performed effects can establish new benefits.

Coverage comparison: selecting A/F plus another uncertainty gloss fills one target family and two operations; C/B/H spans access/timing/causal and retrieval/computation/intervention at the same three-slot budget. This is greater declared coverage, not proof of better discoveries. D remains the best attention niche pending U40; E remains historically blocked and G observationally blocked. Distance may exaggerate differences between equivalent operations; the explicit coordinates make that limitation inspectable.

Distinct later application: the next AEX uses timing cost (B), U40 uses attention/visible clauses (D), and RCA48 uses collision control (H), rather than spending all three on alternate labels for sure. These choices are now frozen in their input queue.
'''+end('The later-input portfolio includes timing cost, visible-clause access and duplicate-edge control; an unsupported human urgency inquiry stays open.','The chosen three slots have wider declared coverage. A better discovery yield is not yet established and the user already required breadth, so no independent new keep.','UNRESOLVED','Best available candidates are retained per niche with unresolved evidence requirements, rather than a single ranked winner.','Perform B’s cost comparison; test C’s byte/meaning distinction; enumerate D’s clause positions; retain E until an actual execution receipt appears.'))
# AEX34: independently specified timing assumptions.
types=['Causal','Existence','Stability','Access','Capability','Value','Knowledge','Resources','Permission','Timing']
cs=[
 [('Information changes expected attainable payoff, not just confidence.','Deep','High','Compute best contingent action.'),('A state S and two actions exist in the stated fixture.','Surface','Low','Declared S=success/failure, act/decline.'),('Payoffs remain +6/−4 until the delayed decision.','Deep','High','Assumed fixture; expires in boundary case.'),('Perfect state information is obtainable at price c.','Deep','High','Stipulated experiment, not real service.'),('The actor can condition its later act on the observation.','Shallow','High','Explicit decision tree.'),('Expected payoff is the selected criterion.','Surface','High','Declared hypothetical criterion, no user utility imputed.'),('The success probability p is the quantity informing expectation.','Shallow','High','p remains interval-valued, no fabricated measurement.'),('Cost c is paid even when the later action is decline.','Buried','High','Included in both branches; compare zero cost.'),('Observation purchase is authorized within the decision model.','Shallow','Low','Hypothetical action; no external purchase.'),('Information arrives before the action opportunity closes.','Deep','High','Boundary: after expiry no +6 option.')],
 [('Waiting preserves the favorable state opportunity.','Deep','High','Assumed in base model, varied in boundary.'),('A future decision time exists.','Surface','Medium','Declared t1; not an actual scheduled event.'),('p does not drift during the waiting interval.','Deep','High','Base assumption, not measured forecast.'),('A channel delivers the observation.','Shallow','High','Model perfect observation; capsule is not that channel.'),('The policy can decline after observing failure.','Deep','High','Required for perfect-information payoff 6p−c.'),('One payoff unit has the same value before and after delay.','Deep','Medium','Declared no discounting; otherwise change formula.'),('No hidden correlated cost is omitted.','Buried','High','Only c is specified; general claim remains conditional.'),('The observation budget covers c.','Surface','Medium','Base c=1; constraint can block wait.'),('No obligation forces act after buying information.','Buried','High','Base decision tree permits decline; forced act destroys information value.'),('The observation duration itself has no extra penalty beyond c.','Deep','High','Base c aggregates cost; avoid double count.')],
 [('Writing a capsule does not itself generate a future execution event.','Shallow','High','Already established; imported, no new keep.'),('The stored next operation has a specific source and input.','Surface','Medium','Methods v2 read; SP02 concrete.'),('The same user goal survives until the resumed act.','Deep','High','Unknown future; invalidation field retained.'),('The restored actor can access both source and current instruction.','Deep','High','Now readable; future environment unknown.'),('The consumer rechecks an invalidation condition rather than merely storing it.','Buried','High','Current hash comparison performed.'),('Current continuation is useful even if no later session occurs.','Surface','Medium','User’s present task authorizes actual work.'),('The next action is still pending when selected.','Deep','Medium','Status check required; methods doing SP02 now.'),('Saved state is sufficient to avoid reconstructing missing input.','Deep','High','Methods v1 failed; v2 exact input repaired.'),('A saved proposal authorizes a different future external act.','Buried','High','False as universal; current task scope still governs.'),('The opportunity has not expired when resumed.','Deep','High','Capsule declares invalidation; future unknown.')]]
s='''Intended mind change: Determine when waiting for perfect information is worth its cost, rather than infer a timing choice from unresolved probability alone.

Starting working judgment: Previous interval cases established action sensitivity but did not price information. Waiting remained a plausible candidate, not an endorsed universal rule. Concrete input: the DVS32 candidate B, RCI29’s omitted-cost question and the completed timing dependency’s capsule. For a hypothetical decision, acting returns +6 on success and −4 on failure, declining returns 0, and perfect information costs c=1. Probability p is initially allowed in [.4,.9]; these are declared model parameters, not human measurements or advice.

Original: ../sources/inquiry-aex.original.md and receipt, interpretation 1. Core claims: C1 perfect information is preferable throughout the stated interval; C2 its payoff formula survives delay; C3 preserving the next question is sufficient for later execution. Ten extraction questions per core follow.

| ID/core | Type | Assumption | Hiddenness/risk | Testability / actual result |
|---|---|---|---|---|
'''
for j,rows in enumerate(cs):
 for i,(a,h,r,t) in enumerate(rows):s+=f'| T{j*10+i+1}/C{j+1} | {types[i]} | {a} | {h}/{r} | {t} |\n'
s+='''
Assumption map: C1=T1–T10, C2=T11–T20, C3=T21–T30. The highest-priority assumptions are T8 (cost on every observed branch), T15 (ability to decline), T10/T30 (opportunity timing) and T6 (expected-payoff criterion). Normative premises are declared rather than discovered as facts. Historical or future channel availability remains unknown; current artifact checks do not establish it.

Five-edge dependency chain for the stated perfect-information policy: executing its contingent choice requires the state observation before choice (D1); D1 requires an observation delivery before the opportunity expires (D2); D2 requires an operating delivery channel during the available window (D3); D3 requires a successful initiation with required payload (D4); D4 requires its trigger’s actual preconditions to be met (D5). This is a dependency chain under the declared host-triggered method, not proof that all conceivable methods need a capsule. The present capsule records input; it does not establish D5 for a future event. At the algebraic root, expectation follows from the declared two-state payoffs; at the temporal root, later initiation is genuinely unobserved.

Immediate tests: compute E(act)=10p−4 and E(wait)=6p−1, since after observing failure the policy declines but still pays one. Therefore wait−act=3−4p. At p=.4 the values are 0 and1.4; at .75 both are3.5; at .8 they are4 and3.8; at .9 they are5 and4.4. C1 is not uniformly true on [.4,.9]. If c=0 then perfect information weakly improves the optimally chosen current action; if the chance to act expires before observation, the stipulated wait strategy loses its +6 branch. Those are different models, not counterevidence to the arithmetic under its own premises.

Distinct later application: on a newly supplied interval [.8,.9] with the same fixed payoffs and c=1, act exceeds wait at every p by .2–.6, so the model now selects act and keeps p unresolved. This is stronger than the earlier threshold-invariance result: perfect information could change a later action, yet its net value is negative at each allowed p. timing-value-tests.json records every evaluated row. SE36 receives this cost-bearing input and both the tie p=.75 and expiry boundary. No real purchase, human urgency or scheduled future act is inferred.

Depth: thirty assumptions, ten categories, more than six Deep/Buried entries and five explicit dependency edges. Already tested items cite current artifacts or prior exact tests; parameter assumptions are conditional; future user/channel behavior has no current verification. Nothing is added solely to force waiting or acting.
'''+end('The current decision model separates action sensitivity from the net value of information. On [.8,.9] the performed payoff comparison selects act while uncertainty remains.','The next timing enumeration uses a cost-bearing policy and retains its tie/expiry limits. K10 is this new local cost comparison, not another keep for the existing saved-versus-scheduled distinction.','KEEP','Probability interval, policy, observation price, opportunity window and channel evidence remain distinct. The result is hypothetical expected-payoff logic, not a claim about the user’s preferences.','Enumerate price and expiry cases; test a forced-act observation; compare a risk-averse criterion only if declared; keep actual channel evidence separate from theoretical delivery.');put('34-aex-information-price.md',s)
vals=[{'p':p,'act':10*p-4,'wait':6*p-1,'wait_minus_act':3-4*p} for p in [.4,.75,.8,.9]]
(R/'timing-value-tests.json').write_text(json.dumps({'payoffs':{'success':6,'failure':-4,'decline':0},'information_cost':1,'observations':vals,'heldout_interval':[.8,.9],'decision':'act','scope':'declared finite decision model'},indent=2)+'\n')
# The origin map is expected to change when its pending status is repaired; preserve old hash and inspect operation-source separately.
p=R/'09-spd-timing.md';s=p.read_text().replace('The GG dependency is pending and prevents completion of this application.','The exact-input GG/QAG/ARAW dependency is complete; its preserved-state candidate is inspected in the later operation below.').replace('Dependency status: PENDING.','Dependency status: COMPLETE. See ../methods/gg-02.md, gg-02-guesses.json, gg-02-qag.md and gg-02-araw.md. This reuses the same exact-input dependency and is not an extra independent GG exposure.')
s=s[:s.index('Actual mind change:')]+'''Distinct later application: AEX34 consumes the completed timing dependency and reads its exact resumption-capsule.json. The origin SPD map and next SP source have different roles: this status repair changes the origin map bytes, while SP’s original source remains independently hash-checkable. The current lookup preserves source-specific invalidation rather than inferring future resumption. The new information-price result is credited in AEX34 only; no additional SPD keep is counted.

Actual mind change: The expanded timing map feeds a completed dependency and a current capsule inspection alongside the cost-bearing timing test.
Benefit: The current operation is inspectable; no future-session effect or separate marginal benefit of the large guess inventory is established.
Verdict: UNRESOLVED
Organization: The frozen GG input is retained even as this map’s completion status changes. An origin-map edit does not silently rewrite the next original skill.
Next attempts: Recheck the exact next source before a replay; compare information price and expiry; inspect actual later execution only when a real initiating event exists.
''';p.write_text(s)
