from pathlib import Path
import json, hashlib
root=Path('/workspace/scratch/78b838bd97fc/mind-change-research')
nodes=[]
def add(parent,claim,strength='Necessary',kind='implication',bedrock='',premise=''):
    ident=f'R{len(nodes)+1}'; nodes.append(dict(id=ident,parent=parent,claim=claim,strength=strength,kind=kind,bedrock=bedrock,premise=premise)); return ident
p=add('', 'The requested sustained program—actual original Reasoningtool executions at requested depth, repeated on substantively different possible changes, with demonstrated useful changes retained and consolidated after each four keeps—is the right program to conduct here.',kind='assumed analytical claim')
a=add(p,'Success is a relation between a performed change, its consequence, and a supported concern; a completed document alone cannot settle success.',kind='commitment')
b=add(p,'The requested original procedures constrain which operations and dependencies belong to each application, while the requested outcomes constrain what those operations must address.',kind='commitment')
c=add(p,'Retention changes the resources available to later investigations, so organization is part of the program’s causal proposal rather than only its presentation.',kind='commitment')
a1=add(a,'A consequence admissible for one target is not automatically admissible for another target: model selection, reported human experience, and later human conduct assert different events.')
add(a,'FORECLOSED: Counting fifty-one documents as fifty-one useful changes when no later operation uses their outputs.',kind='foreclosure',bedrock='LOGIC: the program defines a keep by demonstrated useful change, not document count.')
add(a,'An informative failed intervention can satisfy exploration while receiving REJECT or UNRESOLVED for its intended change.',bedrock='TEST: a candidate with a failed later use must remain in the corpus without adding keep credit.')
a2=add(a1,'A record that moves from a model decision to a claim about human behavior adds an empirical dependency absent from the model decision.',kind='commitment')
add(a1,'The same observed model selection is compatible with distinct human-behavior outcomes when no human-behavior outcome is observed.',bedrock='LOGIC: the local observation supplies no premise selecting one of those human outcomes.')
add(a1,'A proposed human relocation has no observed human relocation as its consequence in this record.',kind='foreclosure',bedrock='LOGIC: no person has performed a relocation in the available task record.')
a3=add(a2,'Reuse must preserve which proposition the evidence supports; otherwise a later consumer cannot determine whether it inherited the extra human-behavior dependency.',kind='commitment')
add(a2,'FORECLOSED: Promoting a correct worked example into demonstrated transfer solely because the example was successful.',kind='foreclosure',bedrock='LOGIC: the successful example contains no observation of a distinct transfer task.')
add(a2,'A human-outcome claim remains unresolved even when the present model uses the candidate successfully.',bedrock='TEST: query this corpus for a performed human intervention; the current record supplies none.')
a4=add(a3,'An organization used for selecting future attempts must expose evidence scope at the point where an entry becomes actionable.',kind='commitment')
add(a3,'If a scoped finding is copied without its exception and the exception controls the next case, the copy no longer supplies the finding needed for that decision.',strength='Possible',premise='The removed exception is active in the next case.',bedrock='TEST: contrast a same-context retrieval case with an unseen-context transfer case.')
add(a3,'If the compressed entry omits the disputed premise and the original is its only retained source, resolving that premise requires returning to the original.',strength='Possible',premise='The disputed premise is absent from the compact entry and has no other retained source.',kind='cost',bedrock='TEST: the concrete fixture below contrasts a missing exception with an entry that already preserves it.')
a5=add(a4,'A comparison that ignores evidence scope relevant to the next selection cannot establish that a consolidation preserves that scope.',kind='commitment')
add(a4,'FORECLOSED: A one-word KEEP label that is consumed as a general recommendation without access to its actor and scope.',kind='foreclosure',bedrock='LOGIC: the label alone cannot distinguish model-local evidence from human evidence.')
add(a4,'Preserving every word is not required when the next choice depends only on a retained proposition, condition, exception, and provenance.',strength='Possible',premise='The omitted content has no bearing on the specified later choice.',bedrock='TEST: execute the same later choice against full and compact records and compare outputs.')
add(a5,'A compact entry containing only “model use succeeded” leaves the answer to “did a human perform the intervention?” unsettled; interpreting that entry as an affirmative human answer exceeds the preserved evidence.',kind='commitment',bedrock='LOGIC: the quoted entry contains no premise asserting performed human intervention.')
add(a5,'Reading cost is an outcome distinct from decision correctness; fewer inspected records with a wrong scope is a failed consolidation on that case.',kind='cost',bedrock='LOGIC: reduced retrieval does not imply preserved conclusion; both values are separately observable in a retrieval trial.')
add(a5,'A tie on observed cases leaves a trade-off unresolved instead of proving a unique best organization.',bedrock='LOGIC: equal finite observations cannot establish a strict winner.')
b1=add(b,'Source fidelity, actual execution, depth sufficiency, and useful consequence are separate constraints; satisfying one does not discharge the others.',kind='commitment')
add(b,'FORECLOSED: Replacing a named original operation with a generic eight-section essay while retaining the original label.',kind='foreclosure',bedrock='LOGIC: eight sections do not perform an omitted required operation.')
add(b,'Requested repeated applications must address different substantive targets; changing only the title or wording cannot supply the requested diversity.',kind='commitment',bedrock='TEST: compare each repeated application’s concrete input and changed operation.')
b2=add(b1,'A source with required subordinate operations creates a dependency on those operations, even if the allocation manifest omits that dependency.',kind='commitment')
add(b1,'A correct source digest establishes which bytes were read and does not establish that the written inference follows.',bedrock='LOGIC: byte identity and semantic entailment are different propositions.')
add(b1,'A numeric 8x floor from one source cannot certify another source that defines depth differently.',kind='foreclosure',bedrock='TEST: inspect the original depth definition in each source receipt.')
b3=add(b2,'The executable queue is constrained by actual prerequisites and available inputs rather than rank alone.',kind='commitment')
add(b2,'Unavailable referenced databases remain an explicit limitation on any operation that requires their content.',bedrock='OBSERVE: the local RSI bundle lists source loader, archived skills and manifest, but not the referenced questionroute or depth-map databases.')
add(b2,'An imported completed prerequisite can be reused only when its input and result satisfy the new invocation’s actual requirements.',strength='Possible',premise='The named source permits reuse and the input-sensitive requirements coincide.',bedrock='TEST: match new invocation inputs against the preserved prerequisite output; unmatched items require fresh execution.')
b4=add(b3,'Contextual priority can remain unchanged while chronological order changes to make a needed input available.',kind='commitment')
add(b3,'FORECLOSED: Claiming a dependent procedure complete while its required subordinate product is only planned.',kind='foreclosure',bedrock='LOGIC: a planned operation is not an executed operation.')
add(b3,'Reordering alone earns no keep unless it produces a useful change in an actual later operation.',bedrock='TEST: record the first dependent operation receiving a newly available input and the choice it changes.')
b5=add(b4,'The next application should be selected from ready inputs while preserving every assigned repetition as an outstanding obligation.',kind='commitment')
add(b4,'Prioritizing a useful prerequisite does not authorize deleting an expensive assigned application.',kind='foreclosure',bedrock='LOGIC: the user’s application counts remain part of the assumed program.')
add(b4,'The program can acknowledge incomplete depth without converting a source or input blocker into fictional completion.',kind='commitment',bedrock='TEST: progress entries expose completed operations and any unmet floor separately.')
add(b5,'When two assigned applications both have available prerequisites, readiness alone leaves their relative order undecided.',kind='commitment',bedrock='LOGIC: both options satisfy the same readiness condition; that condition supplies no strict ranking.')
add(b5,'The inquiry queue retains 51 application obligations after this first record; one completed obligation leaves 50, regardless of keep count.',bedrock='LOGIC: 51 minus 1 equals 50; consolidations do not discharge named-skill applications.')
add(b5,'A later audit can distinguish changed ordering from missing work because every rank/application pair remains in the queue.',bedrock='TEST: reconcile queue identities with allocation.json.')
c1=add(c,'Every four distinct demonstrated keeps create an obligation to construct and actually use a new consolidation.',kind='commitment')
add(c,'FORECLOSED: Recounting the same scoped change as several new keeps merely because different skills rediscover it.',kind='foreclosure',bedrock='LOGIC: the brief requires four demonstrated findings, not four endorsements of one finding.')
add(c,'A useful incompatibility must remain visible in consolidation because erasing it would change what the program has established.',kind='commitment',bedrock='TEST: query a keep and its exception after compression; both must remain retrievable.')
c2=add(c1,'The keep ledger therefore needs identity of the changed operation as well as application ID before a four-keep trigger can be evaluated.',kind='commitment')
add(c1,'A consolidation with no changed later use is unfinished even if its prose is concise.',kind='foreclosure',bedrock='LOGIC: the program explicitly requires actual use of the arrangement.')
add(c1,'Waiting for four keeps can delay consolidation indefinitely if outcomes remain unresolved; unresolved outcomes cannot be promoted to force the trigger.',kind='cost',bedrock='TEST: a sequence of four UNRESOLVED applications leaves the keep trigger at zero.')
add(c2,'An entry without a distinct useful consequence cannot increment the four-keep counter merely by naming an intended next use.',kind='commitment',bedrock='LOGIC: intended use is not the distinct demonstrated consequence required by the counter.')
add(c2,'If two applications change only the same classification rule on the same evidence, the second can validate reuse but adds no independent keep credit.',bedrock='TEST: compare operation identity and evidence scope before incrementing the ledger.')
add(c2,'A later record that changes a different operation—such as search coverage rather than evidence classification—can earn independent credit when its useful consequence is demonstrated.',strength='Possible',premise='The later record supplies a distinct performed change and useful consequence.',bedrock='TEST: require the later operation’s before/after output and scope.')
# Add an eighth edge to the first long path only by expanding a concrete unresolved organization question.
# The existing path is seven recursive edges from R1, so no extra nodes are required.
lookup={n['id']:n for n in nodes}
def depth(n): return 0 if not n['parent'] else 1+depth(lookup[n['parent']])
for n in nodes:n['depth']=depth(n)
children={n['id']:[q for q in nodes if q['parent']==n['id']] for n in nodes}
assert len(nodes)>=45
assert max(n['depth'] for n in nodes)>=7
assert all(len(cs)>=3 for cs in children.values() if cs)
assert all(n['bedrock'] for n in nodes if not children[n['id']])
lines=['Intended mind change: Change the inquiry actor’s immediate continuation from allocation-order execution to a dependency-aware queue whose entries distinguish source fidelity, depth, demonstrated effect, and later uptake.','', '# AR 01 — the requested program assumed right','',
'Actor and scope: This assistant’s current research queue and claims about its own records. No human intervention or model-weight change is observed. The current brief is the concrete input.','',
'Starting working judgment: I was prepared to execute the allocation in rank order, starting with AR and then proceeding through the listed skills. I already accepted the requirement for actual consequences and did not believe all techniques would work. What was unsettled was how rank, dependencies, and later uptake should interact in the next concrete record.','',
'Frozen claim: '+nodes[0]['claim'],'Assuming this is: the right approach. Interpretation: strategy commitments.','',
'Premise check: The brief requests original skill execution and the 3/2/1 allocation (verified by working-instruction.md and allocation.json). This line has 51 assigned applications (calculated from the allocation). No claim of human benefit, successful transfer, or available external database is assumed. Local archive availability was observed through rg --files. The analytical judgment that this is the right program is assumed, not established by that inspection.','',
'Original: ../sources/inquiry-ar.original.md; exact-source and current-requirements receipts: ../sources/inquiry-ar.requirements.txt. The corruption pre-inoculation source is also preserved. The source specifies 8x floors of seven levels, three implications per non-bedrock node, and 45 claims. This execution has '+str(len(nodes))+' distinct nodes, '+str(max(n['depth'] for n in nodes))+' recursive edges on the longest branch, and three children at every expanded node. Concrete leaf measurements/definitions stop their branches.','',
'## Exploration','', '| Claim | Parent | Strength / type | Derived proposition, added premise, and bedrock |','|---|---|---|---|']
for n in nodes:
    content=n['claim']+((' Added premise: '+n['premise']) if n['premise'] else '')+((' BEDROCK-'+n['bedrock']) if n['bedrock'] else '')
    lines.append(f"| {n['id']} | {n['parent'] or '—'} | {n['strength']} / {n['kind']} | {content} |")
lines+=['','## Claim registry','']
for n in nodes: lines.append(f"- [{n['id']}] {n['claim']} — TYPE: {n['kind']}; STRENGTH: {n['strength']}; PARENT: {n['parent'] or 'input'}.")
lines += ['','## Synthesis and certificate','',
'Pattern: constraining and convergent. The assumed program converges on scope-carrying records, a ready-input queue, and an independent-keep ledger. Its commitments are the necessary commitment rows above; its foreclosures are every foreclosure row; its costs are the retained provenance, separate retrieval/correctness assessment, and an indefinitely deferred consolidation when useful outcomes do not arrive. No contradiction between the frozen claim and these branches was found. That is a conditional implication result, not validation of every intervention.','',
'Findings by branch: R2 and its descendants establish a distinction between local evidence and transfer, carry that distinction into reuse, and require two scope-sensitive consolidation queries. R3 and its descendants establish independent source/execution/depth/effect constraints, source-derived prerequisites, rank/order separation, and retained application obligations. R4 and its descendants establish keep identity, triggered consolidation, and no credit for duplicate effects. These paragraphs add no propositions beyond their numbered branches.','',
'Weakest links: possible implications require an active removed exception, irrelevant omitted content, reusable prerequisite inputs, or a distinct later effect. The indicated concrete comparisons would confirm or defeat each. The claim that the whole program is best among all possible programs remains assumed. The strongest contrary possibility is that its opportunity cost exceeds its benefit; this AR does not resolve that comparative empirical question.','',
'## Distinct later operation: constructing the next input','',
'The next aex input is now the exact proposition: “A source-faithful, depth-sufficient execution that changes the present model’s next choice can qualify as a local keep even when human transfer remains unresolved.” It receives three separate fields: source/depth status, local-use evidence, and human-effect evidence. Rank-order execution alone did not specify this input or separate these claim types. The retained queue places aex-01 next, reserves ar-02 for representation access and ar-03 for continuation, and keeps every application obligation. This is a performed allocation and input-construction change, observable in continuation-queue.json; later AEX success is not pre-claimed.','',
'Prompt amendments derived from the tree: (1) attach actor/evidence scope at the point a finding becomes selectable; (2) name the distinct later operation that consumed it; (3) retain every allocated obligation while allowing prerequisite-driven chronology; (4) increment the four-keep trigger by distinct changed operation, not endorsement count; (5) when a referenced resource is absent, record the unmet operation instead of treating the receipt as execution.','',
'Actual mind change: The immediate continuation now uses a scope-carrying concrete AEX proposition and a ready-input queue. The resulting fields preserve unresolved human effects while allowing inspection of an actual model operation; this distinction was already present in the brief.','Benefit: The next application has a definite claim and evidence distinctions that prevent a local observed change from silently becoming a human-transfer claim. Benefit is limited to this input-construction/queue operation; no speed, future compliance, or human outcome has been measured.','Verdict: UNRESOLVED — changed queue/input construction is observed, but no independent new beneficial discovery is established beyond requirements already in the brief. Prior KEEP credit is withdrawn after semantic review.','Organization: The tree retains every numbered claim and the registry duplicates only for access. The working queue carries scope and pending obligations. A later consolidation remains due only after four distinct demonstrated keeps; the current new-keep ledger is 0/4.','Next attempts: Execute aex on the scoped-keep claim; apply DD to available target dimensions; apply AR to provenance-preserving representation; compare the first eligible consolidation on model-use and human-effect queries.']
(root/'inquiry/01-ar-program.md').write_text('\n'.join(lines)+'\n')
alloc=json.loads((root/'inquiry/allocation.json').read_text())
queue=[{'id':x['id'],'application':i,'rank':x['rank'],'status':'pending'} for x in alloc for i in range(1,x['applications']+1)]
for q in queue:
    if q['id']=='ar' and q['application']==1:q.update(status='completed',file='01-ar-program.md')
queue.sort(key=lambda q:(0 if (q['id']=='aex' and q['application']==1) else 1,q['rank'],q['application']))
(root/'inquiry/continuation-queue.json').write_text(json.dumps({'next_input':lines[-10] if False else 'A source-faithful, depth-sufficient execution that changes the present model’s next choice can qualify as a local keep even when human transfer remains unresolved.','fields':['source_and_depth','local_use_evidence','human_effect_evidence'],'queue':queue},indent=2)+'\n')
(root/'inquiry/ar01-nodes.json').write_text(json.dumps(nodes,indent=2)+'\n')
(root/'inquiry/progress.json').write_text(json.dumps({'line':'inquiry','assigned_applications':51,'completed_applications':1,'keeps':0,'rejects':0,'unresolved':1,'consolidations':0,'files':['01-ar-program.md'],'next':'aex-01','source_limitations':['Referenced questionroute/depth-map/pure-regress databases are absent from local RSI bundle.']},indent=2)+'\n')
print(json.dumps({'claims':len(nodes),'max_recursive_edges':max(n['depth'] for n in nodes),'branching':[len(cs) for cs in children.values() if cs],'output':'01-ar-program.md'}))
