from pathlib import Path
import json,collections
R=Path('/workspace/scratch/78b838bd97fc/mind-change-research/inquiry')
# Each group is one unbundled claim followed by four independently specified mapping products.
def write(name,intent,input_,groups,voi,load,hidden,later,verdict='UNRESOLVED',benefit='The map supplies distinct next inputs; an independent beneficial effect beyond the parent findings remains unestablished.'):
 out=[]
 for i,(ctype,claim,findings) in enumerate(groups,1):out.append({'id':i,'type':'unbundled-'+ctype,'parent':None,'text':claim})
 for i,(_,_,findings) in enumerate(groups,1):
  for kind,txt in findings:out.append({'id':len(out)+1,'type':kind,'parent':i,'text':txt})
 assert len(out)>=60
 techniques=set(x['type'] for x in out[12:]);assert len(techniques)>=6
 s=f'''Intended mind change: {intent}

Starting working judgment and concrete input: {input_}

Original: ../sources/inquiry-u.original.md and receipt, plus the previously loaded corruption protocol. Interpretation 2: unbundle the compound candidate position before judging it. The starting position is an object of inquiry, not a reported belief reversal. Mapping below records possibilities, conditions and perspectives without endorsing them; evaluation follows the complete registry. This 8x execution has twelve unbundled claims, {len(techniques)} techniques and {len(out)} numbered findings.

Phase 1 — exploration

'''
 for x in out:
  parent='' if x['parent'] is None else f' from U{x["parent"]}'
  s+=f'[U{x["id"]}] {x["type"]}{parent}: {x["text"]}\n\n'
 s+='Phase 2 — complete finding registry\n\n| Finding | Category | Parent | Recorded content |\n|---|---|---|---|\n'
 for x in out:s+=f'| U{x["id"]} | {x["type"]} | '+('—' if x['parent'] is None else 'U'+str(x['parent']))+' | '+x['text']+' |\n'
 counts=collections.Counter(x['type'] for x in out);s+='\nRegistry totals: '+', '.join(f'{k}={v}' for k,v in counts.items())+f'; total={len(out)}. All exploration IDs occur once in this registry.\n\n'
 s+='Phase 3 — synthesis using only registered findings\n\nVOI ranking: '+ '; '.join(f'{i+1}. U{u}: {why}' for i,(u,why) in enumerate(voi))+'.\nLoad-bearing assumptions: '+', '.join('U'+str(x) for x in load)+'. Hidden dimensions: '+', '.join('U'+str(x) for x in hidden)+'.\n\nCompleteness check: the mapping rotates through current model, later consumer, source author and an unobserved person where relevant; the temporal/scale entries retain boundaries. A question about an actual person remains empirically open. The declared twelve-claim bundle is mapped, but “complete space” is not claimed as a proven property of all possible real-world contexts. Specific unobserved cases remain in the registry rather than being silently removed.\n\nDistinct later application: '+later+'\n\n'
 s+=f'''Actual mind change: The working input now contains the registered alternatives and its later operation uses the cited distinction. No human internal change or model-weight update is inferred.
Benefit: {benefit}
Verdict: {verdict}
Organization: Every finding retains its parent and technique. Synthesis references the registry; later testing is separated so the pure mapping phase contains no verdicts.
Next attempts: Apply /ar to the first ranked registered claim; test its strongest boundary with a distinct case; retain source intent or human response as unresolved until actual evidence exists.
'''
 (R/name).write_text(s);(R/(name[:-3]+'.json')).write_text(json.dumps(out,indent=2)+'\n')
# U38 — option retention and interest
G=[
('explicit','A failed attempt can remain represented as an option with a failed result.', [('state','The option can be retained with its result, removed, or retained without its result.'),('category','This is an instance of retaining a tested alternative; siblings include a rejected hypothesis and a completed experiment.'),('assumption','A retained option has an identity that distinguishes it from its verdict.'),('temporal','A present failure and a later changed-condition attempt occupy different times.')]),
('bundled','Failure of one attempt does not state the status of every other attempt.', [('state','Other attempts can be untested, independently failed, or successful within another scope.'),('parameter','Number of tested attempts ranges from one to all members of a declared finite set.'),('dimension','Attempt identity and evaluation scope are separate axes.'),('perspective','A current model can track the set; a human may or may not experience encouragement from it.')]),
('implicit','Retaining an alternative can have a resource cost.', [('parameter','Retention cost may be one row, a large source bundle, or a repeated expensive operation.'),('state','Retain a pointer, retain full evidence, or regenerate from a verified source.'),('scale','A single rejected option and hundreds of rejected options create different retrieval spaces.'),('assumption','An available pointer still resolves when used; if not, its preservation is only nominal.')]),
('explicit','The source hope and sure labels can refer to distinct objects.', [('dimension','Left and right propositions can be identical or different.'),('parameter','The certainty predicate may apply to one tested outcome while the future option set has many members.'),('category','A relation between two attitudes is a binary relation; siblings include compatibility, support and tension.'),('assumption','The relation’s actual operands are supplied rather than inferred from labels.')]),
('presupposed','An attempted change has a result that can be described.', [('state','Result can be observed, ambiguous, absent or conditional.'),('dimension','Model output, source assertion and human experience are different result channels.'),('perspective','A reviewer can inspect an output without observing the user’s experience.'),('temporal','Immediate output and delayed transfer are different observations.')]),
('bundled','The selected next attempt can differ from the retained failed attempt.', [('state','Repeat unchanged, change conditions, choose a sibling, or defer selection.'),('category','A next-attempt choice is a portfolio allocation; siblings include replication and boundary testing.'),('parameter','Similarity to the earlier attempt can range from an exact replay to a new target.'),('scale','A one-slot choice and a four-slot portfolio admit different diversity constraints.')]),
('implicit','A failure can constrain a narrower proposition than the original broad goal.', [('dimension','Scope can be an input, a procedure implementation, a target class or a universal claim.'),('state','A failed implementation can coexist with an unresolved underlying idea.'),('assumption','The failure observation actually bears on the proposition being narrowed.'),('perspective','A source defender may attribute failure to implementation; a critic may target the proposition. Both require a discriminator.')]),
('meta','Interest in investigating is not the same variable as the truth of a claim.', [('category','Investigation priority is a selection judgment; truth is an epistemic property.'),('state','An interesting claim can be false, unresolved or established.'),('dimension','Novelty, tractability and consequence can vary independently of truth status.'),('temporal','A resolved false claim can still motivate a later mechanism question.')]),
('presupposed','The future alternative space contains meaningful distinctions.', [('parameter','Maybe as p>0 includes p=1; maybe as 0<p<1 does not.'),('dimension','Logical possibility and strict uncertainty are two candidate senses.'),('state','The sure/positive overlap and sure/strict exclusion occupy different cells in SE35.'),('assumption','The chosen meaning is declared for the fixture; the source intended meaning may remain unknown.')]),
('bundled','Changing conditions can change whether a replay tests the same proposition.', [('temporal','A changed source version creates a new input at a later time.'),('parameter','Change can concern price, actor, tool, semantics or opportunity window.'),('state','A replay can replicate, extend or fail to address the earlier claim.'),('assumption','The recorded changed condition is causally or logically relevant, rather than decorative.')]),
('implicit','A useful retained record must remain retrievable for a live query.', [('perspective','The next model reader needs the discriminating condition; the author may need literal fidelity.'),('dimension','Search key can be verdict, obstacle, target or source.'),('scale','Chronology and a scoped index support different corpus sizes.'),('state','A concise index can coexist with complete underlying records.')]),
('meta','Benefit from this map must be evaluated on a later operation.', [('state','The map can change an input, remain unused, or repeat what was already known.'),('assumption','A changed operation has an inspectable before/input and after/output.'),('perspective','The user’s appraisal is a separate observation from the model’s output difference.'),('temporal','Present use does not establish future transfer.')])]
write('38-u-retained-possibilities.md','Map how failed attempts, retained alternatives and interest can coexist without collapsing them into a single hope/certainty label.','RLCL14 retains a failed attempt A alongside an untested B; SE35 adds distinct positive-possibility and strict-uncertainty senses. The candidate position is that preserving failed and live alternatives may support continuing inquiry. I have evidence only for current model records, not anyone’s felt hope.',G,[(45,'the probability meaning changes which cases remain live'),(39,'the tested scope changes what failure excludes'),(33,'next-attempt choice distinguishes replay from a new target')],[15,28,39,48,52,58],[23,26,30,37,43,46,54], 'FRQ41 now asks which untested sibling remains after failure under the same declared conditions, rather than asking whether failure destroys hope. The ready AR44 input is U45/U46: assume positive possibility p>0 includes certainty and derive exact foreclosures. This changes the object of the next question; no human motivational result is claimed.')
# U39 — persistence and timing
G=[
('explicit','A capsule preserves an exact current input.', [('state','Input can be exact, truncated, paraphrased or absent.'),('category','A capsule is a stored payload; siblings include a bookmark, a command specification and a full checkpoint.'),('assumption','The restoration operation uses the saved string rather than reconstructing it from memory.'),('temporal','Preparation time and restoration time are separate events.')]),
('bundled','A next operation can be specific independently of scheduling.', [('state','Specific-unscheduled, vague-scheduled, specific-scheduled and neither are distinct states.'),('dimension','Payload specificity and initiation status are separate axes.'),('perspective','A current executor can use a ready payload; a future executor still needs initiation.'),('assumption','An observed scheduled state has an actual service acknowledgment.')]),
('implicit','The original source for a next operation can remain unchanged while its parent record changes.', [('parameter','A source hash can refer to the origin map, the next skill or an input dataset.'),('state','Origin changed/skill unchanged is observed in capsule-current-check.json.'),('dimension','Byte identity and role in the action’s validity are different axes.'),('temporal','A completion-status edit can follow the original frozen-input capture.')]),
('presupposed','The next operation has prerequisites.', [('category','Prerequisites include evidence, capability, permission and a still-valid goal.'),('state','One prerequisite may fail while other independent operations remain ready.'),('assumption','The chosen dependency graph reflects actual data/control requirements.'),('scale','A blocked local branch need not imply a blocked whole portfolio.')]),
('explicit','A future observation can arrive too late to alter a choice.', [('parameter','Arrival can precede, equal or follow an opportunity deadline.'),('state','The opportunity can persist, degrade or disappear.'),('dimension','Information accuracy and arrival time are separate dimensions.'),('assumption','The action remains feasible at the time the policy uses the observation.')]),
('bundled','Information has a price and a contingent-use policy.', [('parameter','In AEX34 c=1; c=0 and c=4 are alternative declared prices.'),('state','After observing failure the policy may decline or be forced to act.'),('dimension','Observation precision and ability to condition action are separate.'),('category','Information purchase is an option among immediate action, abstention and partial investigation.')]),
('implicit','A price can make perfect information unattractive despite action sensitivity.', [('parameter','For the declared payoff model, wait−act=3−4p.'),('state','At p=.4 wait gains; at .75 ties; at .9 loses under expected payoff.'),('assumption','Payoffs, price, probability and available actions match the declared model.'),('perspective','An expected-payoff chooser and a worst-state chooser can use different criteria on the same input.')]),
('presupposed','Noisy information needs an observation model to price its value.', [('state','Noise can be symmetric, asymmetric, state-dependent or unspecified.'),('parameter','Sensitivity and specificity may vary independently.'),('dimension','An “80% accurate” label can conceal a base rate and asymmetric errors.'),('assumption','Conditional observation probabilities are available for the expected-value calculation.')]),
('bundled','The goal may change before the saved operation resumes.', [('temporal','A later user instruction can alter a previously appropriate next step.'),('state','The old result remains historical even if the current recommendation is invalidated.'),('perspective','The later user can value a different target from the present model’s pending queue.'),('assumption','The resumed operation reads the current governing instruction.')]),
('implicit','A preserved queue can contain completed and pending entries.', [('state','An entry can be pending, performed, blocked or superseded.'),('dimension','History retention and next-choice eligibility are separate properties.'),('category','This is a state-transition system; siblings include build queues and study protocols.'),('scale','Selecting one ready item differs from asserting the whole program will complete autonomously.')]),
('explicit','The actual current model can perform a ready next operation now.', [('state','Tool execution, written proposal and human assignment have different observed statuses.'),('perspective','A host returns an operation result; a human may inspect it later without being its executing actor.'),('assumption','The required tools and source are currently available for that operation.'),('temporal','Current tool completion is not a receipt for a future session.')]),
('meta','A timing method’s value must include what it causes to happen and what it costs.', [('dimension','Elapsed delay, paid resource and foregone opportunity are distinct cost candidates.'),('state','A representation can improve restoration while leaving execution unobserved.'),('assumption','An actual comparison does not credit a hypothetical future act as performed.'),('category','Timing evaluation is both a control question and a decision-value question.')])]
write('39-u-continuation-value.md','Map the independent roles of stored input, initiation, information quality and opportunity value.','AEX34 provides the paid-information model; SE36 row9 shows missing noisy-signal likelihoods; the actual capsule hash check has changed origin bytes and unchanged next-skill bytes. The candidate position is that a sufficiently complete checkpoint makes later work worthwhile and ready. Its stored/current aspects are observed; later execution and value are open.',G,[(43,'a noisy information price needs conditional observation data'),(21,'source roles decide which mismatch matters'),(37,'the cost comparison depends on the full payoff model')],[15,20,27,32,39,44,48,55,59],[18,23,31,35,43,50,57], 'FRQ42 uses U43/U44 to ask for a likelihood-specific information-value bound; QAF47 separates the source-role dependency from scheduled initiation. The next original AR45 input is the conditional statement that noisy evidence cannot be priced uniquely from a headline accuracy number alone.')
# U40 — attention and source boundaries
G=[
('explicit','A targeted view can expose a critical instruction.', [('state','Critical clause may be shown, outside the window or absent from the source.'),('parameter','Window size in SE37 is one, three or six clauses.'),('category','Targeted reading is an access operation; siblings include full reading and indexed retrieval.'),('assumption','The selected clause really is the one relevant to the current question.')]),
('bundled','Its limiting exception can be outside the same view.', [('state','Critical clause visible/exception absent is SE37 row2.'),('dimension','Main instruction visibility and qualifier visibility are separate axes.'),('parameter','The exception can precede, follow or reside in another section.'),('assumption','The consumer knows which separate clause qualifies the selected instruction.')]),
('implicit','An adjacent overlap can restore a nearby qualifier.', [('parameter','One-clause overlap changes shown indices from [11] to [10,11] in row3.'),('state','Overlap can restore the exception, add irrelevant text or still miss a distant exception.'),('dimension','Physical adjacency differs from semantic dependency.'),('category','Qualified-span retrieval is a dependency retrieval operation; siblings include citations and linked definitions.')]),
('presupposed','The source distinguishes instruction force.', [('state','A clause may be mandatory, optional, conditional or descriptive.'),('dimension','Visibility and normative force vary independently.'),('perspective','A source author’s suggested next step and the user’s direct instruction can carry different authority.'),('assumption','The reader resolves governing instruction priority using actual context.')]),
('explicit','Full bytes can still be stale or semantically wrong.', [('state','Current accurate, current inaccurate, stale still-applicable and stale inapplicable are possible.'),('dimension','Byte identity, currency and semantic validity are distinct.'),('category','Source verification includes identity checking and claim testing as different operations.'),('assumption','A hash comparison answers identity, not the truth of a source claim.')]),
('bundled','A compact representation changes what remains easy to retrieve.', [('parameter','A view may contain one clause, a qualified span, a neighborhood or a whole document.'),('state','Compression can omit duplicates, irrelevant context or decisive exceptions.'),('perspective','A literal lookup and a scope-sensitive inference need different portions.'),('scale','The whole corpus and a single relation have different indexing needs.')]),
('implicit','The source’s numeric depth floors do not define benefit.', [('state','A record can meet a floor and be redundant, or have a useful partial result.'),('dimension','Procedural completion and demonstrated benefit are separate judgments.'),('assumption','The original floor is actually read rather than inferred from a title.'),('temporal','A dependency may complete after its parent map was first written.')]),
('presupposed','The model’s visible input is not identical to a person’s attention.', [('perspective','A model fixture reports displayed indices; a person’s notice or comprehension requires observation.'),('state','A human can notice, overlook, misread or correctly apply a visible qualifier.'),('dimension','Availability, attention, interpretation and action are separate variables.'),('assumption','A human-effect claim has a relevant measurement rather than a generated feeling.')]),
('explicit','Repeated retrieval can have a cost.', [('parameter','Cost can count requests, tokens, elapsed time or human effort.'),('state','An exact small follow-up can repair a truncation; repeated irrelevant reads may add no information.'),('scale','A single missing clause and hundreds of dependencies create different strategies.'),('assumption','The measured cost corresponds to the real constrained resource.')]),
('bundled','An exception can change the domain of a claim rather than negate it.', [('state','The claim can hold within its condition and fail outside it.'),('category','This is restricted quantification; siblings include universal claims and existential witnesses.'),('dimension','Domain restriction and evidential confidence are distinct.'),('assumption','The qualifier is applied to the proposition it actually modifies.')]),
('implicit','A retrieval policy can follow explicit semantic dependencies.', [('state','A critical clause can link to an adjacent exception, a distant definition or an external premise.'),('parameter','Dependency depth can be zero, one or several links.'),('dimension','Link existence and target access are different properties.'),('assumption','A dependency cycle is detected rather than recursively fetched forever.')]),
('meta','The better unit of access depends on the next question.', [('state','A title lookup may need one phrase; an applicability test may need its condition and exception.'),('perspective','A reviewer may prefer complete provenance while a current selector needs a small qualified unit.'),('temporal','A later query can require detail irrelevant to the current one.'),('assumption','The representation retains a path back to omitted source context.')])]
write('40-u-qualified-attention.md','Map how targeted access can preserve or lose a clause’s qualifying context.','SE37’s literal retrieval fixture has a visible clause at index11 and its exception at10; a one-clause targeted read omits the exception and one-clause overlap restores it. I already knew source access can differ from visible output. The live issue is whether adjacency overlap is sufficient as the next retrieval unit, without claiming a human attention effect.',G,[(23,'adjacency may not coincide with the semantic dependency'),(53,'a distant qualifier needs a different retrieval operation'),(49,'a condition changes scope rather than merely confidence')],[16,20,28,32,39,44,48,52,56,60],[18,23,26,30,38,43,51,55], 'On a distinct fixture with critical clause11 and a qualifier at2, adjacency overlap [10,11] still omits2; explicit dependency retrieval [2,11] includes both. qualified-access-tests.json records this performed comparison. QAF46 now asks whether the qualifying dependency is known before selecting a retrieval window. This changes a model retrieval operation, while source correctness and human comprehension remain separate.', 'KEEP','The actual second fixture rejects adjacency as a sufficient proxy for semantic dependency and changes the selected retrieval from [10,11] to [2,11]. K11 is this specific operational change; the earlier generic source/visibility distinction receives no new credit.')
(R/'qualified-access-tests.json').write_text(json.dumps({'parent_fixture':{'critical':11,'qualifier':10,'targeted':[11],'overlap':[10,11]},'later_fixture':{'critical':11,'qualifier':2,'adjacent_overlap':[10,11],'explicit_dependencies':[2,11],'adjacent_qualified':2 in [10,11],'dependency_qualified':2 in [2,11]},'scope':'deterministic displayed-index retrieval; not human comprehension'},indent=2)+'\n')
print('Three U applications written: 12 claims and 60 findings each; all registry IDs preserved.')
