from pathlib import Path
import json
R=Path('/workspace/scratch/78b838bd97fc/mind-change-research/inquiry')
data=json.loads((R/'questionroute-original-exports.json').read_text());M={x['data']['question']['id']:x for x in data};C=json.loads((R/'questionroute-original-chains.json').read_text());CM={x['data']['id']:x for x in C}
specs=[(6,'sure','How sure should this model be before acting on a finding whose effect is established only in the present example?','certainty / epistemic / sufficiency','L2, a recurring class of model decisions',{'certainty','epistemic','sufficiency','uncertainty'},'I expected the confidence question to route mostly toward truth and corroboration. I had not inspected the graph’s actual threshold expansion or its potentially ambiguous prerequisite reason.','The medium-weight sure→enough expansion opens a distinct action-threshold question while high-weight sure→true keeps a truth question open. The selected next target is now a pair: “What is established?” and “Would the unresolved remainder change this reversible action?” The original route reason “Being sure requires that the underlying claim is true” is carried into FCTL as two candidate meanings: factive warranted certainty and subjective/report certainty. No route weight is treated as truth evidence.','fctl on the sure→true reason; qaf on truth versus action threshold; aex on unknown premises','No new keep: the graph has supplied specific candidate questions, but their useful effect requires the later FCTL and threshold application.'),
(7,'when','When can a saved continuation state actually lead to another performed mind-change attempt?','temporal / preparedness / possibility','L2, a recurring continuation problem',{'temporal','preparedness'},'I could answer with a next-session timing phrase. That would leave the mechanism of resumption unspecified; the existing DD already identified the distinction, so rediscovery is not a new keep.','The graph’s ready-or-not chain ends in can after ready, when, and now. On the concrete saved-state case, “now” is false for an idle future model but “can on an explicitly resumed session” remains conditional on the actual host. The next question becomes “Which available channel initiates the saved state?” The present active run continues through its existing tool channel. Saved files remain available records and do not become scheduled acts.','frq on initiator; ar on preserved resumption state; mss on active/resumed/automated models','No new keep: this graph path refines a continuation question already separated in DD 03; no new future act has occurred.')]
for num,root,q,types,level,ts,start,use,skills,credit in specs:
 rec=M[root]['data'];neighborhood=[x['data']['question'] for x in data if x['data']['question']['semanticType'] in ts]
 lines=[f'Intended mind change: Reorient the next concrete question through the original graph’s actual neighborhood for “{root}”, preserving the input’s scope.','',f'# QR {num-5:02d} — {q}','','Starting working judgment: '+start,'','Raw question: '+q,'Core: '+('What confidence is enough for action?' if root=='sure' else 'At what condition/time does continuation become possible?'),f'Semantic type: {types}. Abstraction: {level}. Actor: present inquiry model; no human response or future run is observed.','','Original skill: ../sources/inquiry-qr.original.md, requirements: ../sources/inquiry-qr.requirements.txt. Graph: authorized benjam3n/questionroute export at tree 17dbbe3fea812c0cf3ed065be413ec18e6ea7ffd. The requested data/questions and data/routes paths are absent from current main; the repository’s own 438 public/compare-data exports preserve question definitions, outgoing route reasons/weights, and chain/sequence references. Exact fetched content and blob receipts are in questionroute-fetch-receipts.json. This is an authentic changed source representation, not a recreated graph. The 8x floor is structural, not numerical: full semantic neighborhood, all outgoing routes and one further hop, full applicable chain/sequence analysis, and abstraction-adjusted skill mapping.','','## Full matching neighborhood','', '| Node | Type / level | Source definition | Match to exact input |','|---|---|---|---|']
 for x in neighborhood:
  match=('Primary keyword and topic fit; abstraction two levels higher than input' if x['id']==root else 'Action threshold; strong secondary' if x['id']=='enough' and root=='sure' else 'Related concept; not substituted for exact question')
  lines.append(f"| {x['id']} | {x['semanticType']} / L{x['abstractionLevel']} | {x['definition']} | {match} |")
 lines+=['',f"Nearest node: {root}; text: {rec['question']['text']}; definition: {rec['question']['definition']}. Match quality: moderate because the core keyword matches but the generic L4 node omits the concrete actor and action condition. Secondary candidates: "+('enough (action threshold), known (established evidence), certain (strong certainty)' if root=='sure' else 'ready (preparedness), continuation (after completion), continuous (uninterrupted activity)')+'. Every supplied node remains available in the preserved 438-node registry.','','## All outgoing routes and their second hop','','These are source-provided inquiry directions, not certified entailments. Priority is source weight within type; all routes are retained at 8x.','', '| Hop | From | Type / weight | Target and definition | Source route reason |','|---|---|---|---|---|']
 edges=[]
 for edge in sorted(rec['outgoing'],key=lambda e:({'high':0,'medium':1,'low':2}[e['weight']],e['type'],e['targetId'])):
  edges.append((1,root,edge))
  for e2 in M[edge['targetId']]['data']['outgoing']:edges.append((2,edge['targetId'],e2))
 for hop,src,e in edges:
  tq=M[e['targetId']]['data']['question'];lines.append(f"| {hop} | {src} | {e['type']} / {e['weight']} | {tq['id']}: {tq['definition']} | {e['reason']} |")
 lines += ['',f'Coverage: {len(rec["outgoing"])} first-hop edges, {sum(h==2 for h,_,_ in edges)} second-hop edges. Repeated target IDs and cycles are preserved as routes, not new independent findings. Incoming neighbors: '+', '.join(x['sourceId']+' ('+x['type']+')' for x in rec['incoming'])+'. Their definitions are available in the complete export; outgoing traversal follows the original specified direction.','','## Chains and sequences','']
 refs=rec['chains']+rec['sequences']
 for ref in refs:
  z=CM[ref['id']]['data'];seq=z.get('links',z.get('steps'));defs=[M[x]['data']['question']['definition'] for x in seq]
  lines+=['- '+z['id']+': '+' → '.join(seq)+'. '+z.get('composedText',z.get('name'))+'. Members: '+'; '.join(x+': '+de for x,de in zip(seq,defs))+'.']
 if root=='sure':
  lines+=['','Chain comparison: adversarial-maybe-sure keeps an uncertainty opposition; should-you-really adds normative rightness; truth-seeking moves through existence, truth, challenge, certainty, and rightness. The action threshold appears in sure→enough but is absent from the short truth-seeking sequence. Therefore the exact input retains the threshold branch alongside the truth sequence. The “sure contradicts hope” reason is not treated as contradiction without matching proposition and time: certainty about a past event and hope about a future event can coexist.']
 else:
  lines+=['','Chain comparison: dialectic-always-never-when distinguishes conditional timing from universal timing. ready-or-not ends in ability; challenge-from-should asks capability before how/when, while timing-sequence tracks before/now/after without a capability check. breadth-first-from-action also includes body, stillness, identity, and continuation; these preserve relevant human target directions without asserting a bodily change in this model. On the concrete saved-state case, ready-or-not exposes a missing initiator that timing-sequence alone does not answer.']
 lines += ['','Skill mapping at the concrete L2 scope: '+skills+'. These are selected uses named by actual input fit; suggestions alone are not claimed as executions.','', 'Distinct later application: '+use,'','Certificate: exact claim—the selected graph path supplies a candidate inquiry direction for this input. The source definitions and route rows establish that the direction exists in the original graph. They do not establish truth of the route’s explanatory reason or the benefit of following it. Strong contrary branch: the generic abstraction can displace the concrete question; retaining the complete raw question and action condition prevents that displacement in this record. Remaining dependency: actual later test of the chosen question.','', 'Actual mind change: '+('The next factual test concerns the two meanings of sure, and the next decision question concerns action thresholds.' if root=='sure' else 'The continuation question now names the initiating channel as well as time, without claiming a future act occurred.'),'Benefit: '+credit,'Verdict: UNRESOLVED','Organization: Original routes, candidate interpretations, and selected later question are kept distinct. All one-hop-further edges and applicable chain members remain accessible; the selected short path does not delete the larger graph.','Next attempts: Test a high-weight route reason; apply the chosen question to a distinct concrete case; compare a direct ordinary answer; inspect an incoming-neighbor direction if the selected outgoing path leaves the input unanswered.']
 (R/f'{num:02d}-qr-{root}.md').write_text('\n'.join(lines)+'\n')
 print(num,root,len(neighborhood),len(edges),len(refs))
