from pathlib import Path
import json
R=Path('/workspace/scratch/78b838bd97fc/mind-change-research/inquiry')
def write(name,intent,start,section,reframes,levels,candidates,selected,answer,benefit,verdict):
 s=f'''Intended mind change: {intent}

Starting working judgment and concrete input: {start}

Original: ../sources/inquiry-frq.original.md and receipt. Interpretation 2: reframe a candidate question. The original 8x floors are twelve candidates, six reframes, at least four of five validation tests and five levels; the selected question is repaired to five of five and actually pursued below. The levels are progressively more specific dependencies of the live question, not a claim that each is a causal depth.

Step 0 / selected source branch: {section}

Six materially different reframes:

'''
 for i,x in enumerate(reframes,1):s+=f'{i}. {x}\n'
 s+='\nFive-level question development:\n\n'
 for i,x in enumerate(levels,1):s+=f'{i}. {x}\n'
 s+='\nCandidate validation. A=changes the next operation; S=scope permits a determinate answer; H=the answer is sought through a discriminating check rather than chosen to validate a preferred verdict; L=the necessary lower question is included; V=answerable by available evidence/analysis. H is an output-method check, not a claim about hidden motives.\n\n| ID | Candidate question | A/S/H/L/V | Result / repair |\n|---|---|---|---|\n'
 for i,(q,scores,result) in enumerate(candidates,1):s+=f'| Q{i} | {q} | {scores} | {result} |\n'
 s+='\nFinal formulation:\n\nQUESTION: '+selected[0]+'\nWHY THIS QUESTION: '+selected[1]+'\nWHAT A GOOD ANSWER LOOKS LIKE: '+selected[2]+'\nFIRST STEP TO ANSWER IT: '+selected[3]+'\n\n'
 s+='Distinct later application: '+answer+'\n\nActual mind change: '+selected[4]+'\nBenefit: '+benefit+'\nVerdict: '+verdict+'\nOrganization: Candidate questions, failed validation tests, the repaired selected question and its actual answer remain separate. No new result is introduced by a score alone.\nNext attempts: Test the nearest live boundary; reject a question whose answer would repeat existing evidence; preserve unanswerable human or historical questions as unresolved instead of inventing answers.\n'
 (R/name).write_text(s)
write('41-frq-failure-scope.md','Find a question that distinguishes a new attempt from a replay after a failed instance.', 'U38 retains failed A and an untested B. The current candidate question “can hope survive failure?” is too broad to answer from the available model record; no human emotional response is supplied. I can instead test the scope of a proposed new operation without treating that as hope.', 'Section E: given problem is to continue changing the model’s working state after an attempt fails. E1: the human-emotion wording is a symptom of a scope ambiguity, the present model is an investigator/actor on records rather than a human subject, and the user explicitly accepts negative/unresolved outcomes rather than requiring validation. E2 redirects to Section A: trying to select a distinct next attempt, but replication and changed-condition extension can be confused. A2c/A4 compare replay (comparability, less novelty) with changed conditions (new boundary, weaker replication claim); the current horizon is the next actual application, whose aim is a different possible change.', ['Affect: did a person experience hope after failure?','Logical scope: what did the failure exclude?','Replication: does the next case preserve conditions?','Extension: what new condition changes the proposition tested?','Resource choice: which untested sibling is worth its cost?','Representation: can failed and live alternatives be retrieved together?'], ['What should follow failure?','Which part of the attempt failed?','Which exact proposition did that result bear on?','Does the next case preserve the proposition and conditions?','Does changing the information price from1 to0 retest the same optimal-delay claim or test a boundary of it?'], [
('Does failure destroy hope?','0/0/1/0/0','Human meaning and observation absent.'),('Should we always continue?','1/0/1/0/0','Scope and cost absent.'),('Which current attempts failed?','1/1/0/1/1','Already recorded; literal retrieval only.'),('What failure means for every skill?','1/0/1/0/0','One instance does not supply whole-domain evidence.'),('Is an exact replay a new exposure?','1/1/1/1/1','Answerable classification, no new effect by itself.'),('Is a changed price a different condition?','1/1/0/1/1','Literal answer already known.'),('Can one failed implementation leave an idea unresolved?','1/1/0/1/1','Already established scope distinction.'),('Which missing observation would show a human response?','1/1/1/1/1','Answerable design, performance remains absent.'),('Would an unrelated target broaden the portfolio?','1/1/0/1/1','DVS32 already answers declared coverage.'),('Can a live option remain in the index with a failed verdict?','1/1/0/1/1','Existing representation already does this.'),('Does changing price preserve the tested timing claim?','1/0/1/1/1','Four of five: specify exact claim and changed price.'),('For AEX34, does c=0 test the same claim as c=1 or its price boundary?','1/1/1/1/1','Selected precise classification and calculation.')], ('For payoffs +6/−4 and p=.9, does changing perfect-information price from1 to0 reproduce or extend AEX34’s paid-information comparison?','It fixes whether the next application is being credited as replication or as a different timing condition.','Two calculations and an explicit scope comparison.','Evaluate act=10p−4 and wait=6p−c for both c values.','The next case is labeled a price-boundary extension, not an independent replication of the paid-information result.'), 'The model computes act=5, wait(c=1)=4.4 and wait(c=0)=5.4. The action preference changes because the cost condition changes. AR45 receives the label “extension under changed price” for this case rather than “replication disproving AEX34.” Both original results remain compatible. The calculation tests a new condition, but its price sensitivity was already preserved in AEX34/SE36.', 'The later record now describes the comparison with its correct scope. No independent new keep is awarded for the already known zero-cost boundary.','UNRESOLVED')
write('42-frq-signal-value.md','Find the missing question that determines whether a noisy observation is worth buying.', 'SE36 cannot calculate a noisy signal’s value from its unspecified likelihood. U39 notes that headline accuracy can conceal asymmetric errors. The working judgment is that more detail may matter, but the decision relevance for the concrete payoff case has not yet been tested. Hypothetical prior p=.5, act payoff +6/−4, decline0 and signal price1 are fixed.', 'Section C: expected a priced information choice from the supplied “80% accurate” label, but the calculation has no unique likelihood inputs. C2 three candidate causes: omitted base rate (test by fixing p=.5), omitted conditional error rates (construct same-accuracy alternatives), omitted response policy (explicitly allow act/decline after each signal). With base rate, payoffs and policy fixed, the conditional-error branch is the live gap. Section F evaluates candidate repairs.', ['Truth: is the accuracy label correct?','Identification: does it determine a confusion matrix?','Value: do different matrices produce different best payoffs?','Policy: can the actor decline after negative evidence?','Timing: does the observation arrive before expiry?','Robust decision: do all allowed matrices recommend the same purchase choice?'], ['Should we buy information?','What decision and payoffs can information change?','What observation outcomes and conditional probabilities are specified?','Can two conditional models share the same reported accuracy?','At p=.5 and cost1, can two 80%-accurate signals reverse buy versus act-now?'], [
('Is more information good?','1/0/1/0/0','Unpriced, unspecified aim.'),('Is 80% accurate enough?','1/0/1/0/0','Enough for which payoff/policy?'),('Is the prior known?','1/1/0/1/1','Fixed .5 here; no missing input.'),('Can the same accuracy hide asymmetric errors?','1/1/1/1/1','Answerable but still needs decision relevance.'),('Would a better signal help a person?','0/0/1/0/0','No human outcome model supplied.'),('What is the source’s intention?','0/1/1/0/0','No source author needed for this declared fixture.'),('Is waiting free?','1/1/0/1/1','Cost1 is explicit.'),('Can we act after a negative signal?','1/1/0/1/1','Policy permits act/decline; explicit.'),('Does the signal arrive before the deadline?','1/1/0/1/1','Fixed timely arrival in this comparison.'),('Which sensitivity/specificity pairs give accuracy .8 at prior .5?','1/1/1/1/1','Upstream constructive question.'),('Do those pairs change the best policy value?','1/0/1/1/1','Four of five; fix payoff, price and prior.'),('Can two such pairs reverse purchase preference under +6/−4, prior .5, price1?','1/1/1/1/1','Selected and executed.')], ('At prior .5, act payoff +6/−4 and signal cost1, can two binary signals with the same overall accuracy .8 recommend opposite purchase choices?','A changed answer would tell the next selector whether the headline label is sufficient for this decision.','Two exact conditional models, their accuracy, optimal signal policy and net expected payoff.','Compare sensitivity/specificity (.6,1) and (1,.6) with the same prior and payoffs.','The selector no longer treats overall accuracy .8 as sufficient input: two compatible likelihood models reverse its purchase decision.'), 'The performed calculation in signal-value-tests.json gives model A sensitivity .6, specificity1, accuracy .8. Positive-signal payoff contribution is .5×.6×6−.5×0×4=1.8; negative contribution if acting is .5×.4×6−.5×1×4=−.8, so decline after negative. Gross best signal payoff1.8, net .8. Model B sensitivity1, specificity .6, accuracy .8: positive contribution3−.8=2.2; negative contribution0−1.2=−1.2, so decline. Net1.2. Acting now yields1 in both. Thus A recommends act now and B recommends buy. The subsequent AR45 input now assumes this exact non-identification and derives its conditions. These are designed finite decision models, not measured signal performance.', 'K12: an actual paired-model test changes the required input of the next decision calculation; headline accuracy, fixed prior and price still fail to identify the purchase choice. The new finding is conditional on declared expected payoffs and timely contingent action.','KEEP')
# Actual arithmetic, not only recorded text.
obs=[]
for label,se,sp in [('A',.6,1),('B',1,.6)]:
 p=.5;price=1;pos=p*se*6-(1-p)*(1-sp)*4;neg=p*(1-se)*6-(1-p)*sp*4
 gross=max(pos,0)+max(neg,0);now=max(10*p-4,0)
 obs.append({'model':label,'sensitivity':se,'specificity':sp,'prior':p,'accuracy':p*se+(1-p)*sp,'positive_act_contribution':pos,'negative_act_contribution':neg,'gross_best_signal':gross,'net_signal':gross-price,'best_now':now,'choose':'buy' if gross-price>now else 'now'})
(R/'signal-value-tests.json').write_text(json.dumps(obs,indent=2)+'\n')
# Required consolidation after the fourth post-C2 keep (K9-K12), before using that result further.
(R/'consolidation-03.md').write_text('''Intended mind change: Make the four new findings retrievable by the exact missing condition they resolve while retaining all earlier keeps and exceptions.

Starting working judgment: Consolidation02 kept obstacle and warrant views without a proven winner. The new findings K9–K12 add meanings, cost, dependency position and conditional signal models. Only those findings and K1–K8 are admitted here; no new substantive claim is generated.

K9 (AEX33): sure=p=1 overlaps positive possibility p>0, whereas strict uncertainty excludes1; source intent unresolved. K10 (AEX34): paid perfect information can lose despite contingent action value; with +6/−4,c1 and p in[.8,.9], act dominates. K11 (U40): adjacent overlap can omit a distant qualifier; explicit dependency indices retain it in the tested view. K12 (FRQ42): same accuracy .8 and prior .5 can support opposite buy decisions at cost1 because error asymmetry changes payoff.

Organization A, chronology: AEX33→AEX34→U40→FRQ42. Organization B, missing condition: predicate boundary→K9; information cost→K10; qualifier location→K11; conditional likelihood→K12. Both link to exact source/test artifacts and preserve K1–K8 through consolidation01/02. Neither removes unresolved source intent, hypothetical payoff scope or absent human outcomes.

Four concrete retrieval trials: “does positive maybe include certainty?” reaches K9; “does costly perfect information always help?” reaches K10; “is one-clause overlap enough for distant qualification?” reaches K11; “is .8 accuracy enough to price this signal?” reaches K12. Both organizations retrieve the same four findings and their limits. Chronology needs up to four candidate entries in a sequential lookup (1+2+3+4=10); the explicit condition key selects one per trial (4). These are candidate-entry counts under the stated lookup operations, not cognitive-speed measurements. Chronology remains useful for reconstruction; the condition index is chosen for the next decision query.

Actual use: AR45’s exact input query is “what if overall accuracy does not identify the likelihood needed for this purchase decision?” The condition index returns K12 plus its fixed-prior/cost/action conditions. It also returns K10 for a changed-price boundary, without merging the two results. FRQ43’s distant-qualifier question returns K11 and its display-only limit. Earlier K1–K8 remain accessible and unchanged.

Actual mind change: The next AR45 input is retrieved by its missing conditional likelihood, and the attention question by the qualifier dependency, with their source and scope attached.
Benefit: The tested index uses fewer candidate-entry inspections for these four exact queries while returning the same findings and limits. This is an organization improvement under the declared lookup test, not a new substantive keep or proof of universal superiority.
Verdict: KEEP
Organization: Condition lookup is the current action view; chronology remains available for historical reconstruction. No further improvement was found in these four comparisons, not a proof that none exists.
Next attempts: Test an ambiguous condition query; inspect a query spanning K10/K12; retain a nonmatching query unresolved instead of forcing it into the index.
''')
write('43-frq-qualifier-retrieval.md','Find the question that makes a targeted clause usable when its condition is not adjacent.', 'U40’s current retrieval operation now follows an explicit qualifier at index2 for a clause at11. Adjacency has already failed in that fixture. The unsettled extension is a clause with two qualifying dependencies, one absent; I have no basis to assume retrieving the known one completes applicability.', 'Section B: starting a new applicability check. B1 success means the output identifies all supplied conditions relevant to the selected clause and preserves any missing premise as unresolved. B2 assumptions: the clause identity is correct, dependency list is complete, targets are accessible, force is understood, and source/current-goal scope aligns. Least certain is dependency completeness in the new two-premise fixture. The check is model retrieval, not a human reading intervention.', ['Window size: show more nearby text.','Topology: follow declared qualifier links.','Completeness: ask whether all required links are listed.','Access: retrieve the known missing target.','Applicability: test whether the present conditions satisfy the rule.','Trust: distinguish source identity from rule validity.'], ['Can the instruction be applied?','Which conditions qualify it?','Which qualifying clauses are represented?','Which represented dependencies are available?','For clause11 requiring conditions2 and7, what verdict follows when2 is true and7 is unavailable?'], [
('Should the view be longer?','1/0/1/0/1','Longer need not reach exact dependencies.'),('Is index2 enough?','1/0/1/0/1','Need declared condition set.'),('Did one-clause overlap fail?','1/1/0/1/1','Already tested in U40.'),('Will a person notice two clauses?','0/0/1/0/0','Human observation absent.'),('Is every source instruction true?','0/0/1/0/0','Overbroad and separate from access.'),('What are the declared dependencies of clause11?','1/1/1/1/1','Given {2,7}; foundational lookup.'),('Is clause7 available?','1/1/1/1/1','New fixture declares it unavailable.'),('Could clause7 change applicability?','1/1/1/1/1','Test true and false cases under conjunction.'),('Are all unavailable clauses equally relevant?','1/0/1/0/1','Specify exact rule and query.'),('Would fetching all text prove the rule valid?','1/1/0/1/1','Known identity/semantic distinction.'),('Can we apply11 after retrieving2?','1/0/1/1/1','Four of five: state both conditions and rule.'),('If11 requires2 AND7, 2 is true and7 unknown, is applicability determined?','1/1/1/1/1','Selected exact partial-information question.')], ('If clause11 requires conditions2 AND7, and2 is true while7 is unavailable, is applicability determined?','The next retrieval operation must target a condition that can actually change the answer.','Two completions of condition7 with different rule outputs.','Evaluate true AND true and true AND false.','The new retrieval target is condition7; the current applicability result remains unresolved instead of treating the retrieved subset as complete.'), 'The model computes 1∧1=1 and1∧0=0. With condition2 fixed true, the unavailable condition7 is decision-relevant; QAF46 now schedules its retrieval before an applicability conclusion. If condition2 were false, 0∧x=0 would settle inapplicability without7 under this declared rule. This is a new fixture extending K11, but partial-information short-circuiting will be evaluated separately before any new keep.', 'The later question order now targets the unresolved condition that can change the output. The general missing-premise distinction was already established; no independent new keep is claimed here.','UNRESOLVED')
print(obs)
