from pathlib import Path
from math import prod
import json
R=Path('/workspace/scratch/78b838bd97fc/mind-change-research/inquiry')
specs=[dict(num=3,name='uncertainty',intent='Replace one undifferentiated unresolved label with distinctions that change which observation would resolve a concrete case.',start='I could accurately label each seed below unresolved. That label did not yet distinguish ambiguous meaning, unavailable evidence, conflicting testimony, or a decision threshold.',domain='uncertainty relevant to the next act of interpretation',
seeds=['S1: “Continue next time” has session-resume and autonomous-future interpretations.','S2: A named question-route file has not been located.','S3: Two hypothetical measurements report incompatible values for the same stipulated variable.','S4: A stipulated cost interval of 4–9 crosses an action threshold of 6.','S5: A valid conditional inference depends on an unverified premise.','S6: A known effect has an unsettled value for the user.','S7: The needed source is identified but the actor cannot access it now.','S8: A conclusion is settled while its intervention deadline has passed.'],
dims=[('Target','meaning; fact; decision','S1/S6 contrast',False),('Logical status','affirmed; denied; open','S5 conditional versus premise',False),('Interpretive multiplicity','single; multiple','S1 competing readings',False),('Evidence conflict','absent; present','S2/S3 contrast',False),('Numerical dispersion','narrow; wide','S4 interval',False),('Provenance identity','identified; unidentified','S2 named source vs unattributed report',True),('Evidence dependence','shared origin; independent origins','two repeated receipts versus two independent observations',True),('Threshold relation','same action throughout; action changes','S4 threshold',True),('Action reversibility','reversible; irreversible','S6 reversible draft vs irreversible act',True),('Access','now; delayed; unavailable','S2/S7 contrast',False),('Time sensitivity','stable; expiring','S5/S8 contrast',True),('Resolution burden','low; high','local read vs a fresh longitudinal observation',False)],
methods=['Pair comparison: S2 lacks a located item; S3 has items whose contents conflict. Adding another interpretation cannot by itself retrieve S2’s file.','Minimal pair: keep a probability interval fixed and move the decision threshold outside it; inferential uncertainty stays fixed while action uncertainty disappears.','Universal scan: WHO separates model and human claimant; WHAT supplies target; WHEN supplies expiry; WHERE supplies access; WHY supplies threshold/value; HOW supplies evidence route; HOW MUCH supplies dispersion. Actor is retained as metadata because it does not replace any twelve-axis value.','Boundary probe: S8 is epistemically settled yet operationally closed; “uncertain” cannot describe its obstacle without misclassification.','Counterfactual inversion: two identical source receipts can be numerous while evidence origins remain one; count and independence separate.','Cross-domain transfer: an unverified premise in a proof and an unavailable route file both block an inference, but only the latter is repaired by locating a file.','Interaction pruning: “no numeric quantity” makes dispersion inapplicable rather than zero; “no action at stake” makes threshold relation inapplicable.'],
tests=['Independence 1: S4’s interval remains 4–9 while threshold moves from 6 to 12; only threshold relation changes.','Independence 2: a named source changes from accessible to inaccessible with its content and provenance fixed; access changes alone.','Independence 3: two matching statements can derive from one original or two independently obtained observations; agreement remains fixed, dependence changes.','Independence 4: the same settled instruction is encountered before or after its deadline; logical status stays fixed, expiry changes.','Completeness: S1=multiplicity; S2=provenance/access; S3=conflict; S4=dispersion/threshold; S5=logical-status dependency; S6=target/value; S7=access; S8=time. No seed requires conflating action readiness with truth confidence.'],
use='On three actual next targets, the representation produces different next observations: missing QR data → locate the archive; “continue next time” → preserve session-resume/autonomous alternatives and inspect available continuation capability; matching source-requirements digests → check common origin before treating repeated receipts as independent support. The resulting operation selections are recorded in uncertainty-routing.json. This is a model classification on these stated inputs, not measured human reasoning improvement.',
change='The next observation is now conditioned on uncertainty type; a settled truth with expired access is not routed to more truth testing.',benefit='Three distinct obstacles now receive observations capable of resolving their own missing premise. The scalar unresolved label alone did not specify those observations.',verdict='KEEP',boundary='When all candidate actions are the same across the unresolved interval, this classification supplies no reason to delay.'),
dict(num=4,name='attention-access',intent='Change source-reading attention from treating a combined tool response as one available object to tracking which source segments were actually emitted without truncation.',start='I requested CLAUDE, PIPELINE, rejected examples, and AR together. The returned message visibly truncated the combined output. I could use the emitted material, but the response did not establish reading of the hidden segment.',domain='availability and attention in a model’s received source representation',
seeds=['S1: Combined source response includes an explicit truncation marker.','S2: PIPELINE is subsequently read in its own complete response.','S3: CLAUDE lines 270 onward are separately retrieved.','S4: An original skill has stdout and a separate requirements stderr stream.','S5: A source includes a mandatory INVOKE below its main operations.','S6: A source includes a numerical depth table far below its opening description.','S7: A repeated requirements body appears after every skill receipt.','S8: A document reference names a file not present in the bundle.'],
dims=[('Availability unit','whole response; source segment','S1/S2',True),('Position','opening; middle; ending','S5/S6',False),('Assembly','combined; separate','S1/S2',False),('Relevance','required; optional; incidental','INVOKE vs integration suggestion',False),('Surface salience','prominent; buried','header vs lower table',True),('Dependency direction','prerequisite; consequence; neither','S5',False),('Budget relation','fits; exceeds','S1',False),('Novelty','new; repeated','S7',False),('Reference location','inline; external','S4/S8',False),('Instruction force','mandatory; suggested','INVOKE vs “use with”',True),('Verification state','read; merely present','S3 vs unavailable middle',True),('Provenance layer','original; current requirement','S4',True)],
methods=['Pair comparison: S1’s combined response and S2’s separate response differ in emitted availability, not source existence.','Universal scan: WHO=current model reader; WHAT=source segment; WHEN=before execution; WHERE=stdout/stderr; WHY=source operation fidelity; HOW=separate reads; HOW MUCH=received size.','Minimal pair: move a mandatory invocation from opening to ending while preserving its wording; force remains mandatory and salience changes.','Boundary probe: a fully preserved file can have an incompletely emitted response; on-disk existence does not establish attended content.','Failure inversion: reading only the depth table satisfies numerical awareness while omitting the source’s required products; the unavailability problem is not repaired by counts.','Cross-context analogy: a table row and its footnote can jointly specify a result; reading the row alone leaves a condition absent. This is a structural analogy, not a claim about human memory.','Source-role decomposition: identical requirement text across receipts is reusable as instruction content, while each source-specific digest remains distinct evidence that needs comparison.'],
tests=['Independence 1: S5’s invocation wording stays fixed as its screen position changes; force is independent of position.','Independence 2: stdout and stderr may each fit while their combination exceeds a response budget; source length and assembly interact rather than denote the same dimension.','Independence 3: a repeated body stays mandatory; novelty varies without changing instruction force.','Independence 4: the same external reference can point to available or absent files; reference location does not settle availability.','Completeness: S1=budget/assembly; S2=verification; S3=segment; S4=provenance; S5=force/dependency; S6=position; S7=novelty; S8=reference/access.'],
use='The next source reads are partitioned by actual byte length and invocation-sensitive sections. The earlier missing CLAUDE segment and complete PIPELINE are read separately in the transcript. Required next operations are now extracted from the source body, so SPD’s explicit GG invocation is queued while DD’s “next steps” suggestion is not silently treated as the same force. The invocation classification is a new representation of actual text positions and modal force.',
change='Attention is allocated to emitted segments and instruction force; an available file is no longer counted as a fully received source solely because it was included in one command.',benefit='The specific omitted-source risk from the truncated response is repaired by separate reads, and mandatory/suggested continuations are distinguished in the subsequent operation queue.',verdict='KEEP',boundary='A complete short response needs no segmentation; extra partitioning would add work without repairing an observed omission.'),
dict(num=5,name='timing-control',intent='Separate when an action is beneficial from whether the present model can make that later action occur.',start='The request describes sustained work and future uses. I can continue this run and write a handoff now; I have no observation that an idle future session will spontaneously execute a saved instruction.',domain='timing, access, and control of later mind-change opportunities',
seeds=['S1: Read the next skill now in this active run.','S2: Save a specific unresolved claim and its source for a later resumed session.','S3: Request a reminder via an actual supported scheduler.','S4: Leave “revisit later” in prose with no trigger.','S5: Wait for a source file currently unavailable.','S6: Propose that a person try a different physical setting.','S7: A continuation tool exists but requires an input not yet known.','S8: A reversible draft can be prepared before a future decision deadline.'],
dims=[('Actor','model; person; service','S1/S3/S6',False),('Time relation','now; before trigger; after trigger','S1/S8',False),('Trigger','explicit event; clock; none','S2/S3/S4',False),('Control channel','active tool; saved context; human action','S1/S2/S6',False),('Availability','ready; contingent; blocked','S5/S7',False),('Authority','authorized; unestablished','S1 vs person-directed change',False),('Reversibility','reversible; irreversible','S8',False),('Opportunity duration','persistent; expiring','S5/deadline',True),('State payload','specific; underspecified','S2/S4',True),('Resume condition','known; unknown','S7',True),('Acknowledgment','observed; absent','tool success vs prose',True),('Failure visibility','detectable; silent','S3 status vs S4',True)],
methods=['Pair comparison: S2 and S4 both concern later work, but S2 preserves a concrete claim/source while S4 does not identify a resumption state.','Universal scan: WHO provides actor; WHAT provides payload; WHEN trigger/time; WHERE control channel; WHY intended opportunity; HOW supported mechanism; HOW MUCH opportunity duration.','Minimal pair: the same reminder text with and without a successful scheduler response preserves wording but changes acknowledgment and external execution basis.','Boundary probe: S1 changes what happens now even without a long-term trigger; future mechanism is not a prerequisite for all sustained work.','Failure inversion: a perfect future plan with an unknown required recipient/input is not presently executable through its selected channel.','Cross-domain analogy: a saved computation and a scheduled computation contain the same parameters but differ on what initiates execution; analogous only in control structure.','Dependency decomposition: S8 preparation consumes current access; later decision consumes the saved draft; the deadline can block the latter without invalidating the historical preparation.'],
tests=['Independence 1: a specific payload may have no trigger; specificity does not imply execution.','Independence 2: a trigger may fire with a missing input; timing does not imply readiness.','Independence 3: a reversible draft and irreversible send can occur at the same time; time does not determine reversibility.','Independence 4: a task can remain authorized after its opportunity expires; authority does not imply benefit at every time.','Completeness: S1=active-now; S2=payload/resume; S3=clock/service; S4=none/silent; S5=blocked; S6=human; S7=unknown-condition; S8=before-trigger/reversible.'],
use='The next continuation description now names two actual products: the current active queue and a saved unresolved claim with source path. It does not represent either as a scheduled future act. For the hypothetical physical-setting candidate, the action is classified “person must perform; no performance observed.” For a reminder candidate, a successful scheduler acknowledgment would be required before the claim “scheduled” becomes true. No reminder is requested by this bounded assignment, so none is created.',
change='Timing and control are represented separately in the next AR continuation target: “A saved handoff can preserve a resumption state while leaving resumption itself contingent.”',benefit='The distinction avoids predicting spontaneous future work from a saved file. This duplicates an explicit standard in the input and has not yet produced an independently useful new result.',verdict='UNRESOLVED',boundary='An active continuation within this run is already occurring and should not be withheld merely because no future trigger is installed.')]
for s in specs:
 lines=[f"Intended mind change: {s['intent']}",'',f"# DD {s['num']-2:02d} — {s['domain']}",'',f"Starting working judgment: {s['start']}",'','Actor: the current model. The concrete examples below are observations where explicitly identified and otherwise stipulated cases; no invented human outcome is attributed to them. Original: ../sources/inquiry-dd.original.md; requirements: ../sources/inquiry-dd.requirements.txt. 8x source floors: 12 dimensions, seven sources/methods, five hidden dimensions, four validation tests. This record has twelve axes, seven distinct discovery operations with outputs, five or more dimensions hidden by the initial coarse representation, and five validation products.','',*s['seeds'],'','Discovery products:','']
 lines += [f'{i}. {v}' for i,v in enumerate(s['methods'],1)]
 lines+=['','| # | Dimension | Values | Concrete origin | Hidden relative to starting representation |','|---|---|---|---|---|']
 for i,d in enumerate(s['dims'],1):lines.append(f"| D{i} | {d[0]} | {d[1]} | {d[2]} | {'yes' if d[3] else 'no'} |")
 size=prod(len(d[1].split(';')) for d in s['dims'])
 lines+=['',f'Nominal finite product: '+ ' × '.join(str(len(d[1].split(';'))) for d in s['dims'])+f' = {size:,} combinations. This is an upper bound on the declared value grid, not a count of coherent real situations. Inapplicable fields and coupled constraints prune cells. Actor and provenance stay attached even when they are not an independent search axis.','','Validation products:','']+[f'{i}. {x}' for i,x in enumerate(s['tests'],1)]
 lines+=['','Distinct later application: '+s['use'],'','Certificate: The twelve-axis representation distinguishes the stated minimal pairs while retaining each seed. Its successful classifications establish representational distinctions on those inputs. The strongest contrary branch is that a plain unresolved label is sufficient when no action differs; the boundary below preserves that case. No human transfer or globally optimal taxonomy follows.','',f"Actual mind change: {s['change']}",f"Benefit: {s['benefit']}",f"Verdict: {s['verdict']}",f"Organization: Axes are separate from cases and invalid combinations; the later use consumes only dimensions that change its operation. Boundary: {s['boundary']}",'Next attempts: Enumerate concrete combinations of these axes; apply the representation to a held-out case; compare a smaller representation that retains the decisive distinctions; test whether another domain requires an unrepresented axis.']
 (R/f"{s['num']:02d}-dd-{s['name']}.md").write_text('\n'.join(lines)+'\n')
(R/'uncertainty-routing.json').write_text(json.dumps({'actor':'current inquiry model','routes':[{'input':'missing QR data','type':'access/provenance','next_observation':'locate original archive','status':'unresolved'},{'input':'continue next time','type':'interpretive multiplicity/control','next_observation':'compare session-resume and autonomous continuation against actual capability','status':'unresolved'},{'input':'repeated requirement digests','type':'evidence dependence','next_observation':'identify common source before treating repetition as independent support','status':'unresolved'}]},indent=2)+'\n')
