from pathlib import Path
import json,collections
R=Path('/workspace/scratch/78b838bd97fc/mind-change-research/inquiry')
class Tree:
 def __init__(self,root):self.n=[{'id':1,'parent':None,'claim':root,'certificate':'Declared input, checked in the cited fixture.'}]
 def children(self,parent,rows):
  ids=[]
  for claim,cert in rows:
   i=len(self.n)+1;self.n.append({'id':i,'parent':parent,'claim':claim,'certificate':cert});ids.append(i)
  return ids
 def save(self,name,intent,start,context,synthesis,later,benefit,verdict):
  children=collections.defaultdict(list)
  for n in self.n:
   if n['parent']:children[n['parent']].append(n['id'])
  depth={1:0}
  for n in self.n[1:]:depth[n['id']]=depth[n['parent']]+1
  assert len(self.n)>=45 and max(depth.values())>=7 and all(len(x)>=3 for x in children.values())
  s=f'''Intended mind change: {intent}

Starting working judgment and concrete input: {start}

Original: ../sources/inquiry-ar.original.md and separate receipt, plus the loaded corruption protocol. Facts are verified first against the exact source and prior test receipts; the formal model premises below are explicit. No choice is presented as a necessary implication. This 8x search has {len(self.n)} numbered claims, {max(depth.values())} parent-child edges on its deepest path and three children at every expanded node. The certificates state the additional declared context needed for each implication. “Necessary” means necessary inside that context, not an unconditional claim about humans or all possible programs.

Declared context: {context}

Phase 1 — exploration

'''
  for n in self.n:
   parent='INPUT' if n['parent'] is None else 'R'+str(n['parent']);leaf='; BEDROCK: concrete logic/test under declared inputs' if n['id'] not in children else ''
   s+=f'[R{n["id"]}] Parent {parent}; NECESSARY/conditional on declared context{leaf}. {n["claim"]} Certificate: {n["certificate"]}\n\n'
  s+='Phase 2 — complete registry\n\n| ID | Parent | Depth | Classification / endpoint |\n|---|---|---:|---|\n'
  for n in self.n:s+=f'| R{n["id"]} | '+('input' if n['parent'] is None else 'R'+str(n['parent']))+f' | {depth[n["id"]]} | necessary within model; '+('expanded into '+', '.join('R'+str(x) for x in children[n['id']]) if n['id'] in children else 'logical/test bedrock; original claim and certificate above')+' |\n'
  s+='\nAll numbered exploration claims occur in the registry. No probability of empirical transfer is inferred from logical certainty. Foreclosures are those explicitly stated in the claims, not a blanket recommendation to discard other interpretations.\n\nPhase 3 — synthesis\n\n'+synthesis+'\n\nDistinct later application: '+later+'\n\nActual mind change: '+intent+' The actual outcome is the scoped later-operation result above; already known parent findings are not counted again.\nBenefit: '+benefit+'\nVerdict: '+verdict+'\nOrganization: The numbered tree preserves premise dependencies and separate leaf tests. Synthesis introduces no new result; choices and their observed use are outside the implication tree.\nNext attempts: Change one decisive premise; test a new scope without calling it a replication; retain unobserved human or historical effects as unresolved.\n'
  (R/name).write_text(s);(R/(name[:-3]+'-tree.json')).write_text(json.dumps({'nodes':self.n,'depth':depth,'max_edges':max(depth.values()),'children':dict(children)},indent=2)+'\n')
# AR44: a candidate exhaustive semantic filter on a declared finite domain.
t=Tree('On D={0,1/2,1}, S(p) iff p=1 and M(p) iff p>0 permit the joint case p=1; the exact tag reason does not change these stipulated predicates.')
a,b,c=t.children(1,[('The input contains a joint S-and-M witness at1.','Substitute1 in both root predicates.'),('The same predicates have no joint witness at0.','S(0)=false and M(0)=false.'),('At1/2, M holds while S does not.','1/2>0 and1/2≠1.')])
d,e,f=t.children(a,[('The qualifying set W={p inD:S(p) and M(p)} contains1.','The parent supplies1 and1∈D.'),('The same p=1 does not satisfy strict U(p):0<p<1.','Declared strict predicate excludes its upper endpoint.'),('The joint witness occurs at D’s upper endpoint.','D’s greatest value is1 and parent witness is1.')])
g,h,i=t.children(d,[('A candidate filter that deletes every joint S-and-M case deletes1.','The policy Q is explicitly defined to remove all W before answering the existence query.'),('An existence query over the unfiltered D has answer yes.','A member1 of W is an existential certificate.'),('A source relation label cannot make this stipulated witness disappear.','The formal predicates and domain are held fixed independently of the source label.')])
j,k,l=t.children(g,[('After Q, its retained domain D1 does not contain1.','Deletion of1 is precisely nonmembership in the post-filter domain.'),('Q has removed the only possible S witness on D.','S holds iff p=1; the deleted point is unique for S.'),('Changing a route’s display weight without changing Q cannot restore1.','Q’s inputs are domain and joint predicate, not display weight.')])
m,n,o=t.children(j,[('Every later stage defined only to select a subset of D1 also excludes1.','Subset membership cannot add an absent element.'),('Sorting D1 by any key cannot itself add1.','Sorting is a permutation of retained elements.'),('Counting surviving candidates does not measure how many qualifying candidates Q removed.','The surviving set lacks the deleted witness; count alone contains no deletion log.')])
p,q,r=t.children(m,[('After any finite sequence of subset-only stages,1 remains absent.','Induction: base D1 lacks1; each subset stage preserves absence.'),('An alternative stage that explicitly reintroduces1 is outside the subset-only premise.','Adding an absent element violates subset containment.'),('Changing the name of a surviving item is not restoration of the original probability value1.','Item identity in this fixture is its probability value, not its display name.')])
s,u,v=t.children(p,[('A final existence test limited to these survivors returns no joint S-and-M witness.','All S witnesses require1, which the parent excludes.'),('That final no-witness answer differs from the original-D query answer yes.','R9’s original witness and parent exclusion concern different domains.'),('The false-negative behavior depends on answering the original query from only the pruned domain.','If the query instead explicitly asks about survivors, its no-witness answer is true.')])
# Eight additional expansions, each on a different concrete boundary or observable.
t.children(b,[('At0, positive possibility is false.','0>0 is false.'),('At0, strict uncertainty is false.','Strict0<p condition fails.'),('At0, retaining a navigation link would not constitute a joint-predicate witness.','A link is separate from the false predicates at the tested point.')])
t.children(c,[('M does not imply S on D.','The parent supplies a specific counterexample1/2.'),('An existence test for M alone accepts1/2.','The tested predicate is M and it holds there.'),('The fact that M alone accepts1/2 does not certify the conjunction there.','S is false at the same point.')])
t.children(e,[('S and strict U are disjoint on the aligned probability domain.','S requires1 while U excludes1.'),('Replacing positive M by strict U changes the predicate tested.','Their values differ at the parent point1.'),('A strict-U counterexample cannot refute the positive-M joint witness.','It changes the parent predicate, so its false output addresses a different statement.')])
t.children(f,[('Removing the upper endpoint from D removes this S witness.','The witness equals the removed endpoint.'),('Keeping the upper endpoint while removing1/2 preserves the joint witness.','Its value1 is still admitted and both predicates still hold.'),('A test restricted to interior probability values can miss this endpoint overlap.','S has no interior witness while its endpoint witness exists.')])
t.children(h,[('A single valid witness is sufficient for this existential answer.','Existential semantics require at least one, not a majority.'),('Adding p=1/4 to the domain cannot destroy the existing witness.','The expanded set still contains1 and predicates remain fixed.'),('Counting non-witnesses cannot overturn a verified existential witness.','Existence is not a vote across domain points.')])
t.children(i,[('A definition change could alter compatibility even if the source label stayed fixed.','Compatibility is computed from predicates; strict U versus positive M differs at1.'),('A label change could leave compatibility fixed if the predicates stayed fixed.','The held-fixed computation does not consume that label.'),('The author’s intended meaning remains a different unresolved question.','The root is a stipulated model, and no author-context premise has been added.')])
t.children(k,[('A complete scan of D1 cannot find an S witness.','All S witnesses in D were the deleted point1.'),('More repeated scans of unchanged D1 cannot repair this absence.','Each scan receives the same witness-free domain.'),('Recovery needs a changed candidate domain or a separate retained certificate for the original query.','With both absent, the original witness is unavailable to this defined test; either supplied path changes that limitation.')])
t.children(l,[('A high-weight copy of a surviving non-witness remains a non-witness.','Weight is not an input to S or M.'),('A low-weight retained1 would still be a valid witness if Q were changed to keep it.','Predicates do not consume weight, while retention is explicitly changed.'),('Weight-only repair and membership repair are different interventions on this fixture.','One leaves Q’s output fixed; the other changes the admitted point.')])
assert len(t.n)==46
# Actual later tests run independently from the prose tree.
D=[0,.5,1];W=[x for x in D if x==1 and x>0];pruned=[x for x in D if not(x==1 and x>0)];later=sorted(pruned,reverse=True)
(R/'ar44-filter-tests.json').write_text(json.dumps({'D':D,'witnesses':W,'pruned':pruned,'later_sorted_subset':later,'original_exists':bool(W),'survivor_exists':any(x==1 and x>0 for x in later),'scope':'candidate filter, not a claim the current assistant already used it'},indent=2)+'\n')
t.save('44-ar-positive-possibility.md','Preserve the endpoint witness through candidate filtering when the question asks whether joint certainty and positive possibility can exist.','K9 already established the endpoint overlap. U38’s retained-alternative question now tests the consequence of a candidate semantic-exclusion filter modeled after the source’s contradiction label. I have not claimed this candidate filter was previously used by the current model.','All probabilities refer to the same actor, proposition and time. D={0,1/2,1}; S=p=1; M=p>0; strict U=0<p<1. Candidate Q removes all S∧M cases before an existential query about the original D. Downstream stages in the deep branch are explicitly subset-only, unless a boundary changes that premise. The exact source reason is preserved as attribution, with intended pragmatic sense unresolved.','R2/R5/R9 retain the positive witness; R6 and its expansion separate strict uncertainty. R8/R11/R14/R17/R20 establish the candidate-pruning false negative under subset-only continuation. Weight and repeated scanning do not restore a removed candidate (R13 and R12 expansions). These are logical consequences of the explicit candidate policy, not claims about all graph navigation.','The model ran ar44-filter-tests.json: original query true, Q’s survivors [0,.5], later sorted survivors [.5,0], final joint test false. The next HT51 candidate set keeps original-domain existence separate from survivor-domain existence. The already established K9 is not counted again.','The candidate filter’s loss is inspectable and the next test preserves the correct query domain. This is an extension of K9, not an independent new keep.','UNRESOLVED')
# AR45: consequences of identified signal ambiguity, plus exact regret boundary.
t=Tree('At prior .5 and fixed +6/−4 payoffs with price1, two binary signal models A=(sensitivity.6,specificity1) and B=(1,.6) have accuracy.8 but strictly different optimal purchase actions.')
a,b,c=t.children(1,[('A summary-only deterministic selector receives identical input in A andB.','Declared summary contains prior, payoffs, price and overall accuracy, all equal.'),('Act-now is optimal among buy/now in A, and buy is optimal in B.','FRQ42 exact net values are A:.8 versus1 and B:1.2 versus1.'),('The conditional observation distributions differ even though overall accuracy matches.','The root gives different sensitivity/specificity pairs.')])
d,e,f=t.children(a,[('A deterministic function of that identical summary returns the same choice in both models.','Equal inputs to a deterministic function have equal outputs.'),('Repeating the unchanged summary supplies no distinction between A andB.','Each repetition contains the same values.'),('The identical accuracy label alone does not identify the confusion matrix.','A andB are distinct matrices consistent with that label and prior.')])
g,h,i=t.children(d,[('That same buy/now output is suboptimal in at least one of A orB.','R3 establishes opposite strict optima; one common choice cannot equal both.'),('A fixed always-buy selector loses .2 relative to the optimum in A.','A buy=.8 while now=1.'),('A fixed always-now selector loses .2 relative to the optimum in B.','B now=1 while buy=1.2.')])
j,k,l=t.children(g,[('No deterministic selector restricted to that summary is optimal in both admitted models.','Any such selector has a common output, and the parent covers both possible actions.'),('Choosing a more confident label for the same output does not remove its .2 payoff deficit in the losing case.','Confidence label is not part of the fixed payoff calculation.'),('A claim of uniform optimality must therefore change an admitted condition or acquire a distinguishing input.','With model set, summary and criterion fixed, the parent contradiction remains.')])
m,n,o=t.children(j,[('Adding a new feature that is constant across A andB leaves the selector inputs identical.','Concatenating equal summary with an equal constant preserves equality.'),('An observed feature that identifies A versusB would remove this particular ambiguity.','The selector could choose the model’s known strict optimum from R3.'),('Relaxing uniform optimality to a regret objective changes the guarantee being requested.','The criterion no longer requires zero loss in each model.')])
p,q,r=t.children(m,[('A deterministic selector using the summary plus that constant feature still returns the same action in both models.','The parent preserves identical full input; deterministic equality applies again.'),('An additional description of “80% reliable” derived only from accuracy is one such constant feature.','It is a fixed function of the equal accuracy value.'),('More decimal places on the unchanged .8 value are also nondiscriminating here.','Exact root accuracy is equal, not merely rounded equality.')])
s,u,v=t.children(p,[('The constant-feature augmentation still leaves at least one strict .2 loss among the admitted models.','Its common action is either buy or now; R9/R10 give the corresponding losing model.'),('The augmentation cannot truthfully certify zero regret for both models.','The parent provides a nonzero-loss case.'),('A narrower model set containing only A or only B removes the two-model contradiction but adds a model-identification premise.','A single retained model has one specified optimum; exclusion of the other is additional information.')])
# Eight side expansions; meaningful decision conditions and regret rather than verdict relabeling.
t.children(b,[('A’s positive-signal gross contribution is1.8 and its negative contribution if acting is−.8.','Direct products .5×.6×6 and .5×.4×6−.5×1×4.'),('B’s positive contribution is2.2 and its negative contribution is−1.2.','Direct products .5×1×6−.5×.4×4 and0−.5×.6×4.'),('Declining after negative signals is optimal for both models under the declared linear payoff.','The negative contribution is below0 and declining yields0 there.')])
t.children(c,[('At prior .5, both accuracies equal half the sum of sensitivity and specificity, namely.8.','Each pair sums to1.6.'),('The shared accuracy constraint permits more than the two displayed matrices.','Sensitivity a in[.6,1] and false-positive rate a−.6 preserve.8.'),('The two displayed matrices therefore establish non-identification without proving they exhaust the source’s possibilities.','Two witnesses suffice for nonuniqueness; no exhaustive-source premise is given.')])
t.children(e,[('An exact repeated display is not an independent observation of the hidden state or model.','The repeated values are copied from the same summary by premise.'),('If a later display contains a new conditional rate, it is outside the unchanged-summary branch.','The data now differ in a decision-relevant coordinate.'),('Future access to such a rate remains a separate empirical/channel question.','The formal model supplies no future retrieval event.')])
t.children(f,[('Different conditional matrices can be compatible with the same aggregate check.','A andB supply exact witnesses.'),('Verifying only aggregate accuracy cannot select between these two matrices.','Both pass exactly the same aggregate equality.'),('A test of sensitivity or specificity can distinguish A fromB if one of these two is known to be the actual model.','The two given conditional rates differ; the two-model restriction is explicit.')])
t.children(h,[('Changing price to0 makes buy’s net value1.8 in A.','Remove the price1 subtraction from gross1.8.'),('This zero-price comparison extends the original paid case rather than refuting it.','The price premise has changed while both arithmetic results stand.'),('The regret .2 is measured in the declared payoff units, not as an error probability.','It is1−.8, a utility difference.')])
t.children(i,[('A mixed policy buying with probability q has regret .2(1−q) in B.','Expected mixture payoff q×1.2+(1−q)×1; subtract from optimum1.2.'),('The same mixture has regret .2q in A.','Expected mixture payoff q×.8+(1−q)×1; subtract from optimum1.'),('A stochastic policy is outside the deterministic-selector impossibility statement.','Its distribution may be fixed while the realized choice varies; expected regret is a new criterion.')])
t.children(l,[('A valid distinguishing feature need not be the entire confusion matrix.','Within the explicitly exhaustive A/B fixture, a single model-identity bit suffices.'),('An arbitrary feature name without different values is insufficient.','The deep branch R14–R20 shows equality remains.'),('Abstaining from the uniform-optimality claim preserves the model ambiguity without inventing a missing rate.','It changes the claim made, not the given observations.')])
t.children(o,[('For the exhaustive two-model set, worst expected regret of the q mixture is max(.2q,.2(1−q)).','The two side expansions enumerate all model regrets under that added scope.'),('This maximum is minimized at q=.5 with value.1.','The increasing and decreasing linear terms intersect at.1; moving either direction raises their maximum.'),('The .1 minimax regret does not supply zero regret or identify the true model.','Both models retain positive expected regret at q=.5 and no new likelihood is observed.')])
assert len(t.n)==46
reg=[{'buy_probability':q,'regret_A':.2*q,'regret_B':.2*(1-q),'worst':max(.2*q,.2*(1-q))} for q in [0,.25,.5,.75,1]]
(R/'ar45-regret-tests.json').write_text(json.dumps({'models':'exhaustively A/B only for this test','rows':reg,'selected_q':.5,'objective':'minimize worst expected regret','not_claimed':'uniform optimality, model identification or human recommendation'},indent=2)+'\n')
t.save('45-ar-summary-insufficiency.md','Separate a missing conditional signal model from the choice of what guarantee remains possible with that missing input.','K12 has just established opposite purchase choices for equal-accuracy signals. Consolidation03 retrieves that finding by conditional likelihood, retaining fixed prior/payoff/price. The original objective of a uniformly optimal summary-only choice is now tested alongside a separately declared two-model minimax-regret alternative.','The summary-only selector is deterministic and its choices are buy or act now. A/B likelihoods, price and payoffs are the exact FRQ42 model. Uniform optimality is the criterion for the deep branch. The side branch explicitly changes to a stochastic buy-probability q and worst expected regret over the exhaustive model set {A,B}; that narrower model-set assumption is not claimed for the original source.','R2/R5/R8/R11 reject uniform optimality for a deterministic summary-only selector. R14/R17/R20 show that an additional constant feature does not fix the missing distinction. The R16 expansion gives a different attainable criterion: in the expressly two-model regret problem, q=.5 yields worst expected regret.1. Conditional rates and objective relaxation are different routes, neither an inferred human outcome.','The performed ar45-regret-tests.json compares q=0,.25,.5,.75,1 and selects .5 for the declared worst-regret criterion. Its maximum regret .1 is below the .2 of either fixed action; no claim of zero regret follows. AV50 now receives this randomized two-model policy and must verify the exhaustive-model and linear-expectation assumptions before retaining it.','K13: under a newly explicit two-model minimax-regret objective, the actual model choice changes from either unsupported fixed action to a .5 mixture and halves worst expected regret from.2 to.1. This is a finite decision-model benefit; it neither identifies the signal nor prescribes behavior to the user.','KEEP')
print('AR44/45 each have46 nodes,7 edges and3 children per expanded node.')
