from write_records import save,BASE
import json,itertools

def table(headers,rows):
 return '| '+' | '.join(headers)+' |\n|'+ '|'.join(['---']*len(headers))+'|\n'+'\n'.join('| '+' | '.join(str(x).replace('|','/') for x in r)+' |' for r in rows)

specs={1:{
'Goal identity':['Preserve the exact requested action','Retain the named actor','Retain the requested object','Retain the declared time horizon','Retain hard constraints','Label an inferred purpose','Keep alternative interpretations separately','Reject an unauthorized goal substitution'],
'Input availability':['Detect a missing source','Distinguish inaccessible from nonexistent input','Retain source version','Retain units on numeric inputs','Represent unknown inputs explicitly','Reject malformed dates before sequencing','Preserve provided counterexamples','Separate user statements from assistant assumptions'],
'Option creation':['Include the strongest ordinary continuation','Include a no-change candidate where feasible','Include a preparation candidate','Include a representation change candidate','Include a timing change candidate','Include a resource change candidate','Include a coordination change candidate','Preserve an unconventional derived alternative'],
'Evidence fit':['State each option input conditions','State evidence population or constructed scope','Separate observation from prediction','Separate performance from explanation','Retain negative evidence','Reject transfer beyond measured setting as unproven','Preserve unresolved causal attribution','Link a consequence to its performed operation'],
'Action constraints':['Represent an explicit budget','Include preparation cost in bundle cost','Represent resource exclusivity','Represent required authority','Represent task deadline','Preserve prerequisites in order','Detect a cycle in action dependencies','Reject a missing prerequisite at commitment'],
'Choice criteria':['Retain criterion version','Retain criterion owner','Distinguish threshold from maximization','Keep unmeasured intangibles visible','Prevent double counting identical effects','Retain the comparison under previous criteria','Calculate dominance only on declared dimensions','Expose the crossover of a weighted decision'],
'Execution interface':['Transmit task revision','Transmit exact operation input','Name output contract','Name endpoint owner','Return explicit error state','Reject an obsolete returned revision','Deduplicate repeated returned identity','Retain an interrupted action state'],
'Consequence assessment':['Compare expected with actual consequence','Keep the initial baseline visible','Separate repair success from first-pass success','Preserve an unchanged result','Classify a harmful result explicitly','Do not infer human benefit from model agreement','Do not infer weight updates from context change','Retain limits on measurement'],
'Revision control':['Reopen a rejected inference','Invalidate descendants of a removed premise','Retain useful incompatible alternatives','Preserve original sources unchanged','Limit automatic retries','Allow the current requester to stop','Avoid committing an unreviewable irreversible action','Record the reason a selected option changed'],
'Usability and maintenance':['Give a direct answer at the relevant level','Keep useful scope next to recommendation','Provide a readable local artifact','Separate provenance from live decision view','Retain an empty-state explanation','Make missing evidence visible in handoff','Provide a boundary case for reuse','Do not turn method bookkeeping into the product flow']},2:{
'Retention identity':['Assign stable identity to a retained result','Preserve result creation context','Retain actor type with result','Retain original goal wording','Preserve source edition identity','Preserve condition under which result helped','Preserve observed negative case','Distinguish a retained proposal from observed benefit'],
'Future retrieval':['Index by a concrete reuse trigger','Return original evidence with retrieved result','Return scope before reapplication','Return criterion version','Allow a query to return no match','Distinguish absent from deleted entries','Detect a missing retained artifact','Do not claim retrieval from saving alone'],
'Temporal validity':['Retain the observation date','State a validity window when known','Represent unknown durability','Flag a changed environment','Flag a changed goal','Flag a changed authority','Flag a changed input format','Keep historical truth separate from present fit'],
'Long-term resources':['Count recurring maintenance separately','Retain setup versus per-use cost','Retain the recurrence crossover','Represent retention capacity','Represent restoration cost','Represent deletion reversibility','Represent migration effort','Do not assume repeated use will occur'],
'Learning evidence':['Record the next actual recurrence','Record whether retrieval happened','Record whether eligibility was accepted','Record the performed operation at recurrence','Record the observed recurrence consequence','Retain competing causes of recurrence success','Preserve a failed transfer','Do not treat repetition of wording as transfer'],
'Criteria evolution':['Preserve earlier criterion weights','Retain the reason a criterion changed','Name who authorized criterion revision','Recompute old options under new criteria separately','Preserve old comparison results','Identify a new hard constraint','Test whether a new criterion is merely outcome rationalization','Keep disagreement about values visible'],
'Interface evolution':['Record reader format version','Maintain an explicit migration mapping','Reject unknown incompatible versions','Preserve original bytes during migration','Retain semantic exceptions across conversion','Distinguish portable description from executable command','Verify endpoint availability at execution','Do not forecast host capability without evidence'],
'Coordination continuity':['Name the current accountable owner','Transfer pending status explicitly','Retain work already performed','Retain blocked prerequisites','Reject late work for obsolete goals','Retain cancellation state','Avoid duplicate downstream action after retry','Name a concrete escalation endpoint'],
'Reliability and recovery':['Keep a recoverable previous accepted state','Detect a damaged evidence reference','Distinguish copy redundancy from independent evidence','Represent common-cause failure','Separate repair time from waiting time','Test recovery on a constructed missing input','Retain both failure and repair evidence','Expose unknown operational reliability'],
'Agency and retirement':['Allow a user to decline reuse','Allow goal change without rewriting history','Avoid preserving unwanted human attributes','Retire a contradicted recommendation','Keep a retirement reason','Retain needed provenance for retired entries','Compare retention against reconstruction burden','Do not execute an unactioned future promise']}}
roles=['requester','current operator','source owner','evidence reviewer','action executor','affected person','tool host','maintainer','future operator','integrator']
for n,groups in specs.items():
 rows=[]
 for c,(cat,items) in enumerate(groups.items()):
  for k,item in enumerate(items):
   i=len(rows)+1;rows.append({'id':f'R{n}-{i:02}','category':cat,'stakeholder_role':roles[c],'requirement':item,'priority':'MUST' if k<4 else 'SHOULD','source':'shared selector requirement or explicitly derived design condition','verification':f'An input exercising "{item}" yields the specified retained field or rejection, with evidence path.','status':'specified; implementation not presumed'})
 (BASE/f'requirements-{n}.json').write_text(json.dumps(rows,indent=2))
 conflict_pairs=[(1,7,'identity versus ambiguous interpretation','retain alternatives without replacing exact wording'),(9,10,'missing versus inaccessible','use separate unavailable states'),(17,24,'ordinary continuation versus unusual option','compare both on input fit'),(25,30,'reusable fit versus transfer restriction','carry conditions with reuse'),(33,35,'budget versus exclusivity','joint schedule includes both'),(41,46,'new criteria versus historical comparison','version the decision'),(49,54,'dispatch versus obsolete return','recheck revision on return'),(73,76,'direct answer versus provenance','direct decision view plus source links')]
 conflicts=[{'a':rows[a-1]['id'],'b':rows[b-1]['id'],'tension':why,'resolution':res} for a,b,why,res in conflict_pairs]
 # Evaluate pair inventory explicitly for syntactic oppositions; semantic eight conflicts are above.
 paircount=len(rows)*(len(rows)-1)//2
 (BASE/f'requirements-{n}-conflicts.json').write_text(json.dumps({'all_pairs_considered':paircount,'material_checks':conflicts,'no_claim':'An enumerated pair count is not proof no semantic conflict exists.'},indent=2))
 body=f'''System boundary: {'a present intervention selector from goal to revised action' if n==1 else 'a retained-result system from creation through reuse and retirement'}. Inputs are stated goals, evidence and resource conditions. Outputs are eligible choices, rejected transfers and explicit unresolved states. Human preferences are not inferred as measurements; external execution requires its actual host. This is a design specification applied to a constructed case, not an assertion a production system exists.

Stakeholders are ten distinct design roles, not ten interviewed people: {', '.join(roles)}. Requester retains direction; operator needs feasible work; source owner needs source integrity; reviewer needs assessable evidence; executor needs a contract; affected person needs agency; host limits actions; maintainer needs recovery; future operator needs fit; integrator needs explicit dependencies. Interests follow from each role's function and remain revisable.

Eighty specific requirements across ten categories:

{table(['ID','Category','Role','Priority','Required behavior'],[[r['id'],r['category'],r['stakeholder_role'],r['priority'],r['requirement']] for r in rows])}

All MUST requirements name a specific retained object, operation or rejection. Their test is an input with and without the named condition, followed by inspection of the output. They are technically implementable within a constructed local selector; human preference validity and future retrieval remain external unresolved conditions. Forty are MUST and forty SHOULD. Optional interface styling is COULD; unauthorized substitution, invented human outcomes and automatic future execution without a mechanism are WON'T.

Eight material conflict checks and resolutions:

{table(['A','B','Tension','Resolution'],[[x['a'],x['b'],x['tension'],x['resolution']] for x in conflicts])}

Hidden-input prompts applied: missing input→explicit unavailable state; malformed input→reject before sequencing; 10× scale→bounded index and capacity condition; dependency down→retained blocked state; unexpected user change→new goal revision; first interaction→current goal capture; last interaction→pending handoff; day two→recheck validity; error→reason and prior state; empty→no eligible result; worst-fit user→unseen preference preserved as unknown; embarrassing failure→asserted human outcome without evidence withheld; ordinary competitor→direct useful answer included; hated burden→attention cost counted; stopping→requester can decline. These are design conditions, not outcome observations.

Actual transformation: {'the concrete plan S+C+E now carries prerequisite S, 55-unit total, exact criterion version and return revision. The earlier output-only candidate lacked these interface obligations. The requirement for resource exclusivity additionally rules out simultaneous use of one exclusive tool by S and E.' if n==1 else 'the retained lookup entry now carries three distinct states: historical result remains valid, current-fit unknown after an environment change, and future retrieval unobserved. A changed reader version marks the executable command unavailable while preserving the portable description.'}

The change is applied to the design object. Whether all eighty requirements are worth implementation remains open; the original depth floor broadens discovery but does not mandate a bloated production product.'''
 save(f'098-requirements-{n}','requirements',f'{"Present action" if n==1 else "Long-term reuse"} requirements at system boundaries','Change a system design by surfacing previously implicit boundary requirements.', 'I would begin with the central successful path. The initial design does not yet specify behavior for every missing, changed or expired condition.',body,'The concrete design now has an explicit resource-exclusivity rejection.' if n==1 else 'The retained-result design now preserves historical truth while marking present-fit and executable continuation independently.','The changed case now has a definite outcome under the specified boundary. Eighty listed requirements alone are not evidence of an implemented system.','KEEP' if n==1 else 'UNRESOLVED','Category tables expose missing boundaries; the next architecture groups these conditions by owner rather than reproducing eighty independent services.','Prototype one boundary; remove a low-value requirement; obtain missing stakeholder preference evidence.',depth='Original 8x floors: 80 requirements, 10 categories, 10 stakeholder roles, 8 conflict checks. The record supplies these; roles are design perspectives rather than fabricated consultations.')
