from write_records import save,BASE
import json
# Each row is an independently specified analytical proposition, an AR consequence,
# a same-claim AW countercase (or explicitly failed attempt), and a derived alternative.
# These are candidates, not fabricated prior user beliefs.
sets={
'journey-budget':[
('Selecting by direct benefits alone is sufficient for every feasible bundle in the four-action instance.','The source precursor could be omitted from cost accounting without losing feasibility.','C+E+G lists cost60 but requires S; actual total70 exceeds60.','Bundle feasibility includes every transitive prerequisite.','REJECTED'),
('Every prerequisite in the declared graph must be present for its dependent selected action to be feasible.','Selecting C requires S in the same completed plan.','Attempted missing-S case is infeasible by the declared edge S→C; it does not refute the claim.','No replacement derived from the failed countercase.','VALIDATED'),
('A zero-direct-value precursor cannot be part of the optimal bundle.','S would be excluded from the optimum.','The feasible maximum S+C+E has value58 and includes S with direct value0.','An enabling precursor can enter the optimum through dependent value.','REJECTED'),
('The highest-value single action determines the optimal feasible bundle.','Choosing C would settle the full allocation.','C has value40, but S+C+E adds E and reaches58 within55.','The optimum is over feasible subsets rather than single-action rank.','REJECTED'),
('A budget of40 still permits the old S+C+E plan.','The old plan would remain eligible after the budget change.','S+C+E costs55, which exceeds40.','The changed budget reopens the bundle choice.','REJECTED'),
('At budget40, S+C is the maximum-value feasible bundle in the declared instance.','The new bundle can retain comparison value40 while dropping E.','Attempted E+G countercase also costs35 but has value26; exhaustive subsets contain no better feasible option.','No replacement follows from this failed countercase.','VALIDATED'),
('Subtracting the already-spent source cost again improves the current remaining-work decision.','S would be charged twice in the same future-choice budget.','If total budget60 already records S10 spent, a remaining budget50 must price only remaining actions; charging S again leaves40 incorrectly.','Keep spent and remaining costs distinct while preserving total feasibility.','REJECTED'),
('A preparation action remains worthwhile when no matching later use occurs.','P would be worth6 even when n=0 and yields no benefit.','At n=0 prepared route costs6 and direct route costs0 under a work-saving objective.','Preparation value depends on a valid future-use horizon.','REJECTED'),
('For costs A=2n and B=6+n without expiry, B is cheaper exactly when n>6.','All integer n≥7 favor B and n=6 ties.','Attempted n=6 refutation produces a tie, not B cheaper; algebra n>6 is exact.','No alternative is supported by that failed refutation.','VALIDATED'),
('Expiry can be ignored after a prepared option becomes numerically cheaper.','The n10 option would be eligible even when its setup expired at5.','The model forbids reuse after5, so numerical cost16 versus20 does not make B eligible.','Eligibility and comparative cost are distinct predicates.','REJECTED'),
('A lower cost always establishes higher usefulness.','The direct two-distinction response would dominate the complete four-distinction one.','The task requires four distinctions; direct cost2 fails that requirement while complete cost5 fits a six-unit deadline.','Adequacy can be a hard condition before cost comparison.','REJECTED'),
('Removing a truly identical duplicate option leaves the achievable optimum unchanged.','The same cost/value/condition point remains achievable through its twin.','Attempted removal of the only independently checked version changes the identity premise and is not a counterexample.','No replacement follows; equality must remain exact.','VALIDATED'),
('The stipulated value58 proves this plan helps the user by58 units.','A computed objective would be read as measured human benefit.','The value numbers are declared inputs and no human response was observed.','The result proves a finite optimization property, with human benefit unresolved.','REJECTED'),
('A feasible bundle remains feasible when only its budget increases.','Every previously affordable sum remains under the larger bound.','A changed authority would refute a broader claim but does not change only budget; that attempt fails.','No replacement is derived for the exact monotonicity claim.','VALIDATED'),
('More time spent on analysis necessarily improves the selected bundle.','Additional work could never leave the optimum unchanged or consume a useful action slot.','Once all16 subsets are evaluated, repeating them changes no optimum and consumes work.','Marginal analysis value depends on remaining decision uncertainty.','REJECTED'),
('A useful precursor can earn its cost through a later operation even with no immediate benefit.','S can be retained because it enables C.','The no-later-use case shows the claim is existential, not universal; it does not refute the supplied S+C+E witness.','No alternative is derived from the failed universalized objection.','VALIDATED'),
('The current four-action optimum is robust to unknown nonadditive interactions.','The sum58 would remain sufficient even if E duplicates all of C’s useful content.','If E adds0 after C while G adds8, S+C+G becomes better than S+C+E under the changed interaction model.','Additive optimality stays conditional on the declared value model.','REJECTED'),
('The user’s intrinsic reason for requesting this optimization is established by the computed optimum.','A mathematical result would determine the user’s terminal value.','The same optimum serves learning, efficiency or curiosity; no elicitation answer identifies one.','The practical goal is supported while intrinsic purpose remains unknown.','REJECTED')],
'journey-continuity':[
('A saved result is sufficient for successful later reuse.','Every saved entry would be used appropriately at its next recurrence.','A saved file can be inaccessible to the future reader, so reuse does not occur.','Successful reuse requires access, retrieval and fit in addition to retention.','REJECTED'),
('Historical truth becomes false whenever present applicability changes.','A criterion revision would invalidate the arithmetic previously computed.','v1 A4.4>B3.4 remains true under .8 weight while v2 reverses the current choice.','Historical result and present eligibility are separate state dimensions.','REJECTED'),
('With A=(5,2), B=(3,5), fidelity weight w, A wins exactly when w>.6.','A’s retained recommendation must be conditional on the recorded weight.','At w=.6 both totals3.8 tie; the boundary does not refute the strict inequality.','No replacement is derived from the failed tie countercase.','VALIDATED'),
('A later B choice proves the earlier A choice was mistaken.','The revision would erase the old winner.','A is correct at w=.8 and B at w=.3; the changed criterion explains both.','A revision can be warranted by a new objective rather than a past error.','REJECTED'),
('Reader-compatible migration proves semantic compatibility.','Converted entries would preserve all useful scope.','A parser can accept a migrated record that dropped its exception; syntax survives while meaning changes.','Migration needs a scope-preservation comparison separate from parsing.','REJECTED'),
('Retaining every entry has no continuing cost once saving is complete.','The future work budget would exclude review and retrieval.','The declared stock model charges one maintenance unit per retained entry per year;20 entries cost20/year.','Retention entails recurring exposure in a model that includes maintenance.','REJECTED'),
('Three scenarios sharing a property make it an unconditional prediction.','Omitted futures would be excluded without evidence.','All three scenarios can assume a compatible reader while a fourth has none.','A shared scenario property is conditional on scenario coverage.','REJECTED'),
('A portable description is the same thing as an executable continuation.','A text contract would execute even without a dispatch host.','The disruption scenario leaves a readable description but no dispatch facility.','Execution needs an available authorized mechanism in addition to description.','REJECTED'),
('An invalid current recommendation must always be deleted with its evidence.','Rejection would erase the information needed to understand its earlier fit.','The v1 result is useful historical evidence after v2 becomes current; deletion loses a valid comparison.','Retirement can remove current eligibility while retaining provenance.','REJECTED'),
('Copying one observation into two files gives two independent replications.','Evidence confidence would increase merely by duplication.','Both files depend on the same original observation and share its error.','Copies improve access redundancy, not evidential independence.','REJECTED'),
('An exact trigger match proves the next use will help.','No new performance check would be needed on a matching label.','A lookup with given criteria can still contain incorrect criteria; the trigger is eligibility evidence, not outcome proof.','Trigger matching permits a bounded candidate, with actual consequence still evaluated.','REJECTED'),
('A changed criterion version should be preserved with its comparison.','Both past and present scores remain reconstructable.','The attempted claim that versioning forces a preferred criterion confuses recording with endorsement.','No replacement follows; versioned comparisons can retain disagreement.','VALIDATED'),
('A result can remain historical evidence while current fit is unknown.','The record can honestly hold established and unresolved statuses at different scopes.','An objection demanding one global true/false status ignores the two different propositions.','No alternative is supported by that failed conflation.','VALIDATED'),
('The setup crossover n>6 remains valid after per-use costs become equal.','A prepared route with equal running cost would eventually repay positive setup.','A=n and B=6+n never cross.','The general inequality is n(a−b)>setup within validity.','REJECTED'),
('Waiting for actual recurrence always loses the setup opportunity.','Preparation would have to be purchased before any evidence of use.','If setup can be performed just before recurrence at the same cost, waiting preserves the option without loss.','Preparation timing depends on lead time and information, not recurrence fear alone.','REJECTED'),
('A future reader’s value agreement is established by the current assistant’s agreement.','Present model agreement would predict a person’s future priorities.','No future reader response is present; agreement is unobserved.','Future value alignment remains an empirical and agency-dependent question.','REJECTED'),
('A superseded goal can be reopened without rewriting its old evidence.','A new current decision can use the historical record as input.','An attempt to reuse the obsolete action automatically violates current eligibility, not historical retention itself.','No replacement follows for the exact reopen-with-history claim.','VALIDATED'),
('Every useful result must be retained forever.','Finite storage and review would never justify retirement.','In the declared maintenance model, an expired redundant entry adds cost and no eligible use.','Retention is a conditional choice over future use, cost and provenance needs.','REJECTED')],
'journey-agency':[
('A task-name match is sufficient authority to accept any returned action.','Every result labeled T could enter the current plan.','T revision1 returns after T revision2; label match accepts obsolete work.','Acceptance includes current target revision and authority.','REJECTED'),
('A displayed stop state is sufficient to prevent future dispatch.','No dispatch transition would need to read the flag.','The display-only model still dispatches B because its action gate ignores stop.','The active condition belongs at dispatch and acceptance transitions.','REJECTED'),
('A cancelled task can still accept late work because the work was started earlier.','Dispatch-time permission would override present cancellation.','The current active flag is false when A returns; acceptance would violate current control.','Historical output can be retained without current acceptance.','REJECTED'),
('Describing a human relocation means the assistant performed it.','The description would count as a change to the person’s setting.','The person has not acted or reported a location change.','Prepared advice and performed human action are distinct events.','REJECTED'),
('A reported feeling proves an independently measured task improvement.','Self-report alone would settle performance.','A person can report ease while giving a wrong answer; the evidence objects differ.','Report and task result are retained separately.','REJECTED'),
('Observed task improvement proves the person values the intervention.','The assistant could infer endorsement from correctness.','Correct performance is compatible with the person declining the method’s burden.','Performance and endorsed value require different evidence.','REJECTED'),
('Description-only authority permits execution when execution looks beneficial.','A favorable prediction would expand the action scope.','The declared permission set contains describe but not execute.','Benefit expectation does not add an absent permission.','REJECTED'),
('The exact active-state gate blocks all returns after its flag is false in the finite model.','Late A is retained but not accepted.','An unmodeled side effect is outside the return gate claim; the four-event trace has no post-stop acceptance.','No replacement follows from the failed broader objection.','VALIDATED'),
('Rejecting a late result requires destroying its historical output.','Cancellation would delete potentially inspectable work.','The trace can retain A with cancelled status while acceptance stays empty.','Retention and authorization are independent decisions.','REJECTED'),
('An output contract establishes the semantic correctness of the output.','A well-shaped false sentence would be correct.','The complete packet can carry an unsupported universal claim without failing field checks.','Contract validation and semantic verification remain distinct.','REJECTED'),
('One accountable owner must perform every component’s work personally.','A responsibility map would forbid tools or support.','The coordinator can own acceptance while a tool produces a described result under contract.','Accountability and execution allocation are distinct roles.','REJECTED'),
('A current host capability proves the same capability will exist in eighteen months.','A present dispatch command would support a future promise.','The disruption scenario removes dispatch with no contradiction of current availability.','Future execution is conditional on then-current host capability.','REJECTED'),
('A duplicate accepted result can be treated as a second independent action without checking identity.','Retry would create two accepted action entries.','The return stream repeats one identity; a second side effect would be duplication.','Identity deduplication preserves one acceptance per returned action.','REJECTED'),
('A user can decline a prepared intervention while its factual content remains true.','Rejection of use need not erase evidence.','The attempted objection that truth compels acceptance confuses fact with preference.','No replacement follows from that failed objection.','VALIDATED'),
('If a proposed action is in the exact permission set, membership alone guarantees overall eligibility.','Budget, revision and stopped state could be ignored.','Describe is authorized but a stopped task still forbids new work.','Eligibility conjoins authority with current goal and resource conditions.','REJECTED'),
('Reversible local representations can be compared without pretending to change a person’s body.','The assistant can revise a table now and leave a human action pending.','A claim that all mind change must be bodily replaces the supplied actor distinction.','No replacement follows for this observed local capability.','VALIDATED'),
('Calling an intervention beneficial makes the person’s disagreement a failure to understand.','Disagreement could be discounted without examining values.','A person can understand the tradeoff and rationally prefer a different burden or goal.','Disagreement remains an input that can revise the intervention target.','REJECTED'),
('A pending future intervention becomes completed when a continuation plan is well written.','A textual plan would stand in for its trigger and action.','No trigger has occurred and no authorized scheduler exists for this case.','Plan quality and completion status are separate propositions.','REJECTED')]
}
# Two independent audits use distinct claims tied to original program promises and current source mechanics.
sets['audit-purpose']=[
('A coherent goal chain is sufficient to establish a plan’s real-world benefit.','No outcome observation would be needed after coherence.','The chain can be coherent while the required source is inaccessible.','Coherence and executable prerequisites are distinct.','REJECTED'),
('Every action has an explicitly known intrinsic goal in the present evidence.','All action chains could end with a stated human value.','The current user’s terminal value was not elicited; practical goals are available without that answer.','A practical chain can end with intrinsic purpose unknown.','REJECTED'),
('Every goal-chain link that sounds plausible is causally established.','Proposed means could be treated as tested mechanisms.','More prose can plausibly promise clarity while a concrete reader test remains absent.','Proposed causal links retain predicted status until evidence exists.','REJECTED'),
('Following all source steps guarantees a useful response to every input.','Procedure completion would imply task fit for all cases.','An eighty-requirement expansion can add irrelevant burden to a one-fact request.','Procedure fit depends on the live question and total cost.','REJECTED'),
('The program’s explicit quota can be deleted when a smaller example is easier.','The agent could substitute a reduced deliverable without consent.','One example per skill does not satisfy the assigned repetitions.','Routine implementation freedom preserves the requested program scope.','REJECTED'),
('A known-source hash establishes exact archived bytes, conditional on comparing the emitted file.','An unrelated hash cannot serve as the receipt comparison.','The saved stdout digest equals the receipt; a different file would fail this exact check.','No replacement follows from the unrelated-file objection.','VALIDATED'),
('Source-integrity verification establishes faithful execution of its operations.','A saved original would count as a finished application.','A source can be loaded with no concrete products generated.','Source fidelity and execution fidelity require different evidence.','REJECTED'),
('An output with the expected headings necessarily satisfies the original depth floor.','Empty labeled branches would earn depth.','Eight headings with no parent-child inference contain no recursive edges.','Depth comes from actual valid inferences and distinct findings.','REJECTED'),
('Independent repetition is established by changing only a document title.','One case could earn every allocated repetition.','Identical input and consequence under a new title contain no distinct application.','Repeated applications need substantive target/input variation.','REJECTED'),
('An honest unresolved verdict can still be a useful result.','The program can retain a promising candidate without claiming benefit.','An objection requiring all results to be keeps conflicts with the explicit requirement to retain failures.','No replacement is derived for the scoped usefulness of warranted uncertainty.','VALIDATED'),
('Any unfavorable result should be removed from a consolidation’s provenance.','The user would see only successful transformations.','Removing the failed budget recomputation conceals the actual repair path.','Selected conclusions can coexist with full failure provenance.','REJECTED'),
('A hypothetical countercase is equivalent to observing that failure in a person.','Constructed failures would establish human incidence.','No person participated in the budget or queue models.','A countercase can refute a formal universal without estimating incidence.','REJECTED'),
('A genuine counterexample refutes a universal quantified over that exact case.','The universal cannot survive by silently weakening its scope.','A counterexample outside the domain fails, but one inside is decisive by universal quantification.','No replacement follows; the domain must be the claim’s original domain.','VALIDATED'),
('A method can add value only by making the model agree more with the user.','Disagreement or retained uncertainty would never help.','The corrected40-budget bundle disagrees with a prior mistaken suggestion and satisfies the declared constraint.','Useful change can correct a working choice without manufacturing agreement.','REJECTED'),
('The best organization is independent of its later use.','One permanent ordering would win every query.','Chronology answers event order while dependency adjacency answers prerequisite queries.','Organizational comparison is indexed to concrete later uses.','REJECTED'),
('Consolidation can introduce a new unsupported substantive claim while citing old keeps.','A new conclusion would inherit evidence it never received.','None of the retained finite cases establishes human transfer, so synthesis cannot add that claim.','Consolidation rearranges established findings without inventing new evidence.','REJECTED'),
('A local correction changes model weights.','The new table would imply a training update.','Available operations change files/context; no weight-update event is observed or available.','The demonstrated actor change is current working state.','REJECTED'),
('Current behavioral evidence can be inspected without proving general reliability.','The assistant can examine the actual correction and its boundary.','A future failure would limit transfer, not erase this observed finite correction.','No replacement follows from the failed universal-reliability objection.','VALIDATED')]
sets['audit-evidence']=[
('Fifty passing field-contract cases establish that all returned propositions are true.','Semantic review could be replaced by format tests.','A complete packet containing a false universal still passes its required fields.','Finite contract correctness and propositional truth need different tests.','REJECTED'),
('A successful repair proves the original attempt was correct.','The first budget suggestion would become historically correct after editing.','The original E+G suggestion lost to S+C at40; the repair changed that answer.','Repair success is distinct from first-pass accuracy.','REJECTED'),
('A numerical depth floor proves semantic depth whenever its count is met.','Eighty disconnected sentences would certify recursive analysis.','A count can contain duplicates or invalid inference edges.','Counts are necessary declared floors, not semantic certification.','REJECTED'),
('Every additional serial verification component improves mission reliability.','Adding a required component could never lower successful completion probability.','Under independent series model Rtotal is multiplied by Ri<1, decreasing uptime reliability.','Verification value trades against operational failure and overhead.','REJECTED'),
('Operational availability is determined only by active repair duration.','Waiting and administrative delays could be dropped.','The declared downtime11 contains repair2, logistics8 and administration1; omitting9 overstates availability.','Total downtime includes nonrepair delays.','REJECTED'),
('Redundant copies eliminate a common-cause failure.','A shared unavailable source could be overcome by two references to it.','Both copies fail when their common source fails.','Redundancy benefit depends on failure independence and common-cause exposure.','REJECTED'),
('A lower-discounted-cost option must have higher human value.','Cost accounting would settle unmeasured experience and goals.','The lifecycle model stipulates operations and has no measured human-valued outcome.','Cost is one criterion under separately established adequacy and values.','REJECTED'),
('An experiment designed after inspecting its outcomes can be called prospectively specified.','Observed data could determine the supposedly prior hypothesis.','The time order contradicts the definition of prospective specification.','Exploratory findings can motivate a new prospective test.','REJECTED'),
('A two-arm sample-size calculation establishes adequate power for a four-cell interaction.','The retrieval contrast N would support an interaction claim automatically.','An interaction is a different estimand with additional cell variation not in that power model.','Each confirmatory estimand requires its own power assumptions.','REJECTED'),
('A nonsignificant experiment establishes no effect.','An imprecise estimate would rule out all meaningful effects.','A wide interval can include zero and a meaningful effect.','Nonsignificance can leave the effect unresolved.','REJECTED'),
('A synthetic model’s exact output remains exact under its stated recurrence and initial state.','Recomputing those definitions should reproduce its finite trace.','Changed rates alter the model, not the truth of the original computed trace.','No replacement follows from a changed-model objection.','VALIDATED'),
('A loop’s negative sign guarantees monotone convergence under any delay and gain.','The delayed controller could not overshoot.','g=.8 with one-step delay overshoots10 in the executed recurrence.','Sign, gain and delay jointly determine dynamic behavior.','REJECTED'),
('Increasing pipeline arrivals always increases completed output at a fixed bottleneck.','The five-arrival policy would outproduce the three-arrival policy.','Both share the one-unit eligibility bottleneck; the executed completion count is unchanged while backlog increases.','Input generation and bottleneck throughput are distinct.','REJECTED'),
('A smaller unfinished-work stock always means greater output.','Admission control would necessarily increase completions.','Bounded admission lowers backlog with the same bottleneck throughput in the model.','Accumulation and output are separate response variables.','REJECTED'),
('A conditional formal result can be useful without forecasting its parameters.','The crossover can guide what to observe next.','Unknown recurrence prevents a real-world forecast but does not erase the algebraic decision boundary.','No replacement follows from that scope-preserving objection.','VALIDATED'),
('All system goals should be changed before any parameter is adjusted.','Gain reduction would be inappropriate even when it meets the existing target better.','The fixed-target controller reduces oscillation by changing gain from.8 to.4.','Intervention choice follows the actual mechanism and available control.','REJECTED'),
('Missing original execution tools can be replaced with a new script and still called original execution.','A fabricated session_learning implementation would satisfy the named archived dependency.','No archived script exists; a new implementation would be an adaptation.','The original dependency remains blocked while available substantive operations proceed.','REJECTED'),
('A complete structural ledger can coexist with partially executed original procedures.','The ledger can identify every slot while exposing unmet requirements.','The objection that complete indexing means complete execution changes the predicate being evaluated.','No replacement follows from that conflation.','VALIDATED')]

def build_araw(key,deepchain):
 rows=sets[key];claims=[];findings=[];cert=[]
 for i,(claim,ar,aw,alt,verdict) in enumerate(rows,1):
  cid=f'C{i}';claims.append({'id':cid,'claim':claim,'type':'analytical candidate','voi':'high' if i<=8 else 'medium','prior_status':'candidate; not attributed as a user belief'})
  def add(parent,kind,text,strength,bedrock=None):
   fid=f'F{len(findings)+1}';findings.append({'id':fid,'parent':parent,'kind':kind,'text':text,'strength':strength,'bedrock':bedrock});return fid
  fa=add(cid,'AR',f'Assume exactly C{i} right: '+ar,'necessary conditional on the frozen claim')
  fw=add(cid,'AW',aw,'fatal' if verdict=='REJECTED' else 'failed countercase','LOGIC/OBSERVE in the declared case')
  if verdict=='REJECTED':
   fal=add(fw,'ALTERNATIVE',alt,'derived from the stated wrongness')
   far=add(fal,'AR',alt+' The original countercase is represented without asserting the refuted universal.','necessary for the specified countercase','LOGIC')
   faw=add(fal,'AW','If the newly required condition is unknown in a later case, this alternative does not establish that case’s successful outcome; its current corrective claim is restricted to the exhibited countercase.','boundary to transfer, not refutation','LOGIC')
   refs=[fa,fw,fal,far,faw]
  else:
   fb=add(fa,'AW','The supplied attempted countercase changes a premise or a proposition; it fails against the exact scoped implication. No successful contrary case is established here.','failed countercase','LOGIC')
   refs=[fa,fw,fb]
  cert.append({'claim':cid,'verdict':verdict,'decisive':fw if verdict=='REJECTED' else fa,'supporting_findings':refs,'strongest_contrary':fa if verdict=='REJECTED' else fw,'unresolved_dependency':'Transfer beyond the specified case and supplied premises remains untested.'})
 # Reopened exploration: explicit foreclosures, with existing claim parents.
 foreclosure_map={
 'journey-budget':[('C6','At budget40, accepting S+C+E as feasible is foreclosed because its declared cost55 exceeds40.'),('C9','At n=6, calling B strictly cheaper is foreclosed: both declared costs equal12.')],
 'journey-continuity':[('C3','At w=.3, treating A as the maximizing option is foreclosed by A2.9<B4.4.'),('C13','Current-fit uncertainty cannot by itself justify declaring the established v1 arithmetic false; those are different propositions.')],
 'journey-agency':[('C8','After active=false, accepting a late return through the exact modeled active-state gate is foreclosed.'),('C14','A person’s refusal to use a factually true contribution does not license declaring its content false merely because it was declined.')],
 'audit-purpose':[('C6','A file whose digest differs from the emitted receipt cannot pass that exact digest-equality comparison.'),('C13','After a true in-domain counterexample, retaining the same universal as validated is foreclosed by universal quantification.')],
 'audit-evidence':[('C11','The same deterministic recurrence, exact initial state and inputs cannot produce a different mathematical trace without changing a premise or computation.'),('C15','A conditional inequality alone cannot license the factual claim that its future-use antecedent will occur.')]
 }
 for parent,proposition in foreclosure_map[key]:
  findings.append({'id':f'F{len(findings)+1}','parent':parent,'kind':'FORECLOSURE','text':proposition,'strength':'necessary under the frozen claim and explicit case inputs','bedrock':'LOGIC/TEST'})
 # Deep branches are actual dependency chains, not heading counts. Each supplied edge states its added premise.
 depthrows=[]
 for side,nodes in deepchain.items():
  parent='C1'
  for text in nodes:
   fid=f'F{len(findings)+1}';f={'id':fid,'parent':parent,'kind':side,'text':text,'strength':'necessary under the explicit added premise' if 'given' in text.lower() else 'conditional derivation','bedrock':None};findings.append(f);depthrows.append(f);parent=fid
  findings[-1]['bedrock']='LOGIC/TEST';
 # actual two tests available in all subjects: source-match observation + case witness computation, never count source receipt as execution success
 if key=='journey-budget':
  import itertools
  acts=[('S',10,0),('C',25,40),('E',20,18),('G',15,8)]
  choices=[]
  for mask in itertools.product([0,1],repeat=4):
   picked=[a for a,z in zip(acts,mask) if z];names=[a[0] for a in picked];cost=sum(a[1] for a in picked)
   if cost<=60 and ('C' not in names or 'S' in names):choices.append((sum(a[2] for a in picked),cost,names))
  live={'exhaustive_optimum':max(choices),'changed_budget_optimum':max(x for x in choices if x[1]<=40)}
 elif key=='journey-continuity':
  cross=[w/100 for w in range(101) if (2+3*w/100)>(5-2*w/100)]
  original={'claim':'lookup eligible','exception':'discovery untested'};migrated={'claim':original['claim']}
  live={'weight_grid_A_wins':cross,'migration_scope_loss':{'syntax_valid':bool(migrated['claim']),'exception_preserved':'exception' in migrated}}
 elif key=='journey-agency':
  returns=[('active',2,2,'describe'),('stopped',2,2,'describe'),('active',1,2,'describe'),('active',2,2,'execute')]
  live={'acceptance_truth_cases':[{'case':x,'accepted':x[0]=='active' and x[1]==x[2] and x[3] in ['describe']} for x in returns],'human_action_state':{'description_prepared':True,'human_action_observed':False,'executed_human_change':False}}
 elif key=='audit-purpose':
  alloc=json.loads((BASE/'allocation.json').read_text())
  live={'quota_arithmetic':{'required':sum(x['applications'] for x in alloc),'one_per_skill':len(alloc),'reduction_satisfies':len(alloc)==sum(x['applications'] for x in alloc)},'source_vs_execution':{'original_file_exists':(BASE.parent/'sources/systems-gjs.md').exists(),'empty_output_has_products':False}}
 else:
  packet={'claim':'2+2=5','status':'complete','scope':'all arithmetic'}
  live={'contract_vs_truth':{'required_fields_present':all(k in packet for k in ['claim','status','scope']),'claim_true':2+2==5},'serial_reliability':{'one':.99,'two_independent_required':.99*.99,'two_improve':.99*.99>.99}}
 independent=[f for f in findings if not (f['kind']=='AR' and 'The original countercase is represented' in f['text']) and not (f['kind']=='AW' and (f['text'].startswith('If the newly required') or f['text'].startswith('The supplied attempted')))]
 # Count independent propositions after removing repeated scope-review remarks.
 unique_independent=len({f['text'] for f in independent})
 # Every finding remains in full registry, with categories as references to avoid reauthoring it.
 registry={'claims':claims,'findings':findings,'categories':{k:[f['id'] for f in findings if f['kind']==k] for k in ['AR','AW','ALTERNATIVE','FORECLOSURE']},'verdicts':cert,'cruxes':[{'id':f'CRUX-{i+1}','claim':claims[i]['id'],'question':'Does the exact countercase retain the stated domain and premises? '+claims[i]['claim'],'resolution':cert[i]['decisive']} for i in range(8)],'tests':live,'totals':{'claims':len(claims),'findings':len(findings),'independent_propositions_before_semantic_dedup_review':unique_independent,'max_recursive_edges':max(len(v) for v in deepchain.values()),'cruxes':8,'tests_run':2},'contamination':'Original procedure text and prior evidence were already available. Imported instructions do not count as findings; independent countercase derivations and fresh arithmetic are recorded. Self-evaluation is by the same assistant, not an independent assessor.'}
 (BASE/f'{key}-araw-registry.json').write_text(json.dumps(registry,indent=2))
 ctable='| Claim | Frozen proposition | Verdict certificate |\n|---|---|---|\n'+'\n'.join('| '+c['id']+' | '+c['claim']+' | '+v['verdict']+' from '+','.join(v['supporting_findings'])+' |' for c,v in zip(claims,cert))
 ftable='| Finding | Parent | Kind | Concrete proposition / countercase |\n|---|---|---|---|\n'+'\n'.join('| '+f['id']+' | '+f['parent']+' | '+f['kind']+' | '+f['text'].replace('|','/')+' |' for f in findings)
 body=f'''Interpretation: extract and stress-test operational candidates for {key}; these are not claimed to be the user’s beliefs. The actor doing the audit is the same assistant that generated the work: this self-evaluation is not independent confirmation. The requested program is accepted as the governing goal; candidates concern how to fulfill it without substitution.

Meta-ARAW: uncertainty is model fit and epistemic scope. State space includes changed budgets, criteria, access and authority. The competing perspectives are current operator, later consumer and the person retaining control. A favorable verdict is not an objective. Source claims are imported context; the numbered findings below are concrete derivations and countercases, not summaries of the source procedure.

Phase1 exploration is retained in the finding rows, including unsuccessful objections and boundaries that do not refute the parent. A rejected universal stays rejected; its derived alternative is a new proposition. No transfer success is inferred from a bounded countercase.

{ftable}

Phase2 registry: every finding above is copied as a structured record in `{key}-araw-registry.json`, categorized by kind, preserving parent identity and bedrock. All eighteen claims appear in the following certificates. Exact claim + decisive countercase/failed objection + inference to verdict are retained; the alternative does not rescue a refuted universal.

{ctable}

Eight crux questions are attached to C1–C8 in the registry and resolved only at their declared case scope. Two subject-specific finite tests are executed and recorded below. Outcomes: {json.dumps(live)}. They substantiate those exact model distinctions, not the whole procedure’s reliability. The two deeper chains preserve explicit added premises and stop at computed or logical bedrock; duplicate/imported claims do not increase the finding count.

Phase3 synthesis introduces no new finding. Every claim’s AR commitment, AW result and any derived replacement is represented by its certificate above. The pattern is mixed: scoped mathematical/observational claims survive; broad sufficiency claims fail their concrete countercases. Strongest surviving contrary branches are the AR commitments of rejected claims; their exhibited countercase is decisive. Weakest dependencies are relevance to another setting and unknown actual human effects. The next action is the corresponding GJS or GAA decision using these certificates; no new universal claim is added at synthesis.'''
 save(key+'-araw','araw','ARAW: '+key,'Change the operational claims used by the parent goal journey or audit through exact countercases and scoped surviving results.','I have useful candidate policies, but their sufficiency across changing conditions is not established. The candidates below are hypotheses for examination, not invented prior certainty.',body,'Broad sufficiency candidates are rejected where an exact countercase exists; the supported scoped propositions and uncertainty remain distinct.','Concrete countercases change what the parent plan is permitted to infer. Arithmetic/model evidence remains local.','KEEP','Numbered parent-linked findings preserve why each verdict follows; source receipts remain separate.','Test an unmodeled boundary; obtain actual external evidence where needed; compare whether a retained alternative changes the next action.',depth=f"Original 8x floors: {len(claims)} claims, {len(findings)} findings, {registry['totals']['max_recursive_edges']} recursive edges on each developed branch, 8 cruxes, 2 subject-specific executed tests. Repeated scope-review remarks are excluded from the independent-proposition count, which is {unique_independent} before semantic dedup review. Semantic scope and unsuccessful objections remain explicit.")
 return registry
